### ISSUE TITLE
Handshaking - Pegasus Astro UPBv2 (connectivity issue).

### ISSUE THREAD

**Issue by cl330b** [indilib/indi#1003]
Hello,

Ubuntu 18.04
indilib 1.8.0

When attempting to connect to the Pegasus Astro Ultimate Powerbox version 2, I receive the following error.

`[WARNING] Port /dev/ttyUSB0 is already used by another driver or process.` 

dmesg output shows the device is connecting yet indi/ekos fails to connect.

`[ 1671.061223] usb 2-1.2.3.2.7: new full-speed USB device number 35 using ehci-pci
[ 1671.178040] usb 2-1.2.3.2.7: New USB device found, idVendor=0403, idProduct=6015
[ 1671.178043] usb 2-1.2.3.2.7: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[ 1671.178044] usb 2-1.2.3.2.7: Product: UPBv2 revA
[ 1671.178046] usb 2-1.2.3.2.7: Manufacturer: Pegasus Astro
[ 1671.178047] usb 2-1.2.3.2.7: SerialNumber: UPB23J7KZU
[ 1671.180402] ftdi_sio 2-1.2.3.2.7:1.0: FTDI USB Serial Device converter detected
`

Kindly,
Christopher

**Comment by knro** [comment]
well, if you unplug and replug, does it work?

**Comment by toeastro** [comment]
This is fixed.
