### ISSUE TITLE
Pulsar Dome Driver Installation

### ISSUE THREAD

**Issue by jmhirschi** [indilib/indi#1014]
The Pulsar Dome Driver is not available on the site. The syntax to install is not correct. Can you please adapt the information on the related page.
Thank you.

**Comment by knro** [comment]
Which syntax is incorrect?

**Comment by jmhirschi** [comment]
Hello,
Thank you for your quick answer.
I followed the instructions below to add the Pulsar Driver to my Indi setup :
sudo apt-add-repository ppa:mutlaqja/ppa
sudo apt-get update && sudo apt-get install indi-bin
Unfortunately the driver is not available  when I try to add the Pulsar Dome under Ekos setup
----Message d'origine----
De : notifications@github.com
Date : 17/09/2019 - 06:50 (WEDT)
À : indi@noreply.github.com
Cc : j.m.hirschi@bluewin.ch, author@noreply.github.com
Objet : Re: [indilib/indi] Pulsar Dome Driver Installation (#1014)
Which syntax is incorrect?

**Comment by knro** [comment]
Right, it's available for INDI v1.8.2 (not released yet). It would be in the next release. Right now, you can build it from source or use the INDI Nightly PPA.

**Comment by jmhirschi** [comment]
Thank you
I'll test it with the Nightly PPA

**Comment by jmhirschi** [comment]
I've installed the Nightly PPA to test the dome. The driver is now visible in Ekos but when I launch the Indi I've an immediate crash of the Dome driver.
