### ISSUE TITLE
UPB driver issue

### ISSUE THREAD

**Issue by fenriques** [indilib/indi#1018]
It is not easy to check / replicate Over Current behavior on a real device but in indi/drivers/auxiliary/pegasus_upb.cpp starting from 176:

>  // Over Current
>     IUFillLight(&OverCurrentL[0], "POWER_PORT_1", PowerControlS[0].label, IPS_OK);
>     IUFillLight(&OverCurrentL[1], "POWER_PORT_1", PowerControlS[1].label, IPS_OK);
>     IUFillLight(&OverCurrentL[2], "POWER_PORT_1", PowerControlS[2].label, IPS_OK);
>     IUFillLight(&OverCurrentL[3], "POWER_PORT_1", PowerControlS[3].label, IPS_OK);
> 

I think POWER_PORT_1 should be increased to POWER_PORT_2 etc.

**Comment by knro** [comment]
It's fixed, thanks!
