### ISSUE TITLE
Broken frame skip (while guiding)

### ISSUE THREAD

**Issue by mireianievas** [indilib/indi#1021]
I'm on my way to buy a guider to replace the ZWO ASI120mm that displays broken frames, but discussing with a friend who does use that camera with his own custom control software, we were thinking if it would be possible to add some sort of check for the broken frame issue and just skip those frames that are buggy. 

![image](https://user-images.githubusercontent.com/2607760/65509597-1d25e800-ded3-11e9-9e96-b874d673d8fd.png)

I was thinking that maybe some kind of nearest neighborhood interpolation threshold to asses the 'smoothness' of the frame may pick of those frames from the correct ones. What do you think? Or maybe even adding the option to ignore 1 single frame that is an outlier. If you pick a star and the next frame the star is not around, then wait to the next frame.

**Comment by knro** [comment]
Your friend who directly uses the SDK also gets such broken frames? was this discussed with ZWO? It's probably best if they resolve it at the SDK level.

**Comment by mireianievas** [comment]
Well, it is a very well known issue with their first round of cameras and it is just not going to be fixed. But I did not want to enter into that terrain. Bad frames can happen for multiple reasons (e.g. cloud passing, a quick flash from a car or something giving you saturation) and it would be super nice to have some sort of way to react (or not react) to them.

**Comment by PMoff** [comment]
ZWO on their website, shows that with the ASI120MM or MC versions, do not work well under Linux.  They work fine on Windows, and I have used that model for 2 years with PHD2, and APT, and prior to APT, with BYE.

**Comment by knro** [comment]
Right, so this is not an INDI issue per se. It is more of a camera problem.
