### ISSUE TITLE
Double ZWO cameras issue

### ISSUE THREAD

**Issue by terrordrummer** [indilib/indi#1022]
I own a ZWO ASI 178 mc and a ZWO ASI 120 mini cameras, I'm using the first as scope camera and the second as guide camera.

I use kstars/ekos under Mac OSX.

When Ekos connects to the cameras both are immediately recognized and I can set all device's parameters.

Unfortunately, when I use both at the same time (one for pictures and the other for guiding)  very often acquisition from one of the two times out and the whole acquisition session stops.

This happens in particular when I use the ZWO 128 mc as guiding camera, in the average the guiding image capture times out after few minutes, it's really unstable and unusable.

Not sure if this is a driver issue or ekos issue, when I acquire from only one of the two I can do everything without issues for an entire night, when differently I'm acquiring from both camera at the same time one of the two times out very frequently.

Regards,
Roberto

**Comment by knro** [comment]
Does the timeout happen when the primary camera is downloading?

**Comment by knro** [comment]
also, please file ZWO issues at the [3rd party repository](https://github.com/indilib/indi-3rdparty) issues and not here.
