### ISSUE TITLE
Capture module - image flip/rotation. 

### ISSUE THREAD

**Issue by toeastro** [indilib/indi#1044]
I would like to add an image flip and image rotate option in the capture module. The image rotation could be added to the "sequence queue". 

This would be useful for a meridian flip without needing to manually rotate the camera.

**Comment by knro** [comment]
Thanks for the suggestion. However INDI is not KStars. To suggest features for KStars, please submit them at https://bugs.kde.org/

**Comment by toeastro** [comment]
Hi Jasem,

Kstars? This is a suggestion for the ekos capture module. Am I missing something? Thanks.

**Comment by knro** [comment]
Yes, Ekos is part of KStars. INDI is just the control protocol for hardware drivers.
