### ISSUE TITLE
Build: 2019-11-20T07:23:51Z / Ekos crashes with indi-sx-ccd

### ISSUE THREAD

**Issue by escribana** [indilib/indi#1045]
**Ekos crashes with Trius SX35**
Taking pictures with the Trius SX-35 result in random crashes of KStars. Solving with Trius SX-35 crashes always!

**To Reproduce**
1. Connect the SX-35 with Ekos.
2. Do a "Capture & Solve" with the SX-35.
3. Kstars crashes totally after capturing image.

**Expected behavior**
Start to solve received image.

**Screenshots**
None

**Desktop:**
 - OS: Ubuntu
 - Version 16.04

**Log Files**
None

**Workaround**
Downgrading to Build: 2019-11-16T00:05:35Z solves the problem!

(Upgrading from 2019-11-20T07:23:51Z to 2019-11-20T07:23:51Z claimes to upgrade indi-sx to version 1.14, but it doesn't!! Version 1.13 remains in place!)

**Comment by knro** [comment]
Ok, so this is technically a KStars issue, not INDI. However, do you have a backtrace for the Ekos crash? run **gdb -ex run --args kstars**

then when it crashes, type in **backtrace** to get the backtrace and share it.

**Comment by escribana** [comment]
OK! Thanks. I'll do this. But where is the corresponding bug report site for KStars?

**Comment by knro** [comment]
bugs.kde.org
