### ISSUE TITLE
KSTARS 3.3.9, EQMOD startup issue

### ISSUE THREAD

**Issue by CheekyMonkey** [indilib/indi#1051]
Skywatcher EQ5 Mount/EQMOD
Canon 600D DSLR
Altair 80mm refractor
ZWO CCD ASI224MC Guide Camera
MyFocuserPro2 focuser
Stellarmate 1.4.3 (Raspberry Pi 4)
Raspberry Pi 4 (4GB)

After installing the lastest nightly build (KSTARS 3.3.9), I'm seeing that my 
Skywatcher mount no longer connects when the INDI drivers startup.
 
The following message pops during the connection attempt:

**"INDI Driver EQMod Mount crashed"**

![KSTARS V3 3 9 Stellarmate v1 4 3 Raspberry Pi 4 EQMOD INDI driver startup issue](https://user-images.githubusercontent.com/537672/70340034-ec095280-1847-11ea-9ec7-647dd23e081e.png)

**Video walkthrough here**: https://www.youtube.com/watch?v=s60NH5M-u6A

![KSTARS 3 3 9 Stellarmate 1 4 3 EQMOD issue 06 12 2019](https://user-images.githubusercontent.com/537672/70340070-fdeaf580-1847-11ea-9328-83af0c1edadc.png)

Logs attached for reference
logs for 3.3.8 (successful connections)
logs for 3.3.9 (EQMOD mount fails to connect)
[KStars 3.3.8 - EQMOD issue does not occur - log_16-15-29.txt](https://github.com/indilib/indi/files/3933166/KStars.3.3.8.-.EQMOD.issue.does.not.occur.-.log_16-15-29.txt)
[KStars 3.3.9 - EQMOD issue occurs - log_16-11-58.txt](https://github.com/indilib/indi/files/3933167/KStars.3.3.9.-.EQMOD.issue.occurs.-.log_16-11-58.txt)

Rolling back to KSTARS 3.3.8 solves the issue

**For information:**
I'm looking to get the latest FITS header fixes that come with the latest nightly build to allow me to use ASTAP for platesolving

Currently ASTAP fails to solve (CDELT keywords issue) and looking at this[ post](https://www.indilib.org/forum/ekos/5901-astap-astrometry-integration.html?start=72
) there is a fix for the issue in the latest nightlies 

I observe that ASTAP solve works as expected on my setup when given an image with the CDELT keywords in the FITS header

I checked my recent image FITS headers and observe that they do not contain the CDELT keywords, so I'm looking for the recent fix in the latest 3.3.9. nightlies to overcome that

**Comment by knro** [comment]
This is usually a build issue. Did you update since then? still same crash?
