### ISSUE TITLE
ASI ZWO 174 GAIN always at max when in 16 bit RAW 

### ISSUE THREAD

**Issue by fiveseve84** [indilib/indi#1056]
Hi I am using an ASI ZWO 174MM-Cool via USB 3 on an Raspberry Pi 4 4GB model. The camera is powered.

Everthing works fine so far, BUT when setting to 16bit RAW GAIN is always at 400 (maximum). Using 8 bit mode gaing works as expected. To be exact the GAIN settings does not work and is being ignored. The resulting image is always at max GAIN (same as 8bit and GAIN set 400).

Raspbian Buster
4.19.75-v7l+
INDI Library: 1.8.2
Code v1.8.2-1-g29b0ba05. Protocol 1.7.

Indi installtion as in:
https://www.indilib.org/download/raspberry-pi.html

Client application is Kstars 3.3.8

 8 bit gain 400 ( a lot of noise as expected)
<img width="2560" alt="Bildschirmfoto 2019-12-14 um 23 46 18 (2)" src="https://user-images.githubusercontent.com/58893225/70855505-143e2480-1ecc-11ea-8694-80da12585551.png">

8 bit gain 0 (no noise as expected)
<img width="2560" alt="Bildschirmfoto 2019-12-14 um 23 46 04 (2)" src="https://user-images.githubusercontent.com/58893225/70855517-42236900-1ecc-11ea-9864-7893832022ab.png">

16 bit gain 0 (noise as gain 400)
<img width="2560" alt="Bildschirmfoto 2019-12-14 um 23 45 40 (2)" src="https://user-images.githubusercontent.com/58893225/70855523-6aab6300-1ecc-11ea-9651-2a7cab43490c.png">

16 bit gain 400 (same as gain 0, so no effect, gain always at max)
<img width="2560" alt="Bildschirmfoto 2019-12-14 um 23 45 17 (2)" src="https://user-images.githubusercontent.com/58893225/70855531-87e03180-1ecc-11ea-9fed-00d7a7ede40e.png">

**Comment by knro** [comment]
How about when you set it to say, 50 in Ekos? Does it change as well when you capture in INDI control panel?

**Comment by fiveseve84** [comment]
Sorry forgot to mention. I tried that already. 50 120 240 all look like Max gain. And it does not make any difference changing the value in Indi panel or in cam settings.

Also tried a lot different settings to see if behaviour changes. Auto gain on off, Max auto gain exposure etc . But still always at Max gain.

**Comment by knro** [comment]
Have you tested with ASICAP? same results or it works there?

**Comment by fiveseve84** [comment]
Not asicap specifically. But imaging with the setup since nearly two years. Was using sharpcap with Windows before. (on an Intel nice mounted to the telescope) There everything works fine. 

When I saw I can ommit windows rdp and use a less power hungry Rpi. I was searching for exactly your solution but never found something. Then I saw an Indi/Kstars video on YouTube and was immediately sold.

But let me try sharpcap again. Maybe there is an  issue with the I am not aware of, since I didn't use it  since last winter

**Comment by fiveseve84** [comment]
Okay somehow very interesting. Sharpcap works as expected. 
In addition installed Ubuntu 
Description:	Ubuntu 18.04.3 LTS
4.15.0-72-generic
On another Intel NUC @ CPU J3455
As described:
https://indilib.org/download/ubuntu.html
apt-get install indi-full gsc

And again it works as expected. 

So the issue hast smething to do with either the PI4, OS or a difference between packages RPI4/X86_64

One another thing I can see, the grain or image output grain behavior looks completeley different between RPI and NUC

Intel NUC:
<img width="502" alt="Bildschirmfoto 2019-12-15 um 11 00 55" src="https://user-images.githubusercontent.com/58893225/70861133-41212480-1f2a-11ea-929b-2934a1fa4d69.png">

RPI4
<img width="502" alt="Bildschirmfoto 2019-12-15 um 11 01 12" src="https://user-images.githubusercontent.com/58893225/70861140-47af9c00-1f2a-11ea-8584-7b5b76e96355.png">

**Comment by fiveseve84** [comment]
Maybe an additional note: if exposure settings are orrect, I can see a picture with the RPI4. So the image or readout is not broken. Only GAIN/grain behaviour very strange

**Comment by knro** [comment]
If you saved the FITS image from RPI4 and opened it on another PC or NUC, does it show the same pattern?

**Comment by fiveseve84** [comment]
Found the issue. Sorry for the buzz. Apparently Kstars has an independent Ekos settings where it auto stetches all images.  But this is only applied to 16bit images and althoug while capturing I deaktivated Stretchin, Contrast etc.

Sorry. Issue can be closed
