### ISSUE TITLE
Illegal characters in profile name with indi web

### ISSUE THREAD

**Issue by ennui2342** [indilib/indi#1073]
I created some profile names in Ekos which included a /

When using indi web manager this causes it to fail to start the profile. Removing the / solved the problem, but it would be good to have some validation checking ekos side to inform the user as it was a bit difficult to diagnose.

**Comment by knro** [comment]
Yes I can understand this is difficult to diagnose. Perhaps INDI Web Manager should handle them properly instead. Should be filed here: https://github.com/knro/indiwebmanager
