### ISSUE TITLE
No bit depth switching using indi_toupcam_ccd

### ISSUE THREAD

**Issue by raul-chirea** [indilib/indi#1078]
**Describe the bug**
indi_toupcam_ccd driver does not offer the possibility to switch between bit depths, although the hardware of the camera supports it. For example, I have a Touptek GP2000KPA camera. Its specification says that camera supports bit depths of 8bit and 12bit but, with the current driver, it can not be used in 12bit mode (only 8bit mode).

**To Reproduce**
Exact steps to reproduce the behavior.
1. Run driver
2. In the "Controls" tab of the driver control there is no way to switch from 8bit mode to 12bit mode as described in documentation (https://www.indilib.org/devices/cameras/toupcam-cameras.html - "Capture" section).

**Expected behavior**
indi_toupcam_ccd should be able to use 12bit mode of the camera.

**Screenshots**
![ToupCamBitDepthProblem](https://user-images.githubusercontent.com/26461353/73124502-c45f7c80-3fa4-11ea-8099-237afb6c153c.png)

**Desktop (please complete the following information):**
 - OS: Linux (Fedora 28) + driver running on RPi 2
 - INDI Version: 1.8.2

**Comment by knro** [comment]
RGB is 8bit. Try RAW and see what can you get.

**Comment by raul-chirea** [comment]
Wow. Magic. Changing from RGB to RAW switches camera to 12bit. A little bit unintuitive, but it works. Thanks !

**Comment by raul-chirea** [comment]
Somebody tell me, please, should I close the bug or let it open (maybe the docs should be modified to be more explicit) ? I don't know the customs around here.

**Comment by knro** [comment]
Yes, I updated the driver documentation to help users know about this.

**Comment by raul-chirea** [comment]
Excelent ! Thanks a lot, again. BTW, great job with EKOS.
