### ISSUE TITLE
Canon 60Da Capture issue

### ISSUE THREAD

**Issue by PMoff** [indilib/indi#1083]
New setup, test phase.
When I have my DSLR camera setup and connected, I like to take a single frame test photo. I have been noticing, that it reports that the capture has failed, and is restarting, which then succeeds. If I have the count set to more than 1, say 2 or 3, I only get 1 image. If framing is used, the first photo fails capture, then rest proceed until stopped.
Odroid H2, 16Gb RAM, 120Gb SSD, Ubuntu 18.04, KStars V3.3.9 latest drivers downloaded 2 days ago.
Just noticed that captured images have 'tearing' at the top of the frame, diagonally greatest at left, vanishing to the right
I strongly suspect now, that the conversion to FITS may be the culprit in the image defects, however that does not address the capture failure on EVERY image, and succeed on the retry. I am abandoning this project now, as the software is too 'buggy'. Windows with APT seems better at this time.

**Comment by knro** [comment]
Please file this in INDI [3rd party](https://github.com/indilib/indi-3rdparty) repository.
