### ISSUE TITLE
Fli cfw-2-8 FilterWheel

### ISSUE THREAD

**Issue by porkyhttp** [indilib/indi#1084]
I was unable to connect to my Fli cfw-2-8 wheel. The system, Raspbian is updated and it see the hardware that is listed in the usb devices list, but Ekos through the INDI Panel was unable to connect to the wheel usini any method (USB, Serial, ...).
Where is the problem???????

**Comment by knro** [comment]
IIRC, this filter wheel is no longer supported by FLI in their SDK.
