### ISSUE TITLE
indi-aagcloudwatcher-ng package missing/broken from linux mint repositories

### ISSUE THREAD

**Issue by myxlflik** [indilib/indi#1093]
I am unable to update the indi-full package because the indi-aagcloudwatcher-ng package is missing/broken in the Linux Mint install repositories.  
![Screen Shot 2020-02-11 at 6 22 49 PM copy](https://user-images.githubusercontent.com/41927919/74288954-cd1db580-4cfb-11ea-87bb-3b48bd29f66c.jpg)

**Comment by knro** [comment]
is this 16.04? I just found that it didn't build on 16.04 , so now triggering a build.

**Comment by myxlflik** [comment]
Yes.  I believe the Linux Mint distros I have installed are based on Ubuntu 16.04 LTS.  I just tried and it was able to install the package.  Thanks for fixing this.
