### ISSUE TITLE
Stellarmate v1.5.0 on Raspbian OS 64-bit is extremely slow to the point of jumpy when connecting USB 3.0 device on USB 3.0 port

### ISSUE THREAD

**Issue by gmboytell** [indilib/indi#1094]
**Describe the bug**
Stellarmate v1.5.0 on Raspbian OS 64-bit is extremely slow to the point of jumpy when connecting USB 3.0 device on USB 3.0 port.

**To Reproduce**
Exact steps to reproduce the behavior.
1. Install current Raspbian OS - Stellarmate v1.5.0 from provided image and write to SD card;
2. Boot with new SD Card created in step 1 above; and
3. Connect a USB3.0 device to a USB3.0 port on the Raspberry Pi 4B.

**Expected behavior**
Try operating mouse, keyboard or any other software and watch devices and applications stutter.
NOTE: when disconnecting the USB3.0 device from USB3.0 port of Raspberry Pi 4B all returns to normal with no stutter.

**Screenshots**
Not applicable.

**Desktop (please complete the following information):**
 - Based on Raspbian OS 64-bit for ARM based Raspberry Pi 4B; and
 - Stellarmate v1.5.0

**Log Files**
NOTE: this is a similar issue found on other versions of Linux on hardware with USB3.0 ports - Ubuntu 18.04LTS, there is a known patch for Ubuntu, not sure if there is for Raspbian.

**Comment by knro** [comment]
Thank you for the report. This is not an INDI issue. Please send the report to support@stellarmate.com
