### ISSUE TITLE
Clamping on moonlite focuser results in inward focusing to 0 all the time `indi_moonlite_focus`

### ISSUE THREAD

**Issue by rickbassham** [indilib/indi#1099]
**Describe the bug**
Clamping code is not doing signed integer math, causing wrapping issues when focusing inward.

**To Reproduce**
Exact steps to reproduce the behavior.
1. Run driver
2. Move focuser to a position of 2000.
3. Relative move focuser INWARD by 1000.
3. Focuser actually moves to 0.

**Expected behavior**
Expected the focuser to move to 1000.

See PR https://github.com/indilib/indi/pull/1098 for proposed fix and further description.

**Comment by Chris-Rowland** [comment]
The patch suggested in PR #1098 seems to have been implemented.  Close this?

**Comment by knro** [comment]
Correct. Will close it!
