### ISSUE TITLE
tutorial_four  Set environment variable INDISKEL to the skeleton path and try again

### ISSUE THREAD

**Issue by VTVL** [indilib/indi#110]
Trying to run tutorial_four:  After someone else tried this, there is suspicion that it is a bug.

Driver ./tutorial_four: No skeleton file was specified. Set environment variable INDISKEL to the skeleton path and try again.

Using QT Creator to edit simpleskeleton.ccp to change the path to tutourial_four_sk.xmlOptions
but there is a bug:   
"/home/xxxx/Projects/indi/libindi/examples/tutorial_four/simpleskeleton.h:34: error: indidevapi.h: No such file or directory"
How or where do I set the path to /home/xxxx/Projects/indi/libindi  where indidevapi.h is located ?
OR is this a bug?

**Comment by knro** [comment]
It's not a bug, but the documentation for the tutorials wasn't complete. Please check the [updated](https://github.com/indilib/indi/tree/master/libindi/examples) documentation about how to export the INDISKEL variable before you run the tutorial.
