### ISSUE TITLE
Get the code instruction is wrong

### ISSUE THREAD

**Issue by phomer60** [indilib/indi#1101]
The instructions show the following, which produces the error following. The 'hub' needs to be removed.
git clone https://github.com/indilib/indi.github
Cloning into 'indi.github'...
Username for 'https://github.com': phomer60
Password for 'https://phomer60@github.com': 
remote: Repository not found.
fatal: repository 'https://github.com/indilib/indi.github/' not found

**Comment by TallFurryMan** [comment]
Jasem did beat me to it 😉
