### ISSUE TITLE
Some settings of the AstroPhysics Experimental driver are unreadable or unsettable

### ISSUE THREAD

**Issue by jmichelet** [indilib/indi#1130]
Description : 
Some settings of the AstroPhysics Experimental driver are unreadable, and may be un-settable.
This bug appeared about a month ago, I just waited to file a report, thinking it would vanish some time. But no luck.
That said, the driver actually works, so this is not a critical bug. 
Note that the panels of the other devices (3 cameras, 1 focuser, 1 GPS) do not show this defect. 

Reproduction :
This requires having an AstroPhysics mount that support the experimental driver.
Using Ekos, create a profile that includes an AstroPhysics Experimental mount, and activate it, so that Ekos connect to the mount. The Indi drivers screen appears, then check the mount tab.
You should see something like the attached screenshots.

Desktop :
 - OS: Linux Ubuntu LTS 18-04
 - Version : all the indilib is pulled from git (latest pull was on the April 25), and compiled.

![ecran_apexp_1](https://user-images.githubusercontent.com/3582166/80465527-85dab480-893b-11ea-9bf3-b6cd18cbd843.png)

![ecran_apexp_2](https://user-images.githubusercontent.com/3582166/80465551-8bd09580-893b-11ea-8c18-9a091806dd12.png)

**Comment by knro** [comment]
This is not an issue with the driver. It was a bug in KStars and is resolved with KStars 3.4.2, please update.
