### ISSUE TITLE
INDI driver for Brightstar Mammut Lyuba camera

### ISSUE THREAD

**Issue by Manu4810** [indilib/indi#1132]
I own an old Brightstar Mammut Lyuba camera which works fine on Windows with both native and ASCOM drivers (that are no more maintained since the company closed business). I would like to move my entire set-up to a full linux environement, with RaspberryPI / Astroberry, but unfortunately the camera is not recognized by the existing set of INDI drivers embedded in Astroberry (I tried MEADE DSI, Orion SSAG, Starshoot, all to no avail) and therefore cannot be used as main or guide camera. This camera ressembles the ORION Starshoot G3 very much, but does not have the same firmware / chipset apparently (I cannot control it with Orion SSG3 ASCOM driver on Windows either). It seems to be based on some AVR32 AMTEL chipset from microchips (so it says from dmesg after plugging it into the USB port). Any advice on the relevant INDI driver to be used or any trick involving ASCOM Alpaca would be very much welcome. Thanks

**Comment by knro** [comment]
A new driver would need to be developed for this camera. Unless you have the skills or know someone who has the skill to develop a driver, it would be extremely challenging.

At any rate, please file this in INDI [3rd party](https://github.com/indilib/indi-3rdparty) repository.
