### ISSUE TITLE
atik16hr support

### ISSUE THREAD

**Issue by caggelis** [indilib/indi#1134]
it will be useful to make older atik cameras work with indi.

**Comment by TallFurryMan** [comment]
It all depends on Atik agreeing with this. Now Atik provides "legacy code" for 16-series, so picking an old version of `indi_atik_ccd`and rebuilding may be possible.

**Comment by knro** [comment]
Please file this in INDI [3rd Party](https://github.com/indilib/indi-3rdparty) repo.
