### ISSUE TITLE
DSLR camera Nikon d3100 very slow responce

### ISSUE THREAD

**Issue by caggelis** [indilib/indi#1135]
some times, after capturing the picture comes, but with very big delay (about 1.5 -2 minutes) but the most times picture doesn't comes, giving "Exposure timeout. Restarting exposure..." 

Raspberry pi 3 mod b. 
DSLR NIKON D3100

**Comment by knro** [comment]
Please file this in INDI [3rd party](https://github.com/indilib/indi-3rdparty) repository.
