### ISSUE TITLE
Missing symbol in libindiclient.a

### ISSUE THREAD

**Issue by gnthibault** [indilib/indi#1139]
Sorry for the bad problem, description, I don't know much about the history of pyindi client, apart from the fact that I use it a lot, and it makes the full potential of indi available for python developers, with its rich ecosystem (astropy in particular).

Anyway, the original problem is defined here:
https://indilib.org/forum/development/6913-pyindi-client-fails-at-runtime-because-of-missing-symbol.html#53246

Looks like this problem was not there in 1.8.4, but started to appea from 1.8.5, 1.8.6

Main highlight:
The original problem:

> Recently found myself with the following problem while trying to import and use pyindi-client on a new machine:
> Traceback (most recent call last):
> File "/usr/lib/python3.8/site-packages/PyIndi.py", line 18, in swig_import_helper
> return importlib.import_module(mname)
> File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
> return _bootstrap._gcd_import(name[level:], package, level)
> File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
> File "<frozen importlib._bootstrap>", line 991, in _find_and_load
> File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
> File "<frozen importlib._bootstrap>", line 657, in _load_unlocked
> File "<frozen importlib._bootstrap>", line 556, in module_from_spec
> File "<frozen importlib._bootstrap_external>", line 1101, in create_module
> File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
> ImportError: /usr/lib/python3.8/site-packages/_PyIndi.cpython-38-arm-linux-gnueabihf.so: undefined symbol: _ZN4INDI8Property7getTextEv

>  I tried to look for the missing symbol in the static library:

> nm /usr/lib/libindiclient.a | grep getText
> 000004ec T _ZN4INDI10BaseDevice7getTextEPKc
> U _ZN4INDI10BaseDevice7getTextEPKc
> 00000504 T _ZNK4INDI8Property7getTextEv
> 
> Or in demangled format:
> nm -C /usr/lib/libindiclient.a | grep getText
> 000004ec T INDI::BaseDevice::getText(char const*)
> U INDI::BaseDevice::getText(char const*)
> 00000504 T INDI::Property::getText() const
> 
> The symbols in the pyindi swig binary are:
> nm -D /usr/lib/python3.8/site-packages/pyindi_client-0.2.2-py3.8-linux-aarch64.egg/_PyIndi.cpython-38-arm-linux-gnueabihf.so | grep getText
> 00030d04 T _ZN4INDI10BaseDevice7getTextEPKc
> U _ZN4INDI8Property7getTextEv
> 00036884 T _ZNK4INDI8Property7getTextEv
> 
> Or in demangled format:
> nm -CD /usr/lib/python3.8/site-packages/pyindi_client-0.2.2-py3.8-linux-aarch64.egg/_PyIndi.cpython-38-arm-linux-gnueabihf.so | grep getText
> 00030d04 T INDI::BaseDevice::getText(char const*)
> U INDI::Property::getText()
> 00036884 T INDI::Property::getText() const
> 
> EDIT: in an other build I have this
> nm -CD ~/anaconda3/lib/python3.6/site-packages/pyindi_client-0.2.2-py3.6-linux-x86_64.egg/_PyIndi.cpython-36m-x86_64-linux-gnu.so | grep getText
> 000000000005206e T INDI::BaseDevice::getText(char const*)
> 0000000000058fb0 T INDI::Property::getText()
> 
> 
> Looks like the problem is in between the non const missing symbol
> U INDI::Property::getText()
> In the python binary, because only const version is defined in the static libindiclient.a
> 00000504 T INDI::Property::getText() const

**Comment by gnthibault** [comment]
Sorry, just realized there is probably something I missed about dynamic method name resolution.

**Comment by gnthibault** [comment]
Ok I tracked down the problem to this line:
https://github.com/indilib/indi/blame/62f2d19d489f45b7a0f84e664529e38421f5d4dd/libs/indibase/indiproperty.cpp#L272

and there:
https://github.com/indilib/indi/blame/62f2d19d489f45b7a0f84e664529e38421f5d4dd/libs/indibase/indiproperty.h#L76

A const was added
@knro  there is actually nothing wrong of course with main indi repository. but somehow, we need to make a change to pyindi-client, and I am not sure how to do that.

**Comment by gnthibault** [comment]
I am trying to change
    result = (ITextVectorProperty *)(arg1)->getText();
to
    result = (const ITextVectorProperty *)(arg1)->getText();

in indiclientpython_wrap.cpp

**Comment by gnthibault** [comment]
I cannot reproduce the problem on my other computer x86_64, although depending on the source (download tar from pypi or automatic pip build), I get either the const or non const version.
Maybe the problem is linked to the operating system/ABI ? that is not able to recognize both symbol as being one, this is outside of my expertise.

**Comment by knro** [comment]
I just updated INDI::Property to be const-correct for all the constant functions. Can you purge any INDI libraries on your system and compile/install from latest GIT?

**Comment by gnthibault** [comment]
Just rebuilt indi from
commit 1af2cbf3813854ffa2706e2ced43b72b023769cc
    Make rest of constant functions const

Nothing changed, 

Old libindiclient.a:
000004ec T INDI::BaseDevice::getText(char const*)
         U INDI::BaseDevice::getText(char const*)
00000504 T INDI::Property::getText() const

New libindiclient.a 
000004ec T INDI::BaseDevice::getText(char const*)
         U INDI::BaseDevice::getText(char const*)
00000504 T INDI::Property::getText() const

The swig shared object built by pyindi-client that I just rebuilt:
./build/lib.linux-aarch64-3.8/_PyIndi.cpython-38-arm-linux-gnueabihf.so | grep getText
000310e4 T INDI::BaseDevice::getText(char const*)
                  U INDI::Property::getText()
00036c64 T INDI::Property::getText() const

To me, it looks like the problem comes from the pyindi-client code. But Somehow I cannot reproduce the error on my x86_64 machine that also features different version of gcc, different OS, ..

**Comment by gnthibault** [comment]
WAIT, I might have forgotten some sources in /usr/ instead of /usr/local

**Comment by gnthibault** [comment]
That was it of course... Very sorry for any inconvenience. Thank you again for your support.
