### ISSUE TITLE
Cannot install KStars with dnf (repodata/repomd.xml error)

### ISSUE THREAD

**Issue by talderw** [indilib/indi#1166]
Cannot install KStars in Fedora 32. Could install the repo manually, could install indi-bleeding and drivers, but then got stuck on installation of KStars. 
This repodata/repomd.xml seems to be a reported bugzilla bug also. Don't know how to get around it. I have the same problem on other PC's with Fedora 32. See typical system response below. 

Does anyone have a solution or workaround for this (known) issue?

Tom. 
 
[Tom@localhost ~]$ sudo dnf install kstars-bleeding
[sudo] password for Tom: 
INDI and KStars for Fedora - Bleeding Edge      6.7 kB/s | 1.1 kB     00:00    
Errors during downloading metadata for repository 'lupinix-indi-bleeding':
  - Status code: 404 for http://download.opensuse.org/repositories/home:/lupinix-indi:/fedora-bleeding/Fedora_32/repodata/repomd.xml (IP: 2620:113:80c0:8::13)
Error: Failed to download metadata for repo 'lupinix-indi-bleeding': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried

**Comment by knro** [comment]
Thank you for the report. I informed the repo maintainer, but this is not really an INDI issue. You can also try to contact the repo container about this issue.
