### ISSUE TITLE
EKOS - Auto Focus routine - random large jump in step position

### ISSUE THREAD

**Issue by jamiecflinn** [indilib/indi#1171]
**Describe the bug**
two recent runs of scheduler using multiple filters - each filter goes through autofocus rountine and twice in two session I have seen an unusually large number used as the focus steps to move to in repsonse to HRF value - screen shot attached - log attached - the regular "area of good fouces ranges between 3400 and 4500.    This jump sees a single move of over 2000 steps injected to teh focuser from EKOS as the "go to position" number - it is RANDOM in appearance

Using Moonlight focuser (Myfocuserpro2 arduino)

Thi sissue is recent - the same unit has operated without issue for close 8 months

**To Reproduce**
Exact steps to reproduce the behavior.
1. schedule multiple filters in a single run
2. before scheduler kicks in, pre-focus on whereever you are pointed and confirm the normal position numbers
2. monitor focus routine onse scheduler starts the process and moves to each filter
3. See error in the left hand position window - this is where the positoin injected to the focuser appears during the routine  - not the manal right hand box

**Expected behavior**
The injected number should be within the noral range of in/out positions as the process works out the delta between each attempt

**Screenshots**
![image](https://user-images.githubusercontent.com/57917381/84537047-091e5280-acbd-11ea-8017-2db2aed6075b.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version 1.8.0.4
All the latest KTARS/EKOS/INDI
Log is marked - look for BUG and the sudden jump from the 3xxx to 1xxx and I think there is even one as low as 800....the routine cannot escape this as the jumps in focus are too large and the stars are not resolvable at this point
[focus bug.txt](https://github.com/indilib/indi/files/4772718/focus.bug.txt)

**Log Files**
Make sure to enable logging and include log files https://indilib.org/support/logs-submission.html

**Comment by knro** [comment]
Thank you for the report. This is not an INDI issue, it's a KStars issue. So you can refile the bug either here: https://invent.kde.org/education/kstars/-/issues or at bugs.kde.org

Also, the log file does not contain Ekos Focus logging. You need to turn off INDI logging (lots of unnecessary data) and just turn on Ekos focus logging.
