### ISSUE TITLE
astroberry-server-wui fails at enable nginx

### ISSUE THREAD

**Issue by AradoSKY** [indilib/indi#1180]
astroberry@astroberry:~ $ sudo dpkg --configure -a
[sudo] password for astroberry: 
Setting up astroberry-server-wui (2.0.7) ...
Synchronizing state of nginx.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable nginx
insserv: script klogd: service klogd already provided!
insserv: script klogd: service klogd already provided!
^Cdpkg: error processing package astroberry-server-wui (--configure):
 installed astroberry-server-wui package post-installation script subprocess was interrupted
Errors were encountered while processing:
astroberry-server-wui

This update crashed. I used dpkg to recover. I am at the same crash place. NGINX never shuts down. Syslog shows
Overwriting existing symlink /run/systemd/generator.late/klogd.service with real service.  

This occurs every time this script is run. I have 9 attempts after cleaning up .service errors. Nothing seems to point to why this is happening. NGINX. SAMBA, and GPSD were all erroring out in SYSLOG after this string of patches.

**Comment by bluthen** [comment]
Maybe it should be filed on the astroberry github issue tracker?
https://github.com/rkaczorek/astroberry-server-wui
https://github.com/rkaczorek/astroberry-server
