### ISSUE TITLE
Let AZ-GTI driver render the mount's SNAP port available to the Gphoto driver to take >30sec pics with older DSRLs 

### ISSUE THREAD

**Issue by federicoparra** [indilib/indi#1181]
When using a DSLR that requires a separate shutter-trigger cable for >30sec pictures in Gphoto, and simultaneously using AZ-GTI mount, gPhoto should "see" the AZ-GTI's SNAP port. NIKON and CANON produce off-the-shelf, very cheap SNAP compatible cables (the AZ-GTI actually comes with a free SNAP cable that works with some DSLR directly). The Synscan app allows to use the SNAP port to trigger pictures of any desired exposure duration with camera in bulb mode; this proves the port is reachable by software and should be reachable through UDP just like all other functions of the mount.

**Comment by geehalel** [comment]
Hi,
Are you using the AZ-GTI driver based on indi-eqmod ?
If this is the case, I would need the mount code to manually add it in the driver as the number of snap ports is not available from the firmware. If you enable debug Serial comm before connecting the mount in the control panel, then just connect and disconnect, the log file will contain the desired code.  I believe I will make this code visible in the firmware tab in next release.

**Comment by federicoparra** [comment]
Perfect, I'll do this as soon as I get the chance, hopefully this weekend. thank you!

**Comment by federicoparra** [comment]
> Hi,
> Are you using the AZ-GTI driver based on indi-eqmod ?
> If this is the case, I would need the mount code to manually add it in the driver as the number of snap ports is not available from the firmware. If you enable debug Serial comm before connecting the mount in the control panel, then just connect and disconnect, the log file will contain the desired code. I believe I will make this code visible in the firmware tab in next release.

Hi! I tried today but couldn't find the option "enable debug serial comm" anywhere. Could you guide me a little bit to find it? Thank you! Federico

**Comment by geehalel** [comment]
Hi,
Before connecting the mount in the control panel,  go to the "Options" tab and "Enable" "Debug".
You should see other options appearing at the bottom of the tab, check 'Serial Port' in the "Logging Levels" property and
"To Log File" in the "Log Output" property. When you check this one, you should see an info message stating where is the log file:
```
2020-07-13T18:47:40: [INFO] Session log file /home/xxx/.indi/logs/2020-07-13/indi_eqmod_telescope/indi_eqmod_telescope_18:35:36.log 
```
Then just connect the mount in the "Main control" tab, and when it's done (2 seconds) disconnect the mount.
Attach the log file here, or get the line at the beginning of the file containing the first sent command:
```
COMM	119.124737 sec	: dispatch_command: ":e1", 4 bytes written
COMM	119.124784 sec	: read_eqmod: "=020300", 8 bytes read
```
Thanks.

**Comment by federicoparra** [comment]
Strangely, both using INDI control panel on the Raspberry directly or on Windows connected to the Raspberry server, when I click on Enable debug for this specific driver it very quickly turns off again; this is my trying repeatedly to enable it:
2020-07-15T13:09:38: [INFO] Debug is disabled. 
2020-07-15T13:09:38: [INFO] Debug is enabled. 
2020-07-15T13:09:37: [INFO] Debug is disabled. 
2020-07-15T13:09:37: [INFO] Debug is enabled. 
2020-07-15T13:09:36: [INFO] Debug is disabled. 
2020-07-15T13:09:36: [INFO] Debug is enabled. 
2020-07-15T13:09:35: [INFO] Debug is disabled. 
2020-07-15T13:09:35: [INFO] Debug is enabled. 
2020-07-15T13:09:34: [INFO] Debug is disabled. 
2020-07-15T13:09:34: [INFO] Debug is enabled. 
2020-07-15T13:09:32: [INFO] Debug is disabled. 
2020-07-15T13:09:32: [INFO] Debug is enabled. 

Any ideas?

**Comment by federicoparra** [comment]
> Hi,
> Before connecting the mount in the control panel, go to the "Options" tab and "Enable" "Debug".
> You should see other options appearing at the bottom of the tab, check 'Serial Port' in the "Logging Levels" property and
> "To Log File" in the "Log Output" property. When you check this one, you should see an info message stating where is the log file:
> 
> ```
> 2020-07-13T18:47:40: [INFO] Session log file /home/xxx/.indi/logs/2020-07-13/indi_eqmod_telescope/indi_eqmod_telescope_18:35:36.log 
> ```
> 
> Then just connect the mount in the "Main control" tab, and when it's done (2 seconds) disconnect the mount.
> Attach the log file here, or get the line at the beginning of the file containing the first sent command:
> 
> ```
> COMM	119.124737 sec	: dispatch_command: ":e1", 4 bytes written
> COMM	119.124784 sec	: read_eqmod: "=020300", 8 bytes read
> ```
> 
> Thanks.

Strangely, both using INDI control panel on the Raspberry directly or on Windows connected to the Raspberry server, when I click on Enable debug for this specific driver it very quickly turns off again; this is my trying repeatedly to enable it:
2020-07-15T13:09:38: [INFO] Debug is disabled.
2020-07-15T13:09:38: [INFO] Debug is enabled.
2020-07-15T13:09:37: [INFO] Debug is disabled.
2020-07-15T13:09:37: [INFO] Debug is enabled.
2020-07-15T13:09:36: [INFO] Debug is disabled.
2020-07-15T13:09:36: [INFO] Debug is enabled.
2020-07-15T13:09:35: [INFO] Debug is disabled.
2020-07-15T13:09:35: [INFO] Debug is enabled.
2020-07-15T13:09:34: [INFO] Debug is disabled.
2020-07-15T13:09:34: [INFO] Debug is enabled.
2020-07-15T13:09:32: [INFO] Debug is disabled.
2020-07-15T13:09:32: [INFO] Debug is enabled.

Any ideas?

**Comment by gubihu** [comment]
You also have to enable debug in Kstars settings, otherwise it is EKOS that turns debug off. I had troubles with that too when I tried to submit my first log.

**Comment by federicoparra** [comment]
[log_18-41-35.txt](https://github.com/indilib/indi/files/4961335/log_18-41-35.txt)
Hope it has what you need!

**Comment by geehalel** [comment]
Thanks @gubihu, I did not think that Ekos may turn debugging off automatically.
@federicoparra yeah that's it, mount code is A5.
I currently have some failures with my development computer, so won't be able to make changes to my repo before some days.
Would you be able to compile and test the modified driver before I make a pull request ?

**Comment by federicoparra** [comment]
> Would you be able to compile and test the modified driver before I make a pull request ?

You mean once you do the changes? Yes, I can try it myself.

**Comment by geehalel** [comment]
Ok, I did the changes in my repo in the [azgti-snap branch](https://github.com/geehalel/indi-3rdparty/tree/azgti-snap).
I tested with the latest indi-core github version, there may be some errors in kstars when disconnecting (dispatch command errors),
it seems drivers do not need to delete properties anymore.

**Comment by federicoparra** [comment]
> Ok, I did the changes in my repo in the [azgti-snap branch](https://github.com/geehalel/indi-3rdparty/tree/azgti-snap).
> I tested with the latest indi-core github version, there may be some errors in kstars when disconnecting (dispatch command errors),
> it seems drivers do not need to delete properties anymore.

Hi! I have some time in my hands (on vacations) and have my AZ-GTI :) so how do I test this? I have the SNAP cable with me as well :)

**Comment by geehalel** [comment]
You would have to compile the indi-eqmod driver of my repo branch, it should work with the latest indi core (I just tested, still dispatch command errors on disconnection). There will be a "Snap Port 1" switch in the Options tab when you run the `indi_azgti_telescope` driver and connect your mount. If you plug the SNAP cable to your DSLR, you will be able to toggle bulb exposure using this switch.

**Comment by knro** [comment]
@geehalel is this ready to be merged with master at this stage? Thanks!!

**Comment by geehalel** [comment]
I'm still waiting someone to test on a **real** AZGti mount, I just tested with the simulator using the A5 mount code, I can not be sure that it toggles whatever on a real mount...

**Comment by federicoparra** [comment]
@geehalel @knro I'm a newby with Linux, only using it with Stellarmate, but I do have the AZ-GTI, if any of you let me know the steps I'll try it asap. Thank you so much for your work!

**Comment by geehalel** [comment]
Ok I will do a pull request after syncing the branch to the latest commit, so you may be able to test in your stellarmate setup when it will be updated (I don't know when this will happen however). The main problem I can see is that the snap port on the AZGTi is not tied to the first output but to the second one. In order to test, connect your DSLR in Manual/Bulb mode to the snap port and try starting an exposure by pressing the Connect button in the Snap port control of the EQMod Indi panel. And Disconnect to stop the exposure.

**Comment by geehalel** [comment]
Pull request just done. Wait until it comes to your stellarmate (you should see your mount name AZGTi now in the firmware tab, and the snap port control button in the Options tab).
Please confirm that works as expected.
Thanks.

**Comment by federicoparra** [comment]
> Pull request just done. Wait until it comes to your stellarmate (you should see your mount name AZGTi now in the firmware tab, and the snap port control button in the Options tab).
> Please confirm that works as expected.
> Thanks.

Perfect, I'll try asap

**Comment by federicoparra** [comment]
@geehalel @knro I updated Stellarmate stable channel but within the EQMod and/or the AZGTI drivers' indi panel there is no Snap port control option. I imagine this is because the latest stable update still does not contain your modification? I'm downloading now the Beta channel's last version to see if the option appears.

**Comment by federicoparra** [comment]
Addendum: just tried the beta channel's last update and same thing: no Snap port control option appears.

**Comment by geehalel** [comment]
The pull request is still pending, it is in the [indi/indi-3rdparty](https://github.com/indilib/indi-3rdparty/pulls) repository named AZGTi Snap. You have to wait Jasem or some repo admin merges it into the master branch. Then it will have to be included in the Stellarmate updates. And then you will be able to see the Snap option...

**Comment by federicoparra** [comment]
@knro could you accept his pull request so that it's included in Stellarmate updates?

**Comment by federicoparra** [comment]
@knro  any news?

**Comment by killercode** [comment]
Hi, are we sure that this was merged?

**Comment by killercode** [comment]
Because I am using StellarMate 1.7.0 and there is no change in there :(
