### ISSUE TITLE
How to make this focuser work with INDI

### ISSUE THREAD

**Issue by oldmar** [indilib/indi#1186]
Hi, I am an old pensioner who has rediscovered the astronomy dreamed of as a child and a new user with very limited knowledge of the programming language.
I own a telescope with a focuser to which I have applied an automatism taken from a project found on the net, it works very well but unfortunately it only works with the ASCOM protocol.
My mount has weight limits caused by a heavy mini PC used to control everything, I would like to use the Raspberry Pi 4, I read it works well with the INDI - Kstars - Ekos protocol.
My problem I don't know how to make it work with INDI, I hope there is someone who can make it work and write a driver for INDI
The components I have are:
- Arduino mega 2560
- Arduino Motor Shield
- TRINAMIC QSH4218-51-10-049 STEPPER MOTOR, 1.8DEG, 1A, 0.49NM
- Adafruit MCP9808 temperature control
Thank you

**Comment by knro** [comment]
Please use "New Driver" template.
