### ISSUE TITLE
Pegasus UPBV2 driver focuser temperature tab using a non-existent sensor 

### ISSUE THREAD

**Issue by xthestreams** [indilib/indi#1213]
**Describe the bug**
The Ultimate Power Box V2 has both a focuser and an environment sensor capability included.

The focuser driver tab features a temperature section (see screenshot), which is registering 0 degrees. In checking the pinout of the focuser hardware, there are no temperature sensor signal lines - all environmental data comes from the environmental sensor.

I believe the driver should be reading this value from the environmental sensor instead. 

**To Reproduce**
Buy a UPVv2 :-)
Install driver
Scratch head

**Expected behavior**
It should be reading the temperature from the environmental sensor.

**Screenshots**
Attached

**Desktop (please complete the following information):**
 - OS: Stellarmate
 - Version 1.5.3

**Log Files**
N/A
![Screen Shot 2020-08-21 at 11 32 17 am](https://user-images.githubusercontent.com/2031023/90842522-d9698600-e3a2-11ea-95bb-801314b576c5.png)

**Comment by knro** [comment]
It is ready the temperature from the SDK provided by Pegasus. Not sure what you mean by environmental sensors? where?

**Comment by xthestreams** [comment]
Okay - so there is to my knowledge only one temperature sensor on the UPBV2 and that is the Temp, Humidity, Pressure sensor - the is the source for the temperature on teh environment tab. I can't find any reference to, or even a source of, focuser temperature in teh API docs.

**Comment by xthestreams** [comment]
perhaps @rishi-garrod has an idea here too!? :-)
