### ISSUE TITLE
Nexdome driver does not open shutter on Unpark

### ISSUE THREAD

**Issue by xthestreams** [indilib/indi#1214]
**Is your feature request related to a problem? Please describe.**
The updated Nexdome driver 9for V3+ firmware) is now slaving great, thanks Jassem! 

It has a feature to enable automatic close on Park but the same feature does not appear to be there for Unpark.

As a result when EKOS Scheduler automates an imaging run it does NOT open the shutter without additional scripting and therefor no images are captured unless an attended session is run. 

**Describe the solution you'd like**
In my opinion an "unpark" should really an Open event (eg: if this was a Roll-on/Roll-off, it's essentially a big shutter on wheels) and Park should be a Close event with Slaving being the event that's unique to Domes.

Alternatively, an "Open on unpark" switch would be a useful addition, much like "Close on park".

**Describe alternatives you've considered**
I've added an "indi_setprop" command to my startup script, but this is not ideal.

**Comment by knro** [comment]
I've updated INDI Nexdome driver as well to make use of this. Please test both parking and unparking. You can find the settings for this in the Options tab.
