### ISSUE TITLE
Automate RPM packages

### ISSUE THREAD

**Issue by xsnrg** [indilib/indi#1220]
Now that we have a spec file and configuration working in indilib/indi for RPM builds, let us also trigger a build automatically upon change to the code base.

If a maintainer would be so kind as to add this json webhook, we should have automated builds of RPMs at Copr.

 https://copr.fedorainfracloud.org/webhooks/github/33801/c17ec177-1c80-4644-90ac-efcf9bb72ed0/ 

Thank you!
Jim

**Comment by knro** [comment]
It's done, can you please check?

**Comment by xsnrg** [comment]
It looks like there has been a commit to master after the time you posted the message asking to check. A build was not kicked, I am not sure why. Does going to settings -> webhooks in github show any status?

The only thing I can think of is maybe the application/json type did not get set?

I double checked the URL, and Copr still says it should be :
 https://copr.fedorainfracloud.org/webhooks/github/33801/c17ec177-1c80-4644-90ac-efcf9bb72ed0/

**Comment by knro** [comment]
Right, it wasn't set to application/json... I left the secret empty, that's correct?

**Comment by xsnrg** [comment]
That is correct. Next commit should trigger a build (I hope)

**Comment by xsnrg** [comment]
It worked. 

https://api.github.com/users/knro's libindi-bleeding copr build of None for srpm-builds finished with 'success'
