### ISSUE TITLE
Allow for Alt-Az operation in AZ-GTI driver

### ISSUE THREAD

**Issue by federicoparra** [indilib/indi#1232]
Currently, users of AZ-GTI mounts can either use the AZ-GTI driver (eqmod based) in EQ mode (with the right arm Sky-Watcher firmware) or otherwise, are left to improvise using either the indi_SkyWatcher_AltAzMount or indi_SynScan drivers, both which come with plenty of limitations when used with the AZ-GTI mount.

The best solution would be to adapt the AZ-GTI driver, which works really well and has implemented tons of functionality, to work with the mount in Alt Az mode. Ideally, there would be a simple switch on the Connection pane which says EQ/ALT-AZ and we can there choose.

As an alternative, a different driver, such as AZ-GTI Alt-Az could be added, based on the AZ-GTI driver (only difference between them would be the Alt-Az capability) but this is probably more confusing for users and more complicated to keep updated.

Stellarmate developer Jasem Mutlaq @knro is developing this into the last beta version of Stellarmate; however, I've tried it and the version I got from the beta channel was based on indi-SkyWatcher_AltAzMount driver, instead of AZ-GTI (based on eqmod) driver.

I'm aware that eqmod is entirely designed for working in EQ mode, and, natively, doesn't allow alt az operation. What I'm thinking is that there should be some code sitting between the AZ-GTI driver and the underlying eqmod driver that translate alt az position into EQ position to feed/retrieve from eqmod.

**Comment by knro** [comment]
There is support for this now, but it's not suitable for astrophotography with the way it tracks. So just have to wait until @geehalel adds proper Az-Alt support to the EQMod driver, or a derivative of it.
