### ISSUE TITLE
 Please make the RST Focuser driver.

### ISSUE THREAD

**Issue by echoman7** [indilib/indi#1250]
[RSF_focuser_Protocol_200313_EN.pdf](https://github.com/indilib/indi/files/5457979/RSF_focuser_Protocol_200313_EN.pdf)
[RSF_focuser_Protocol_200313_KOR.pdf](https://github.com/indilib/indi/files/5457980/RSF_focuser_Protocol_200313_KOR.pdf)

This is the protocol for making RST_Focuser driver. 
I would appreciate it if you could make it.

http://www.rainbowastro.com/rsf-2/

**Comment by echoman7** [comment]
Thank you.

**Comment by echoman7** [comment]
I will wait for it to be made.

**Comment by boulandab** [comment]
Rainbow Astro RSF driver documentation https://indilib.org/index.php?option=com_mtree&task=viewlink&link_id=146

If you can please test it and report back if you get any issues.

**Comment by echoman7** [comment]
Thank you very much.

**Comment by echoman7** [comment]
A bug has been found in "Rainbow Astro RSF driver" 
We will inform you of the bug part with pictures. 
![rainbowrsf_bug_point](https://user-images.githubusercontent.com/44599708/104254401-105b4800-54ba-11eb-9622-518b3c330807.jpg)

**Comment by boulandab** [comment]
Can you clarify what you mean? The desired steps on the right are go to and not relative. So putting in 3000 should take you to 3000. The range is from 0 to 16000.

**Comment by echoman7** [comment]
When the first part A is 8000, if you put 1000 in B, it should be 7000 in A, which is 7999.
  
![rainbowrsf_bug_point_A](https://user-images.githubusercontent.com/44599708/104300662-1da02300-550a-11eb-8a61-e98f2ac1b9ab.jpg)

**Comment by echoman7** [comment]
When the first part A is 8000, 
if you put 1000 in B, it should be 7000 in A, which is 7999.

**Comment by knro** [comment]
A is CURRENT position
B is TARGET position

After you set B then click the "play" icon next to it, the focuser should go there so that A equals B eventually. If this is not happening then please attach the focuser logs.
