### ISSUE TITLE
Mount device configuration is always saved twice

### ISSUE THREAD

**Issue by d33psky** [indilib/indi#1299]
This happens probably for all LX200 mounts. Below paste is from a 10Micron mount.

2020-12-25T20:10:15: [INFO] Device configuration saved. 
2020-12-25T20:10:15: [INFO] Saving device configuration... 
2020-12-25T20:10:15: [INFO] Device configuration saved. 
2020-12-25T20:10:15: [INFO] Saving device configuration... 

Just once is enough really ;-)

update: plz assign to me. (cannot self-assign)

**Comment by knro** [comment]
I think one reason could be perhaps that there saveConfig for specific properties and saveConfig for all properties.

**Comment by knro** [comment]
The issue was tracked down to Serial::processHandshake since it always saves config when it is successful. A solution is to check whether the device port and baud rate are different and then skipping the saveConfig call altogether.

**Comment by knro** [comment]
This is fixed in master.
