### ISSUE TITLE
https://www.indilib.org/ down

### ISSUE THREAD

**Issue by rickbassham** [indilib/indi#1306]
**Describe the bug**
The https://www.indilib.org/ website appears to be down.

**To Reproduce**
Exact steps to reproduce the behavior.
1. Visit https://www.indilib.org/

**Screenshots**

<img width="572" alt="Screen Shot 2020-12-30 at 3 53 15 PM" src="https://user-images.githubusercontent.com/1663823/103380537-2b3fbc80-4ab7-11eb-91e9-defe037fd3fa.png">

**Comment by xsnrg** [comment]
It is fine if you do not use "www". Just go to https://indilib.org

**Comment by rickbassham** [comment]
Is this new? Wonder how my bookmark became bad... Might just be user error.

**Comment by xsnrg** [comment]
Not sure if it happened when the cert was renewed or not. I have always just used it without "www".

**Comment by rickbassham** [comment]
Closing. We'll call this user error. I've updated my bookmark.
