### ISSUE TITLE
indi_EQmod driver - HEQ5 - no Permanent PEC menu option/VS-PEC

### ISSUE THREAD

**Issue by jrhilton** [indilib/indi#1343]
I notice that the Permanent PEC tab does not appear in the indi_EQmod driver when connected to an HEQ5 on any version of the driver. Also I don't see "sidereal + PEC tracking" as an option for tracking.

Does the indi EQmod driver have PPEC or software PEC implemented? As you could do this on the ASCOM version with an HEQ5 from memory.

**Comment by geehalel** [comment]
Please post indi-eqmod issues in the relevant place namely indilib/indi-3rdparty.
Permanent PEC is a feature of the motor controller firmware: if the firmware does not advertise Permanent PEC, the indi-eqmod driver will not create a Permanent PEC tab. It is not a bug.
Software PEC is not implemented in indi-eqmod. Software PEC is relevant for every variable rate capable mount, not only indi-eqmod. It should be implemented at the INDI::Telescope class level.
