### ISSUE TITLE
Raspberry Pi HQ Camera FITS have green tint. BGGR <> RGGB

### ISSUE THREAD

**Issue by callimero** [indilib/indi#1397]
**Describe the bug**

Trying to use Raspicam HQ with Astroberry/KStars/Ekos/Indi. Resulting FITS have a green tint.

FITS also have RGGB in the Header, but I checked in Siril and BGGR fits much better, however still with a green tint.

RAWs done with raspistill and converted  to DNG are perfect.

**To Reproduce**

Take some longish exposures, tint will also be in Fitsviewer.

**Expected behavior**
![RGGB](https://user-images.githubusercontent.com/7713008/112309722-f8672800-8ca3-11eb-82d6-06098ddcc8fe.jpg)
![BGGR](https://user-images.githubusercontent.com/7713008/112309738-fc934580-8ca3-11eb-8915-841cab03874f.jpg)

Good FITS :)

**Desktop (please complete the following information):**
 - OS: Raspian/Astroberry
 - Version [e.g. 1.7.6, GIT..etc]

**Log Files**
Follows

**Comment by knro** [comment]
@lboclboc Can you please check?

**Comment by lboclboc** [comment]
Ill have a check. RGGB in fits sounds very wrong yes. A green tint is as expected since there are twice as many green pixels than red (or blue). Siril has image filters for that.

**Comment by callimero** [comment]
Ok, great. Seems that other software takes that pixel counts into account. No prob.
