### ISSUE TITLE
Plate Solve Capture Options - 'Dark' selection is not saved

### ISSUE THREAD

**Issue by phomer60** [indilib/indi#1418]
**Describe the bug**
After disconnecting and stopping INDI the 'dark' selection under alignment / Plate Solve Capture Options /dark is always unselected.

**To Reproduce**
Exact steps to reproduce the behaviour.
1. select dark to be used when plate solving / aligning
2. disconnect and stop INDI
3. Reconnect devices
4. Go to the alignment tab and the 'dark' selection is not selected

**Expected behavior**
Should save the last used setting

**Screenshots**
![image](https://user-images.githubusercontent.com/20377751/114134795-a2ed7500-994b-11eb-8296-2f931c8e6081.png)

**Desktop (please complete the following information):**
 - OS: Raspberry Pi OS 32 bit
 - Version [e.g. 1.7.6, GIT..etc] Up to date build (not stable)

**Log Files**
Make sure to enable logging and include log files https://indilib.org/support/logs-submission.html

**Comment by knro** [comment]
Thank you for the report, this is not an INDI bug. It should be fixed in the next KStars release nonetheless.
