### ISSUE TITLE
Possible fix for incorrect slew rate in ioptronv3 driver

### ISSUE THREAD

**Issue by simont77** [indilib/indi#1420]
It has been reported on indi forum that slew rate is improperly set in ioptronv3 driver.

Here https://github.com/indilib/indi/blob/605180db41dfa3c1974c37ac5bb33a690e0ef6b4/drivers/telescope/ioptronv3.cpp#L1083 there seems to be an extra "+1", since the setSlewRate function in the rolling line already increases the index when preparing the string to be sent to the mount (which should include a number from 1 to 9). The extra "+1" is indeed not present in ieq driver, and the command syntax did not change in v3 protocol.

**Comment by knro** [comment]
The index is from 0 to 8

**Comment by simont77** [comment]
Yes, but there is a +1 here and another +1 inside setSlewRate function, so at the end we send to the mount a range from 2 to 10

**Comment by knro** [comment]
oh right you're absolutely right, will fix this.
