### ISSUE TITLE
Duplicate Serial Device ID hides physically connected serial devices in INDI Control Panel

### ISSUE THREAD

**Issue by jmocenigo** [indilib/indi#1444]
### Description
List of USB serial devices in INDI Control Panel omits some units with non-unique IDs, namely if two (or more) USB serial devices cannot be distinguished based on their ID, then only one is shown. The (Ubuntu) OS has the same problem, for example:

`
$ ls -l /dev/serial/by-*
/dev/serial/by-id:
total 0
lrwxrwxrwx 1 root root 13 May  3 17:37 usb-Pegasus_Astro_FocusCube_2_PA5FN3Z4-if00-port0 -> ../../ttyUSB2
lrwxrwxrwx 1 root root 13 May  3 17:20 usb-Pegasus_Astro_PPBADV_revB_PPBA636WK4-if00-port0 -> ../../ttyUSB3
lrwxrwxrwx 1 root root 13 May  3 17:36 usb-Prolific_Technology_Inc._USB-Serial_Controller_D-if00-port0 -> ../../ttyUSB0

/dev/serial/by-path:
total 0
lrwxrwxrwx 1 root root 13 May  3 17:36 pci-0000:00:14.0-usb-0:1:1.0-port0 -> ../../ttyUSB0
lrwxrwxrwx 1 root root 13 May  3 17:20 pci-0000:00:14.0-usb-0:2:1.0-port0 -> ../../ttyUSB1
lrwxrwxrwx 1 root root 13 May  3 17:37 pci-0000:00:14.0-usb-0:3:1.0-port0 -> ../../ttyUSB2
lrwxrwxrwx 1 root root 13 May  3 17:20 pci-0000:00:14.0-usb-0:7.1:1.0-port0 -> ../../ttyUSB3
`
In this case, there are four devices (by path), but the INDI Control Panel (and the OS) only shows the three, unique IDs. For me, both my SkyWatcher EQ6 Pro and my GPS unit (GlobalSat BU-353-S4 USB GPS Receiver) show up with the same exact Prolific Technology ID (in every particular except physical connection point). The reason in this particular instance (i.e., Prolific Technology) is allegedly due to [counterfeit chips](http://www.totalcardiagnostics.com/support/Knowledgebase/Article/View/92/20/prolific-usb-to).

### To Reproduce
Requires two devices that would have the same USB ID, if the two only make one entry under /dev/serial/by-id, then the list of "System Ports" in the "Connection" panel under a device in the INDI Control Panel will likewise only show one of the N devices having the same ID.
Note: problem is particularly irksome if one has a configuration with only two devices with a duplicate ID, because these lines at the bottom of indi/libs/indibase/connectionplugins/connectionserial.cpp:

`
// If we have one physical port only, set it to the device port if the current port
// is the default port.

if (pCount == 1 && std::string(PortT[0].text) == m_ConfigPort)
        IUSaveText(&PortT[0], m_Ports[0].c_str());
`

replaces a manually corrected entry with potentially (50/50 odds) wrong serial device (code may not format properly, so just "tail" the above file).

### Expected behavior
All physically attached devices should be displayed even if two have the same ID. Either some distinct physical port information should be added to the ID to make it unique or an option to show devices either by-path or by-id should be available. Finally, code should not set pCount to 1 unless there truly is only 1 physical device.

### Desktop
 - OS: Ubuntu (20.04 or 20.10, perhaps others)
 - INDI core 1.9.0 and later (perhaps earlier, too).

**Comment by knro** [comment]
Thanks, looks like we have to merge the old method with the new one in order to put all the physical devices. Too bad the kernel doesn't take care of this for us :(
