### ISSUE TITLE
Unguided Dithering not following a random pattern

### ISSUE THREAD

**Issue by fenriques** [indilib/indi#1445]
When the checkbox 'Non-guide dither pulse' (Ekos Guide Tab -> options->guide) is checked, dither seems to occur in one direction only and not follow the expected  random pattern.
It was reported by several users in the forum:
https://indilib.org/forum/ekos/9345-unguided-dithering.html

Seems not mount related: CEM and 10Micron are affected.
It was tested with several pulse durations from 0.3s to 2.0s.
Also, changing setting in the upper 'dither' box doesn't affect the behavior.

Attached a screenshot of the settings and an image of the dither pattern over 6 hours
 
 - OS: Ubuntu
 - Version Kstars 3.5.2

![Screenshot from 2021-05-05 11-13-14](https://user-images.githubusercontent.com/38842860/117120729-ffe61a80-ad93-11eb-9047-88a80957f372.png)

![integration](https://user-images.githubusercontent.com/38842860/117120777-0bd1dc80-ad94-11eb-865e-794fec727910.jpg)
(6hrs integration of not registered subs with 0.5s dither pulse)

**Comment by knro** [comment]
Thanks for the report, but this is not an INDI bug. Should be filed at KStars: https://invent.kde.org/education/kstars/-/issues

**Comment by fenriques** [comment]
ok. i will post it there.
