### ISSUE TITLE
[featurerequest] Allow customization of simulated guide chip properties

### ISSUE THREAD

**Issue by seanhoughton** [indilib/indi#145]
Currently the simulator uses a hard-coded resolution and pixel size. It would be nice to allow customization of this in order to simulate real hardware. Is there a reason this is hard-coded? The properties for adjusting the width and height exist (no pixel size option), but they are ignored and get reset.

https://github.com/indilib/indi/blob/master/libindi/drivers/ccd/ccd_simulator.cpp#L263

**Comment by knro** [comment]
I added a separate dedicated Guide camera simulator so this is no longer a priority.
