### ISSUE TITLE
Multi-Threaded Image Acquisition 

### ISSUE THREAD

**Issue by rseidler2019** [indilib/indi#1450]
It would be good, to have the possibility to use mutliple cameras in Kstars at the same time (e.g. using a main camera rig and an other camera mounted on top, or using two cameras of the same type with different filters) using only one indiserver. Right now this is only possible with running another indiserver (with another port) and another Kstars (that crashes the main Kstars when exiting). 

@knro Are there any plans on doing a multi-threaded implementation or any hints, where one could look at?
I would be willing to invest some spare-time to look into this, if I would know the actual situation a little better.

**Comment by knro** [comment]
Thank you for the report. This is not an INDI issue per say. There has already been discussion on supporting multiple cameras at the same time in KStars, but it takes a lot of work to get this done. Follow this issue here: https://invent.kde.org/education/kstars/-/issues/90
