### ISSUE TITLE
Some ubuntu packages not built in nightly repo.

### ISSUE THREAD

**Issue by atoy40** [indilib/indi#1512]
Hello,

some packages are not scheduled to be built for ubuntu 21.04 in the indi-nightly reposistory and prevents the indi-full package to be installed :

- indi-gpsd
- indi-fli
- indi-nightscape
- indi-starbook-ten

thanks
Anthony.

**Comment by knro** [comment]
Thanks for the report, I've initiated the build process for them.

**Comment by atoy40** [comment]
It's working now ! :+1:
