### ISSUE TITLE
Synscan coordinate errors (Skywatcher Dobsonian altaz mount)

### ISSUE THREAD

**Issue by ajeb78** [indilib/indi#1519]
**Describe the bug**
Affects indi_synscan. I am using indi_synscan with a Skywatcher 250P Dobsonian on a GOTO altaz mount. The mount itself behaves correctly when used only with the handset and once aligned will slew to a given GOTO object reasonably accurately.
However when aligned and then controlled via the indi_synscan module it slews to incorrect co-ordinates. It appears to be slewing close to the correct declination but about 3 hours out in RA, (not sure if this error is always the same or just with the objects I tested on). The time on both my laptop and mount is set in UTC with DST turned off, but the bug also occurs if all times are set to BST with DST turned on. My lat / long is approx 54N 003W (this is manually input correctly into the handset from GPS coordinates from my phone).

**To Reproduce**
Align telescope using handset.
GOTO known object.
Connect telescope to computer using USB cable provided.
Run driver (via kstars / ekos).
GOTO other object via kstars.
Telescope position on kstars does not agree with position on handset, telescope points incorrectly.

**Expected behavior**
Telescope position should agree between kstars and telescope hand control.

**Screenshots**
![IMG20210722221047](https://user-images.githubusercontent.com/17723231/126898663-556b2eb5-a3a6-4c0d-9084-8b3ab34c0318.jpg)
![IMG20210722221401](https://user-images.githubusercontent.com/17723231/126898671-15dc714d-e944-4b7e-a093-a7e8b56d56fd.jpg)

**Desktop (please complete the following information):**

    OS: Kubuntu 21.04
    INDI Library: 1.9.1
    Code 1.9.1-tgz. Protocol 1.7.
    Synscan handset version 4.39.15

**Comment by knro** [comment]
Can please you please turn on INDI + Mount logging and attach the logs?

**Comment by ajeb78** [comment]
Hopefully this provides more information. It's not dark at the moment here so I've just aligned the telescope to the approximate direction of Polaris and accepted the alignment when it slews to Arcturus, but the behaviour appears consistent.

[log_17-57-06.txt](https://github.com/indilib/indi/files/6880311/log_17-57-06.txt)

I've also attached some screenshots showing the setup pages in case it helps (or if it lets you spot that I'm doing something dumb!)

![kstars-1](https://user-images.githubusercontent.com/17723231/127037468-ddb87d11-3bbd-48fb-a6fe-f6d7c2bd0366.png)
![kstars-2](https://user-images.githubusercontent.com/17723231/127037479-9774a1d2-f8bf-44e2-a49e-f07bce614410.png)
![kstars-3](https://user-images.githubusercontent.com/17723231/127037490-4deffc5f-0f78-44f4-9336-53074510370d.png)
![kstars-4](https://user-images.githubusercontent.com/17723231/127037496-3ebdab9c-4dda-44e8-8f18-f684e7620850.png)
![kstars-5](https://user-images.githubusercontent.com/17723231/127037501-11f27b75-0210-4f06-887d-20c08f4172e4.png)
![kstars-6](https://user-images.githubusercontent.com/17723231/127037507-be4df81b-0f9f-4dad-a62f-4d6b5c5ac072.png)
![kstars-7](https://user-images.githubusercontent.com/17723231/127037514-f81a2bc9-5c1a-4cec-965b-59c05fb52597.png)
![kstars-8](https://user-images.githubusercontent.com/17723231/127037530-b9ba26e0-ff0a-4877-a731-282349cf1da4.png)

As before, the displayed location of the mount in kstars jumps all over the place as the telescope is moving and then comes to rest in an incorrect position.

If you need any more information just let me know.

**Comment by knro** [comment]
It's fixed, sorry for the stupid bug. Try the nightly/beta or compile from GIT if you know how.

**Comment by ajeb78** [comment]
Fix confirmed, thank you :)
