### ISSUE TITLE
SestoSenso2 - Esatto focuser

### ISSUE THREAD

**Issue by sonny486** [indilib/indi#1522]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%24100%20Rewarded-%237E24E3.svg" />](https://issuehunt.io/r/indilib/indi/issues/1522)

Found that Esatto does have a bit of backlash, need to add (unlock) backlash function to focuser for Esatto series of focusers.

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $100.00)

- [<img src='https://avatars.githubusercontent.com/u/43073912?v=4' alt='sonny486' width=24 height=24> sonny486](https://issuehunt.io/u/sonny486) ($50.00)
- $50.00 have been anonymously funded.
### Submitted pull Requests
- [#1526 ESATTO Backlash measure and correction](https://issuehunt.io/r/indilib/indi/pull/1526)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/indilib/indi/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

**Comment by iliaplatone** [comment]
Thank you!

**Comment by sonny486** [comment]
Thank you for your hard work!
