### ISSUE TITLE
Orion SSAG (using indi_qhy_ccd driver) no longer recognized

### ISSUE THREAD

**Issue by justanenduser** [indilib/indi#154]
lsusb does not show the connected camera. 

In the 85-qhy.rules I find the following lines-

# Is 296d QHY5 or something else? Not sure
ATTRS{idVendor}=="16c0", ATTRS{idProduct}=="296d", RUN+="/sbin/fxload -t fx2 -I /lib/firmware/qhy/QHY5.HEX -D $env{DEVNAME}"

I comment out the ATTRS{idVendor}=="16c0", ATTRS{idProduct}=="296d", RUN+="/sbin/fxload -t fx2 -I /lib/firmware/qhy/QHY5.HEX -D $env{DEVNAME}" line.

lsusb now shows the connected camera- Bus 001 Device 017: ID 16c0:296d Van Ooijen Technische Informatica and indi has a successful conversation to/from the device. 

-gary-

**Comment by knro** [comment]
Thanks will remove that line from the rules.
