### ISSUE TITLE
iOptron CEM25 Compatibility with the iOptronV3 INDI Driver

### ISSUE THREAD

**Issue by jremar98** [indilib/indi#1542]
Hi, I hope I am posting this in the right forum, but I was just wondering whether there was any clarification on whether the iOptronv3 INDI driver would work with the CEM25 with the most recent firmware/motor board updates installed? I looked at the official INDI website and it was listed that it should be compatible, but digging into the ioptronv3.cpp code, I noticed it didn’t seem to accept the CEM25 as a valid mount to use with the new driver (during the sanity checks and mount name assignments). Any clarification would be most appreciated!

I’d love to try the new driver out if possible, I just don’t want to screw anything up on the software end of things.Thank you for all the hard work, it’s very very much appreciated!:)

Best, Jordan

![325F37D4-5F7B-442D-8FBB-0187B1F59B44](https://user-images.githubusercontent.com/38800011/135734430-d8e2ba4a-69bb-4dcc-8100-af5deba4c3e2.jpeg)

**Comment by knro** [comment]
I presume you have access to one? Can you please let us know if it works?
