### ISSUE TITLE
Driver crashes in Ekos causing need to reconnect camera

### ISSUE THREAD

**Issue by tjgruber** [indilib/indi#1587]
**Describe the bug**
I have a few issues where the drivers crash and I am forced to physically reconnect the USB from the camera into the R-Pi4.

First issue:

1. After I connect and open up Ekos, I am free to either start a sequence, or, open up a Live Video feed (Live Video feed example shown in screenshot).
2. As seen in my screenshot, the live video feed works just fine. I can record, GoTo, move the mount around manually if I want, etc.
3. If I close the Live Video window, it reopens up again with no live feed. It's like the drivers crash and I need to close everything, and reconnect the USB cable.
4. If instead of closing the Live Video feed, and I attempt to take pictures via a sequence, the same result happens, the drives crash.
5. The reverse is true, where if I first start taking pictures via a sequence, and then want to open up a Live Video feed, the drivers (or whatever) crash and I am forced to reconnect the USB to camera and restart everything.

Second issue:

I am able to create a sequence and take pics. But at some point, after x amount of successful pictures taken, the camera stops taking pictures but continues taking pictures anyways, reusing the last photo for each new picture taken.
For example, It'll get to 20th job in the queue, let's say job `#20` is supposed to take a photo at ISO 1600. It will take it, but then after that, every photo after that, no matter the settings of the job in the queue, will be that photo, no matter the settings.
When this happens, I no longer hear the camera shutter working, but Ekos still thinks it's taking photos and reuses the last one from `#20`.

I have no way of knowing when this happens unless I'm close enough to realize the camera shutter is no longer making it's noise while Ekos is still taking photos.

Anyone have any ideas? 

Any logs needed?

I'm using Astroberry, and have fully updated everything as of a couple days ago.

Thank you!

**Screenshots**
Screenshot of first issue:
![20220106_181720](https://user-images.githubusercontent.com/15575143/148499929-13823c85-5fa0-4fb9-96da-e7514fb14c9b.jpg)
[https://snipboard.io/KFJ8GL.jpg](https://snipboard.io/KFJ8GL.jpg)

**Desktop (please complete the following information):**
 - OS: Astroberry
 - Version: Not sure where to check but up to date as of first week of January 2022.

**Log Files**
I will work on getting the logs as described and will update post.

**Comment by knro** [comment]
It appears this is specific to Fuji since I cannot reproduce such a behavior with Canon/Nikon cameras I have over here for testing. You can possible use [Ekos Debugger](https://github.com/knro/ekosdebugger) to try to debug the INDI drivers and catch what causes the crash. This would provide better information than even regular logs do.
