### ISSUE TITLE
Focuser with variable speed when connected to an analog joystick

### ISSUE THREAD

**Issue by teoteo** [indilib/indi#1619]
When a joystick is connected, in focuser INDI Control Panel I can see 3 buttons as defined on lines:
https://github.com/indilib/indi/blob/7df8ca6d0de4157268de625c88705c2d96349876/libs/indibase/indifocuser.cpp#L64-L66
to _Focus In_, _Focus Out_ and _Abort Focus_.
<img width="751" alt="Schermata 2022-02-07 alle 10 12 49" src="https://user-images.githubusercontent.com/789650/152808830-096cb6d9-6cb8-4b2d-a100-81136f769784.png">
**My enhancement suggestion**
Once an analog joystick is connected, I’d like to see the option to control the focuser speed with the increase or degrease of axis speed. At 0 or near to 0 axis value could be a _Abort Focus_ command.
It could be useful to chose which axis or joystick to assign to  _Focus In_ and _Focus Out_ because with multiple joysticks controllers, once could be assigned to focuser and another to something other like the telescope movements.
Minimum and maximum speeds should be chosen by the user.
![PS4 joypad](https://user-images.githubusercontent.com/789650/152811062-422f4941-db80-4ead-9afe-dcc998a788fb.jpg)

**An alternative I've considered**
A simpler method could be adding other 2 buttons to control high speed speed _Focus In_ / _Focus Out_ movements
Another method could be to set two or more speed values for axis to simulate a speed ramp.

**Comment by knro** [comment]
Thank you for the suggestion. Please feel free to submit a PR if you have a time to test these changes.
