### ISSUE TITLE
MyFocuserPro2 driver enhancement request/issue

### ISSUE THREAD

**Issue by Lonniegriggs** [indilib/indi#1623]
I've been discussing with Robert Brown the developer of the MyFocuserPro2 about the driver behavior. I'm noticing that the current INDI driver does not retrieve the Max Steps and motor direction from the controller but sends the last set data to the controller. This is an issue for anyone using more than one controller for multiple rigs like myself. How is this normally handled? Can this be modified to call that data from the controller EEPROM?

**Comment by knro** [comment]
The driver gets the max position on startup and also provides ability to set it.
