### ISSUE TITLE
Ekos do not allows stop solver in 'slew to target' action (not all the time)

### ISSUE THREAD

**Issue by luzik** [indilib/indi#1624]
Don't know is this a right place for such issue, so excuse me :)

Slew to target is loop of take_picture/solve/move. While using 'slew to target' action, user is able to abort only in 'take_picture' time window (maybe also in solve step - not sure)

User should be able to stop/abort 'slew to target' all the time, also while slewing to target.

I was in loop of short exposures with fast CPU solving images and it was hard to press STOP button

**Comment by knro** [comment]
This is not the right place for it, it needs to be filed as KDE bugs https://bugs.kde.org
