### ISSUE TITLE
Enable nframe support regardless of orientation of device and set default steps/degree

### ISSUE THREAD

**Issue by mads0100** [indilib/indi#1635]
Change the phase wires from 2 to 5 in order enable full control.  Change the default steps/degree from 1000 to 55 per dev guidance.

**Comment by mads0100** [comment]
Submitted an update to it.

**Comment by knro** [comment]
Thanks. Submitted an update where?

**Comment by mads0100** [comment]
Github. It’s my first time. 

Sent from my iPhone

On Mar 5, 2022, at 15:57, Jasem Mutlaq ***@***.***> wrote:

﻿
Thanks. Submitted an update where?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by knro** [comment]
Got a link to the PR? I don't see it.

**Comment by mads0100** [comment]
https://github.com/mads0100/indi

I don’t think I did this right.. it’s the nframe.cpp that needed to be updated per Gene. 

Sorry. 

Sent from my iPhone

On Mar 5, 2022, at 16:21, Jasem Mutlaq ***@***.***> wrote:

﻿
Got a link to the PR? I don't see it.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by knro** [comment]
Please follow the instructions on how to submit a PR to INDI. Looking forward to the PR!

**Comment by astrogene1000** [comment]
Chris, the 'closest direction' nframe test code I sent was test code. To make it 'correct' there needs to be a switch for 'cord wrap' versus 'closest direction'. The original GIT was always cord wrap aware, the test code is always 'closest direction' path.
