### ISSUE TITLE
INDI Receiver and rtl-sdr

### ISSUE THREAD

**Issue by astrogene1000** [indilib/indi#1638]
**Describe the bug**
Error Messages from driver:
**On first launch prior to Connect**
 Driver /usr/bin/indi_rtlsdr93: No INumber 'RECEIVER_FREQUENCY' in RTL-SDR Receiver USB1.SENSOR_INTEGRATION
 Driver /usr/bin/indi_rtlsdr93: No INumber 'RECEIVER_SAMPLERATE' in RTL-SDR Receiver USB1.SENSOR_INTEGRATION
 Driver /usr/bin/indi_rtlsdr93: No INumber 'RECEIVER_GAIN' in RTL-SDR Receiver USB1.SENSOR_INTEGRATION
Driver /usr/bin/indi_rtlsdr93: No INumber 'RECEIVER_BANDWIDTH' in RTL-SDR Receiver USB1.SENSOR_INTEGRATION
 Driver /usr/bin/indi_rtlsdr93: No INumber 'RECEIVER_BITSPERSAMPLE' in RTL-SDR Receiver USB1.SENSOR_INTEGRATION

**After first connect, set any of 'Receiver Settings'**
Driver /usr/bin/indi_rtlsdr93: No INumber 'RECEIVER_BANDWIDTH' in RTL-SDR Receiver USB1.SENSOR_INTEGRATION

** Set gain
===RECEIVER_SETTINGS RECEIVER_GAIN=23 
Error: Invalid range for Gain (RECEIVER_GAIN). Valid range is from 1 to 4. Requested value is 23

** TCP support
There seems to be support for TCP connect to 'rtl_tcp' or other external program
There is no menu item that allows selection of direct or tcp link

** Device configuration
Device configuration 'Save' does not work for any items

**Sampling rate and Bandwidth tied together
Not possible to independently set Bandwidth, attempt to set and does nothing
Setting Sampling Rate sets Sampling Rate AND Bandwidth

** Antenna
What is this as not used by driver but exposed for setting.

**To Reproduce**
Exact steps to reproduce the behavior.
1. Run driver
2. To reproduce
See above 
3. See error
See above

**Expected behavior**

So is there -any- tutorial on using this driver or indi_receiver class in general?

**Screenshots**

**Desktop (please complete the following information):**
 - OS:
 - Version [e.g. 1.7.6, GIT..etc]
1.9.3 indilib GIT build from source

**Log Files**
Make sure to enable logging and include log files https://indilib.org/support/logs-submission.html

**Comment by iliaplatone** [comment]
Fixed in #1661 
TCP connection is not yet available though
