### ISSUE TITLE
ioptron_V3 driver crashes

### ISSUE THREAD

**Issue by wesm912** [indilib/indi#1664]
**Describe the bug**
Process:               indi_ioptronv3_telescope [32827]
Path:                  /Applications/kstars.app/Contents/MacOS/indi_ioptronv3_telescope
Identifier:            indi_ioptronv3_telescope
Version:               0
Code Type:             X86-64 (Native)
Parent Process:        indiserver [32787]
Responsible:           kstars [29195]
User ID:               501

Date/Time:             2022-05-30 02:11:36.566 -0700
OS Version:            macOS 11.6.5 (20G527)
Report Version:        12
Anonymous UUID:        0711783B-734E-7BEF-4CDE-3A9FE307A6ED

Time Awake Since Boot: 3400000 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
dyld2 mode
terminating with uncaught exception of type std::out_of_range: stoi: out of range
abort() called

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	0x00007fff2033691e __pthread_kill + 10
1   libsystem_pthread.dylib       	0x00007fff203655bd pthread_kill + 263
2   libsystem_c.dylib             	0x00007fff202ba406 abort + 125
3   libc++abi.dylib               	0x00007fff20328ef2 abort_message + 241
4   libc++abi.dylib               	0x00007fff2031a5e5 demangling_terminate_handler() + 242
5   libobjc.A.dylib               	0x00007fff202133db _objc_terminate() + 104
6   libc++abi.dylib               	0x00007fff20328307 std::__terminate(void (*)()) + 8
7   libc++abi.dylib               	0x00007fff2032abeb __cxxabiv1::failed_throw(__cxxabiv1::__cxa_exception*) + 27
8   libc++abi.dylib               	0x00007fff2032abb2 __cxa_throw + 116
9   libc++.1.dylib                	0x00007fff203017ba std::__1::stoi(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned long*, int) + 428
10  indi_ioptronv3_telescope      	0x0000000109347008 IOPv3::Driver::getMeridianBehavior(IOPv3::IOP_MB_STATE&, unsigned char&) + 280
11  indi_ioptronv3_telescope      	0x0000000109349738 IOptronV3::getStartupData() + 2264
12  indi_ioptronv3_telescope      	0x0000000109348d57 IOptronV3::updateProperties() + 263
13  libindidriver.1.9.7.dylib     	0x000000010939c5a1 INDI::DefaultDevice::ISNewSwitch(char const*, char const*, ISState*, char**, int) + 689
14  libindidriver.1.9.7.dylib     	0x00000001093dc5fb INDI::Telescope::ISNewSwitch(char const*, char const*, ISState*, char**, int) + 283
15  libindidriver.1.9.7.dylib     	0x000000010939a851 ISNewSwitch + 97
16  libindidriver.1.9.7.dylib     	0x000000010936dc89 dispatch + 2281
17  libindidriver.1.9.7.dylib     	0x000000010937077c 0x109365000 + 46972
18  libindidriver.1.9.7.dylib     	0x0000000109370bb0 0x109365000 + 48048
19  libindidriver.1.9.7.dylib     	0x0000000109370895 eventLoop + 21
20  libindidriver.1.9.7.dylib     	0x000000010937060e main + 254
21  libdyld.dylib                 	0x00007fff20380f3d start + 1

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x0000000118d1ee00  rcx: 0x00007ffee68bed38  rdx: 0x0000000000000000
  rdi: 0x0000000000000103  rsi: 0x0000000000000006  rbp: 0x00007ffee68bed60  rsp: 0x00007ffee68bed38
   r8: 0x00007ffee68bec00   r9: 0x0000000000000000  r10: 0x0000000000000000  r11: 0x0000000000000246
  r12: 0x0000000000000103  r13: 0x0000003000000008  r14: 0x0000000000000006  r15: 0x0000000000000016
  rip: 0x00007fff2033691e  rfl: 0x0000000000000246  cr2: 0x00007fff870736b8
  
Logical CPU:     0
Error Code:      0x02000148
Trap Number:     133

Thread 0 instruction stream not available.

Thread 0 last branch register state not available.

Binary Images:
       0x10933f000 -        0x10934efff +indi_ioptronv3_telescope (0) <8517D2FF-B65D-3A20-902E-0D795652BE2B> /Applications/kstars.app/Contents/MacOS/indi_ioptronv3_telescope
       0x109365000 -        0x109500fff +libindidriver.1.9.7.dylib (0) <7ABCC854-7BBB-3C25-9084-257F848E27D5> /Applications/kstars.app/Contents/Frameworks/libindidriver.1.9.7.dylib
       0x109581000 -        0x109594fff +libusb-1.0.0.dylib (0) <51FA50BE-CA7E-3D49-836A-C78499A1D6BB> /Applications/kstars.app/Contents/Frameworks/libusb-1.0.0.dylib
       0x1095a7000 -        0x10991efff +libnova-0.15.0.dylib (0) <262A5DDF-3AF3-39B7-AEEF-86A0B9DD4894> /Applications/kstars.app/Contents/Frameworks/libnova-0.15.0.dylib
       0x109937000 -        0x109abafff +libcfitsio.4.0.0.dylib (0) <407BE41C-1B16-382F-807F-41948CFFD2CC> /Applications/kstars.app/Contents/Frameworks/libcfitsio.4.0.0.dylib
       0x109c75000 -        0x109c8cfff +libz.1.2.12.dylib (0) <364ECB5F-B2B3-3F39-85AF-2D295AE13099> /Applications/kstars.app/Contents/Frameworks/libz.1.2.12.dylib
       0x109c9a000 -        0x109dedfff +libfftw3.3.dylib (0) <DCB81186-2169-3EB9-ABF1-0CF638CB2595> /Applications/kstars.app/Contents/Frameworks/libfftw3.3.dylib
       0x118c47000 -        0x118ce2fff  dyld (852.2) <A7924265-DCEF-3515-B28E-3A8279B43E29> /usr/lib/dyld
    0x7fff2009d000 -     0x7fff2009efff  libsystem_blocks.dylib (79) <4DF6D8F5-D9C2-3A96-8DE4-5E99D6B73DC8> /usr/lib/system/libsystem_blocks.dylib
    0x7fff2009f000 -     0x7fff200d4fff  libxpc.dylib (2038.120.1) <0397FC9F-BD11-31FC-882E-9EDAA1E5CA65> /usr/lib/system/libxpc.dylib
    0x7fff200d5000 -     0x7fff200ecfff  libsystem_trace.dylib (1277.120.1) <0A24EB90-5396-36B0-A7E6-E9288702856D> /usr/lib/system/libsystem_trace.dylib
    0x7fff200ed000 -     0x7fff2018afff  libcorecrypto.dylib (1000.140.4) <57E7471E-3960-3398-8918-20DF446EA99B> /usr/lib/system/libcorecrypto.dylib
    0x7fff2018b000 -     0x7fff201b7fff  libsystem_malloc.dylib (317.140.5) <10C22FD0-FC7B-3325-852E-FEC4E88D2BC5> /usr/lib/system/libsystem_malloc.dylib
    0x7fff201b8000 -     0x7fff201fcfff  libdispatch.dylib (1271.120.2) <BA7AD614-F2C2-3E89-9043-43DD548AE5B1> /usr/lib/system/libdispatch.dylib
    0x7fff201fd000 -     0x7fff20236fff  libobjc.A.dylib (824.1) <C41DA6BE-7BC8-30D9-BA01-F196997747FC> /usr/lib/libobjc.A.dylib
    0x7fff20237000 -     0x7fff20239fff  libsystem_featureflags.dylib (28.60.1) <6EB33926-8E22-3000-B2F1-C6182B8CBD8F> /usr/lib/system/libsystem_featureflags.dylib
    0x7fff2023a000 -     0x7fff202c2fff  libsystem_c.dylib (1439.141.1) <8447A4B8-0751-3EF1-AA9B-042E40EFA07D> /usr/lib/system/libsystem_c.dylib
    0x7fff202c3000 -     0x7fff20318fff  libc++.1.dylib (905.6) <81674ADB-670F-3B19-AF5D-F3F66CB93D44> /usr/lib/libc++.1.dylib
    0x7fff20319000 -     0x7fff2032efff  libc++abi.dylib (905.6) <78CE7863-E224-3D0B-98F1-E5E3E382322D> /usr/lib/libc++abi.dylib
    0x7fff2032f000 -     0x7fff2035efff  libsystem_kernel.dylib (7195.141.26) <F0EA5D27-BBC5-3934-AB09-4A5301731981> /usr/lib/system/libsystem_kernel.dylib
    0x7fff2035f000 -     0x7fff2036afff  libsystem_pthread.dylib (454.120.2) <49670AEC-4D5D-3383-906C-23F568351FCB> /usr/lib/system/libsystem_pthread.dylib
    0x7fff2036b000 -     0x7fff203a6fff  libdyld.dylib (852.2) <5FBD0E1A-ACCE-36DB-B11C-622F26C85132> /usr/lib/system/libdyld.dylib
    0x7fff203a7000 -     0x7fff203b0fff  libsystem_platform.dylib (254.80.2) <A85D12B6-6213-34EE-84D8-8E993C19E330> /usr/lib/system/libsystem_platform.dylib
    0x7fff203b1000 -     0x7fff203dcfff  libsystem_info.dylib (542.40.3) <36329FC6-9982-306A-87F9-D018E7F49F4B> /usr/lib/system/libsystem_info.dylib
    0x7fff203dd000 -     0x7fff2087afff  com.apple.CoreFoundation (6.9 - 1778.103) <F6B4A762-9B17-359D-B9B6-C03588493220> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
    0x7fff22476000 -     0x7fff226d5fff  libicucore.A.dylib (66112) <251FC896-7EA1-3505-A9AA-80BAE7A6FD2B> /usr/lib/libicucore.A.dylib
    0x7fff226d6000 -     0x7fff226dffff  libsystem_darwin.dylib (1439.141.1) <29F82ABE-E1A0-3BC2-B91E-ADC010CF23FA> /usr/lib/system/libsystem_darwin.dylib
    0x7fff22a46000 -     0x7fff22af4fff  com.apple.framework.IOKit (2.0.2 - 1845.120.6) <61CDC69E-EC9E-32B1-8A63-532619BA310F> /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit
    0x7fff22af5000 -     0x7fff22b00fff  libsystem_notify.dylib (279.40.4) <608B5A07-D31A-3BEC-86BF-C2E498C085AF> /usr/lib/system/libsystem_notify.dylib
    0x7fff24a8d000 -     0x7fff24a9bfff  libsystem_networkextension.dylib (1295.140.3) <022BE26C-C058-3CC7-8E0B-348B3D3B639C> /usr/lib/system/libsystem_networkextension.dylib
    0x7fff24a9c000 -     0x7fff24a9cfff  libenergytrace.dylib (22.100.1) <13CE770E-37DA-35D5-84A7-2F6C07F3B707> /usr/lib/libenergytrace.dylib
    0x7fff24afa000 -     0x7fff24b10fff  libsystem_asl.dylib (385.0.2) <A5147017-3488-3B18-A11B-C19697C110FC> /usr/lib/system/libsystem_asl.dylib
    0x7fff2620d000 -     0x7fff26214fff  libsystem_symptoms.dylib (1431.140.1) <EA6435E7-8F85-315B-8AED-C20A07DE7F96> /usr/lib/system/libsystem_symptoms.dylib
    0x7fff263d1000 -     0x7fff263d3fff  libDiagnosticMessagesClient.dylib (112) <2FCF6C74-5FAF-3968-AE36-294C9EF3AA75> /usr/lib/libDiagnosticMessagesClient.dylib
    0x7fff28520000 -     0x7fff28530fff  libsystem_containermanager.dylib (318.100.4) <E0A89571-6D3E-3184-9F39-C6094C87B92B> /usr/lib/system/libsystem_containermanager.dylib
    0x7fff29238000 -     0x7fff2923bfff  libsystem_configuration.dylib (1109.140.1) <89E70992-616F-3DD3-9430-67025F759A1B> /usr/lib/system/libsystem_configuration.dylib
    0x7fff2923c000 -     0x7fff29240fff  libsystem_sandbox.dylib (1441.141.6) <53DE290F-AEA6-34E4-8491-348A79CF3A95> /usr/lib/system/libsystem_sandbox.dylib
    0x7fff29e40000 -     0x7fff29e42fff  libquarantine.dylib (119.40.4) <1263FFEA-9722-39FA-A097-D28B4F7FDE04> /usr/lib/system/libquarantine.dylib
    0x7fff29e67000 -     0x7fff29e77fff  libbsm.0.dylib (68.40.1) <FEA138A5-B03E-3AD5-9E21-3F35405D147F> /usr/lib/libbsm.0.dylib
    0x7fff2a3eb000 -     0x7fff2a3effff  libsystem_coreservices.dylib (127.1) <7AE405FC-6A44-34A0-86AD-6BD80B0050BB> /usr/lib/system/libsystem_coreservices.dylib
    0x7fff2a5ec000 -     0x7fff2a5fefff  libz.1.dylib (76) <73C471D3-07CE-307D-A531-92C5D0E4C0E9> /usr/lib/libz.1.dylib
    0x7fff2a5ff000 -     0x7fff2a64afff  libsystem_m.dylib (3186.100.3) <10F86B94-7CEE-35AB-86DC-E91032378BC7> /usr/lib/system/libsystem_m.dylib
    0x7fff2a64c000 -     0x7fff2a651fff  libmacho.dylib (980) <1FCE2BE3-4F6F-3EAA-9BC5-A9892A45CF0D> /usr/lib/system/libmacho.dylib
    0x7fff2a652000 -     0x7fff2a66dfff  libkxld.dylib (7195.141.26) <5B4ABD1D-7A6E-34F5-AE7B-04ED6C0AFE2F> /usr/lib/system/libkxld.dylib
    0x7fff2a66e000 -     0x7fff2a679fff  libcommonCrypto.dylib (60178.120.3) <7E242F29-1CB6-30EF-8C9A-C768A90FDBA0> /usr/lib/system/libcommonCrypto.dylib
    0x7fff2a67a000 -     0x7fff2a684fff  libunwind.dylib (201) <A5B040A8-847F-36EE-B13D-5DD1F5CD5BED> /usr/lib/system/libunwind.dylib
    0x7fff2a685000 -     0x7fff2a68cfff  liboah.dylib (203.58) <26D08622-69F5-32DB-80D2-9B4651A9F0CC> /usr/lib/liboah.dylib
    0x7fff2a68d000 -     0x7fff2a697fff  libcopyfile.dylib (173.40.2) <8C783785-0F5F-3DC5-B815-B29CEBA75737> /usr/lib/system/libcopyfile.dylib
    0x7fff2a698000 -     0x7fff2a69ffff  libcompiler_rt.dylib (102.2) <1FDC92D1-8A17-30AF-8E72-4F0517AEA157> /usr/lib/system/libcompiler_rt.dylib
    0x7fff2a6a0000 -     0x7fff2a6a2fff  libsystem_collections.dylib (1439.141.1) <11D5775A-AD4C-35ED-BC05-616AB67ACBBE> /usr/lib/system/libsystem_collections.dylib
    0x7fff2a6a3000 -     0x7fff2a6a5fff  libsystem_secinit.dylib (87.60.1) <27982311-637E-3308-9F55-4871762736F4> /usr/lib/system/libsystem_secinit.dylib
    0x7fff2a6a6000 -     0x7fff2a6a8fff  libremovefile.dylib (49.120.1) <5973CED7-797B-3288-9589-C1856752F91A> /usr/lib/system/libremovefile.dylib
    0x7fff2a6a9000 -     0x7fff2a6a9fff  libkeymgr.dylib (31) <AAA929A0-45E5-3186-8ABD-37EB25B2C939> /usr/lib/system/libkeymgr.dylib
    0x7fff2a6aa000 -     0x7fff2a6b1fff  libsystem_dnssd.dylib (1310.140.1) <4A85F13B-E3AD-3C44-B327-091F56D35CC1> /usr/lib/system/libsystem_dnssd.dylib
    0x7fff2a6b2000 -     0x7fff2a6b7fff  libcache.dylib (83) <435668CB-666B-3379-AD65-F604A72099F4> /usr/lib/system/libcache.dylib
    0x7fff2a6b8000 -     0x7fff2a6b9fff  libSystem.B.dylib (1292.120.1) <1F975097-394B-3A31-9FA8-515350BB2527> /usr/lib/libSystem.B.dylib
    0x7fff2a6ba000 -     0x7fff2a6bdfff  libfakelink.dylib (3) <C7E36B51-4FD6-3704-975E-AB9B46DF6D30> /usr/lib/libfakelink.dylib
    0x7fff2a6be000 -     0x7fff2a6befff  com.apple.SoftLinking (1.0 - 1) <AF16BDE9-8995-39F5-A0ED-C65232A61095> /System/Library/PrivateFrameworks/SoftLinking.framework/Versions/A/SoftLinking
    0x7fff2dc12000 -     0x7fff2dc12fff  liblaunch.dylib (2038.120.1) <A3F46CC6-BD89-39DB-8732-C885B881A635> /usr/lib/system/liblaunch.dylib
    0x7fff300a9000 -     0x7fff300a9fff  libsystem_product_info_filter.dylib (8.40.1) <6CA8DEA4-5BD4-375F-9AA7-3338135306C5> /usr/lib/system/libsystem_product_info_filter.dylib

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=521.9M resident=0K(0%) swapped_out_or_unallocated=521.9M(100%)
Writable regions: Total=181.1M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=181.1M(100%)
 
                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Kernel Alloc Once                    8K        1 
MALLOC                            51.1M       24 
MALLOC guard page                   24K        5 
MALLOC_MEDIUM (reserved)         120.0M        1         reserved VM address space (unallocated)
STACK GUARD                       56.0M        1 
Stack                             8192K        1 
VM_ALLOCATE                          8K        2 
__DATA                            2333K       61 
__DATA_CONST                      3126K       47 
__DATA_DIRTY                        96K       26 
__LINKEDIT                       501.0M       13 
__OBJC_RO                         70.3M        1 
__OBJC_RW                         2496K        2 
__TEXT                            21.0M       60 
__UNICODE                          588K        1 
shared memory                        8K        2 
===========                     =======  ======= 
TOTAL                            835.8M      248 
TOTAL, minus reserved VM space   715.8M      248 

**To Reproduce**
Exact steps to reproduce the behavior.
Set up an Ekos profile with iOptron GEM 28 as the mount
Try to start Ekos

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS 11.6.5
 - Version [e.g. 1.7.6, GIT..etc]

**Log Files**
Make sure to enable logging and include log files https://indilib.org/support/logs-submission.html

**Comment by knro** [comment]
You got verbose mount communication log? you can enable this in Ekos (if you're using Ekos) or INDI control Panel directly.
