### ISSUE TITLE
Fix INDI Docker build

### ISSUE THREAD

**Issue by knro** [indilib/indi#1682]
Since libev-ev was added, all builds for Linux distributions are failing. How do we trigger docker rebuild?

Would appreciate any help on resolving this, and perhaps how to fix it in case it happens again in the future.

@abecadel
@jochym 
@eric-vickery

**Comment by abecadel** [comment]
@knro  you need to manually trigger this action https://github.com/indilib/indi/actions/workflows/docker.yml - there's a button to do it

**Comment by knro** [comment]
Thanks!! I can't believe it was this simple. Now need to figure out why Fedora is failing along with MacOS.

**Comment by knro** [comment]
Any idea on what is causing the Fedora failure? Usually @xsnrg would be able to help in this but I think he is busy now.

**Comment by pawel-soja** [comment]
@knro I think the issue can be closed.
