### ISSUE TITLE
Issue with interface in Polar alignment

### ISSUE THREAD

**Issue by juandanielmorcilloregueiro** [indilib/indi#1707]
Hi,

A couple of times, when I tried to do a Polar alignment, I´m not able to position the triangle over the star that I want. When I click with the mouse in a point of the image, triangle moves to a different part of the picture. It is like coordinates of image doesn´t match with coordinates of my mouse.

If I close KStars and I start the process from 0 it works fine, so it is something that doesn´t happend all the times.

I´m using Ekos (version 1.9.5 of Indi) with Astroberry in a Raspberry PI 3, and I´m using VNC to handle Ekos. I don´t have any other problem with the mouse, it only happends with the alignment picture. I´m using a ASI294 MM camera, in binning 4 mode for Polar alignment. I don´t know if it could be related with binning, because it changes the size of the image and could affect to coordinates. I also tried with binning 2 and the same results.

I don´t have logs, and I´m not sure this kind of issues appears in logs. I will try to collect it next time if the error appears again.

For example, in the next picture I´m not able to see the entire triangle. If I click on the rigth bottom corner, triangle moves to position you see in the image.

![180761730-081ad770-f5e5-4880-9125-98041f8f1ab9](https://user-images.githubusercontent.com/26090303/180852959-e6d9ac88-21e6-4668-af48-b3cd05d5d33b.png)

Thanks and best regards.

**Comment by knro** [comment]
Thank you for the report, but this is not an INDI issue. KStars is a separate project. You may files bugs at bugs.kde.org
