### ISSUE TITLE
Update Omegon SDK version in INDI omegon driver

### ISSUE THREAD

**Issue by markusd112** [indilib/indi#1711]
INDI is using Omegon SDK version 50.19728.20211022

There is a new SDK version available 53.20923.20220526

https://www.omegon.eu/astronomical-cameras/omegon-camera-vetec-571-c-color/p,67320#tab_bar_4_select

I am using INDI on Stellarmate OS 1.7.1

**Comment by energiebrand** [comment]
Great that you´ve found that!

**Comment by knro** [comment]
It's been updated, thanks!
