### ISSUE TITLE
StellarSolver Options - Overlay issue

### ISSUE THREAD

**Issue by sophisticatedDreamer** [indilib/indi#1714]
**Describe the bug**
In the menu 'StellarSolver Options' > 'Alignment Options' the 'Overlay'  checkbox seems to be activated by default. Thus an overlay images is displayed at the solved position on KStars' map. Deactivating this option has no effect - the overlay image remains visible on KStars' map display.

To have it deactivated KStars / Ekos / INDI has to be closed first, then to be restarted. Only after a restart of KStars the disabled 'Overlay' option becomes effective.

Strangely, when KStars was restarted this way (with Overlay being disabled), the Overlay can be activated again easily with a single click on its checkbox. It then immediately(!) becomes visible. Unfortunately, it cannot be dectivated again, like described above.

**To Reproduce**
1. Start plate solving (Simulator is sufficient)
2. When the overlay image appears on the map (or when plate solving has terminated), switch the 'Overlay' option off in 'StellarSolver Options' > 'Alignment Options' > 'Overlay' checkbox. The overlay will still be visible
3. Close KStars completely and restart it > the Overlay is now turned off during plate solving and afterwards.
4. Activate the 'Overlay' check box again > immediately the overlay image appears on the KStars map
5. This option now(!) cannot be effectively disabled again - overlay image remains visible.
6. Continue with step "2." to get rid of the overlay image again.

**Expected behavior**
When activating or deactivating the 'Overlay' option in 'StellarSolver Options' > 'Alignment Options', the visibility of the overlay image should behave accordingly.

**Desktop (please complete the following information):**
 - OS: current Astroberry on RasPi4
 - KStars-3.5.9 Stable
 - Build: 2022-06-04T11:30:31Z

**Comment by knro** [comment]
Thank you for the report. This is not an INDI issue, it's a KStars issue that must be filed at bugs.kde.org
