### ISSUE TITLE
Ekos crashes on opening object list in Mount control widget

### ISSUE THREAD

**Issue by nelsonsousa** [indilib/indi#1716]
Opening the mount control widget and then clicking on the Find icon to open the list of objects sometimes causes Ekos and Kstars to close. Nothing shows up on the logs. Doesn't happen all the time. When it does is on the first invocation of the find window.

Steps to reproduce
1. Start Ekos
2. Go to Mount tab, open mount control
3. Click find button

Environment:
[log_22-12-45.txt](https://github.com/indilib/indi/files/9294304/log_22-12-45.txt)

 - OS: Stellarmate on Raspberry Pi 4, 8Gb RAM
 - Kstars 3.6.0. This behaviour was not observed on 3.5.x

Log file produced from Ekos debug:
[log_22-12-45.txt](https://github.com/indilib/indi/files/9294310/log_22-12-45.txt)

**Comment by knro** [comment]
Thanks, but this is not an INDI issue. File a bug report with KDE.
