### ISSUE TITLE
FITS files are not written as a multiply of 2880 bytes

### ISSUE THREAD

**Issue by han-k59** [indilib/indi#1733]
The september version of EKOS does no longer writes FITS files confirm the FITS standard as a multiply of 2880 bytes. See INDI forum:

https://indilib.org/forum/ekos/12298-fits-file-size-not-a-multiple-of-2880-anymore.html

**Comment by knro** [comment]
IIRC, this was fixed in master. Can you check if master produces correct files?

**Comment by knro** [comment]
This should be fixed in INDI v1.9.9
