### ISSUE TITLE
Celestron NexStar - Bad file descriptor

### ISSUE THREAD

**Issue by oliver1974** [indilib/indi#175]
Hello,

I use the libindi masterbranch (tree ca0e86002e).
When trying to connect via Ekos to my Celestron CGE, I run into the error: Bad file descriptor.
With libindi version 1.4.1 I could still connect without problem to my CGE.

OS Linux (openSuSE Leap 42.2)

Thanks in advance,
Oliver

[2017-03-14.zip](https://github.com/indilib/indi/files/842862/2017-03-14.zip)
[2017-03-14.zip](https://github.com/indilib/indi/files/842864/2017-03-14.zip)

**Comment by knro** [comment]
Thanks for report, it is fixed in GIT.
