### ISSUE TITLE
Issue in Alnitak Flip-Flat protocol implementation ('0' instead 'O')

### ISSUE THREAD

**Issue by RunTJoe** [indilib/indi#1753]
**Describe the bug**
The Alnitak protocol specification ("Alnitak Generic Commands, 6/12/2017, Rev 44") states that the "fill" character for unused characters of the fixed length commands and responses is "O"  (latin letter O), but the INDI driver implementation uses and expects a "0" (the digit zero). Therefore some replies from the Flip-Flat are not accepted as valid by the INDI driver and the driver does not work correctly with genuine devices and clones using the correct protocol implementation.

See also:
[https://www.cloudynights.com/topic/849100-alnitak-flip-flat-commands/#entry12263187](https://www.cloudynights.com/topic/849100-alnitak-flip-flat-commands/#entry12263187)
[https://github.com/RunTJoe/ELFlatPanel/issues/2](https://github.com/RunTJoe/ELFlatPanel/issues/2)

**Expected behavior**
The driver should use the fill character "O" instead of "0" and accept messages from the Flip-Flat device containing "O" as fill character. 
For compatibility reasons I would propose to accept messages with both fill characters to still support various clone implementations (mostly Arduino/ESP32 based) with the wrong protocol implementation.

**Comment by knro** [comment]
I've been using FlipFlat for over 5 years now in the observatory and never had an issue with this. The [official Optec documentation](https://www.optecinc.com/astronomy/catalog/alnitak/images/general_commands.pdf) lists 0 as the filler and not **O**. I found another document online that claims to be 'O' but it's actually not from Optec.

I will try a fix that would work for both implementations.
