### ISSUE TITLE
ISR_NOFMANY changed by Client base

### ISSUE THREAD

**Issue by knro** [indilib/indi#1759]
This is a regression due to recent changes in INDI (didn't bisect yet). If a switch property is set to ISR_NOFMANY, when the client receives the property it's always ISR_1OFMANY.

![image](https://user-images.githubusercontent.com/5986347/201303528-30af0b50-9f64-42d1-be5d-c6728d8f4636.png)

**Comment by pawel-soja** [comment]
I'll take care of it

**Comment by knro** [comment]
Thanks it's fixed now. Btw, do we need to check for other struct members that could be missing as well?
