### ISSUE TITLE
V4L2 camera crash

### ISSUE THREAD

**Issue by vladtcvs** [indilib/indi#1762]
**Describe the bug**

Selecting Format:Native in EKOS and trying to capture images leads to v4l2 driver crash

**To Reproduce**
Exact steps to reproduce the behavior.
1. Run EKOS with V4L2 camera (sv205 in my case)
2. Select Format: Native in "CCD" tab
3. Select correct exposure
4. Select Capture Options / Capture format: YUYV4:2:2 in INDI Control Panel
5. Press "Start sequence" (sometimes need to press twice)
6. See message about crash

**Expected behavior**
Camera captures and saves images

**Screenshots**
![V4L2](https://user-images.githubusercontent.com/3390973/201497727-ed151792-6399-4328-aef1-a7740e8ebede.png)

**Desktop (please complete the following information):**
 - OS: Kubuntu 20.3
 - INDI Version: 1.9.8

**Log Files**
[log_04-05-53.txt](https://github.com/indilib/indi/files/9996104/log_04-05-53.txt)

**Comment by knro** [comment]
I believe this could be fixed in b2c505dba472164378027cf21ebd18ab42c88793 

Can you test GIT?
