### ISSUE TITLE
LX200 AM5 mount ALT/AZ mode support

### ISSUE THREAD

**Issue by nicomedia** [indilib/indi#1782]
Hello guys,

It seems there is a support for Azimuth mode for AM5 mount but i could not get any related properties from indi client like "change mount type, change mode, read ALT/AZ" values etc. 
```
INDI::PropertySwitch MountTypeSP {2};
        enum
        {
            Azimuth,
            Equatorial
        };
```
I manually could change the working mode of the AM5 mount by calling setMountType function in lx200am5.cpp. I have also manually read ALT and AZ values by calling : getLX200Alt, getLX200Az.

When i checked the lx200driver.cpp i saw the functions setObjAz and setObjAlt. However in the comment, it is explicitly say that 
"Sets the target Object Azimuth [LX 16” and Autostar II only]". 

I try to change the ALT and AZ values but i could not make it so far. By the way i am calling slewToAltAz function as well.

According to me, lx200am5 driver seems not completely support Azimuth mode, it partially supports.  I could work RA and DEC without problem.

My question is that does lx200am5 support Azimuth mode or not ? If it does, how could i switch it from EQ to AZALT mode ? If it does not do you have plan to add it or may i help you about it ? 

Best Regards
Fatih

**Comment by knro** [comment]
If AM5 was put into Alz-Az mode and the driver sends it a GOTO request, then I don't think it matters much if it was sent in horizontal or equatorial coordinates. The mount would arrive there and track according to the selected mode.
