### ISSUE TITLE
99-indi_auxiliary.rules limits usbfs_memory_mb when already set to unlimited

### ISSUE THREAD

**Issue by dimich-dmb** [indilib/indi#1797]
When `usbfs_memory_mb` is set to 0 (unlimited) `99-indi_auxiliary.rules` from `drivers/auxiliary/` overwrites it with 256, so limits it. Additional check for special value `0` is required.

**Comment by knro** [comment]
Please submit a PR.

**Comment by dimich-dmb** [comment]
Please see https://github.com/indilib/indi/pull/1810
