### ISSUE TITLE
Driver "indi_lacerta_fmc_focus" (!) (for Firmware version 3.1) hangs up when disconnecting @ 100% kernel load

### ISSUE THREAD

**Issue by timpeKH** [indilib/indi#1841]
For the Lacerta MFOC a new firmware 3.1was introduced together with a new driver "indi_lacerta_mfoc_fmc_focus"
with libindi1 version 2.0.0. According to Lacerta this driver is specific for the Lacerta MFOC with firmware version 3.1.
The driver hangs up when disconnecting in the INDI control panel. Even though all other hardware drivers of the indiserver process are disengaged the "indi_lacerta_mfoc_fmc_focus" remains active and generates a high processor load of 100% for one kernel. Establishing a connection to the Lacerta MFOC is not possible in this state. The driver process must be terminated manually using bash/kill or other tool and restarted before a connection to the device is possible again.
The behaviour can be reproduced.

Unlike the driver "indi_lacerta_mfoc_focus" for older firmware versions (which crashes when doing relative position command in **inward** direction -> causes negative position number which causes firmware to crash, see [https://github.com/indilib/indi/issues/1834](https://github.com/indilib/indi/issues/1834)), the device does not need to be switched off and on to be able to reconnect.

Although the driver log files in debug mode did not show anything helpful from my naive perspective I attached a log file.

**To Reproduce**
Exact steps to reproduce the behavior.
1. Run driver indi_lacerta_mfoc_fmc_focus in the KSTARS -> Tools -> Device -> Device Manager -> [ Runs as local service or server]
2. Alternatively to step 1. the behaviour is the same on a remote server (e.g. a Raspberry)
3. Connect to "Lacerta MFOC FMC".
4. Disconnect from "Lacerta MFOC FMC".
5. Check the processes with a suitable tool (e.g. htop). One can see the process "indi_lacerta_mfoc_fmc_focus" run on one kernel usually at 100% load (for the specific kernel).
6. Kill the process "indi_lacerta_mfoc_fmc_focus" manually in htop or via bash

**Expected behavior**
Client disconnects with driver/server remaining responsive at low processor load waiting for a new connection

**Screenshots**
![Screenshot_2023-02-05_16-45-44](https://user-images.githubusercontent.com/124307800/216835366-a4e100e8-6373-461e-854b-3e5c1f21220a.png)
![Screenshot_2023-02-05_17-50-50](https://user-images.githubusercontent.com/124307800/216835625-b546c966-811e-4383-8cdb-83b800829a8f.png)

**Desktop (please complete the following information):**
 - OS: XUbuntu 22.04 LTS amd64 / Ubuntu Server 22.04 LTS arm 64
 - libindi version 2.0.0 (31.01.2022)

**Log Files**
[LOCAL_SERVER_indi_lacerta_mfoc_fmc_focus_16-30-52.log](https://github.com/indilib/indi/files/10611692/LOCAL_SERVER_indi_lacerta_mfoc_fmc_focus_16-30-52.log)

**Comment by chkettu** [comment]
merge request opened - should be fixed with next release!
