### ISSUE TITLE
Sony A7IV unable to use BULB

### ISSUE THREAD

**Issue by nvrLa7e** [indilib/indi#1857]
Hi, 

I’ve set my Sony A7IV as per instruction on driver site and once I performed the test shoot for 10s, camera setting changed from BULB to 1s exposure and only 1s exposure has been taken. I’ve changed the setting back to BULB, and run 10s test exposure again, but the camera took only 1.6s exposure and EKOS was still running the count to finish 10s exposure. 
once it finished countdown, the error appeared and it run additional 2 exposures which finished with failure as well. 

![FFFD6045-7AB9-4135-96A9-173FB65A4529](https://user-images.githubusercontent.com/126255409/221184789-643405a4-6d73-423d-bb4b-fc45b38e1dc0.jpeg)

Desktop (please complete the following information): Raspberry PI 4B
 - OS: StellarMate OS
 - Version: 1.7.5
[log_12-42-18.txt](https://github.com/indilib/indi/files/10824358/log_12-42-18.txt)

**Comment by knro** [comment]
Since you're on StellarMate, what's the output for StellarMate dashboard --> Diagnostics --> DSLR Test?
