### ISSUE TITLE
Dark Library switches to FITS (no XSIF)

### ISSUE THREAD

**Issue by evripidis** [indilib/indi#1888]
**Describe the bug**
While I am trying to create a Dark Library with XSIF files, automatically switches to FITS. In the meantime in the Capture module, I can capture darks as XSIF with no issue.

**To Reproduce**

1. Capture Module --> Tools --> Darks
2. Perform action
3. The files saved in /tmp/ and the final MasterDark is FITS

**Expected behavior**
All the files to be saved as XSIF (??? or this is not possible cause it is unable to create the master darks?)

**Desktop (please complete the following information):**
 - OS: Lubuntu 
 - Version Latest stable

**Comment by knro** [comment]
Thanks, this is not an INDI issue. Please file a bug report with KStars.
