### ISSUE TITLE
Watchdog fires prematurely

### ISSUE THREAD

**Issue by praetp** [indilib/indi#1904]
**Describe the bug**
kstars was connect to indi but watchdog still fires.
I have configured the watchdog to fire after 5s of loss of communication with the client.
Communication was not interrupted but the watchdog still fired.

Additionally, it does not seem possible to enable Debug on the watchdog.

**Desktop (please complete the following information):**
 - OS: Raspberry PI Os
 - Version : indi 2.0.2

**Log Files**
Search for _WatchDog_
[log_22-54-55.txt.zip](https://github.com/indilib/indi/files/11655660/log_22-54-55.txt.zip)

**Comment by knro** [comment]
If you put heat beat to 30 seconds, then it depends on WHEN we lost communication with the client. It could be that the timer start and waits for 30 seconds. If the client disconnects by 25 seconds, then it's only 5 seconds until the timer *check* is perform. So after 5 seconds, the shutdown procedure would start.
