### ISSUE TITLE
indiserver is stopped if remote slave indiserver is stopped through indiwebmanager

### ISSUE THREAD

**Issue by gnthibault** [indilib/indi#1927]
**Describe the bug**
There seems to be a really nasty bug in the implementation of multi indiserver setup described here, and based on https://www.indilib.org/support/tutorials/159-indi-on-multiple-devices.html

I cannot understand what is wrong in my setup, and why the master indiserver is stopped upon its slave being stopped (even though the driver is stopped)

**To Reproduce**
First, try to execute this in a shell with simulators:

```
# start master server
indiserver -vvv -p 7624 -m 1000 -v -f /tmp/indiFIFO -u /tmp/indiFIFO_sock > /tmp/indiserver.log 2>&1
# start slave server
indiserver -vvv -p 7627 -m 1000 -v -f /tmp/indiFIFO_guiding_camera -u /tmp/indiFIFO_guiding_camera_sock > /tmp/indiserver2.log 2>&1
# start slave driver
echo "start indi_simulator_guide " > /tmp/indiFIFO_guiding_camera
# Start master link
echo "start \"Guide Simulator\"@localhost:7627" > /tmp/indiFIFO
# Stop slave driver
echo "stop \"Guide Simulator\"@localhost:7627" > /tmp/indiFIFO
# ps -lA | grep indiserver and get the last PID that should be the slave pid
kill -9
# Nothing weird should happend
```

You can also do the same thing, but with an indi camera (let say an asi 290mm in my case:

```
# start master server
indiserver -vvv -p 7624 -m 1000 -v -f /tmp/indiFIFO -u /tmp/indiFIFO_sock > /tmp/indiserver.log 2>&1
# start slave server
indiserver -vvv -p 7627 -m 1000 -v -f /tmp/indiFIFO_guiding_camera -u /tmp/indiFIFO_guiding_camera_sock > /tmp/indiserver2.log 2>&1
# start slave driver
echo "start indi_asi_ccd " > /tmp/indiFIFO_guiding_camera
# Start master link
echo "start \"ZWO CCD ASI290MM Mini\"@localhost:7627" > /tmp/indiFIFO
# Stop slave driver
echo "stop \"ZWO CCD ASI290MM Mini\"@localhost:7627" > /tmp/indiFIFO
# At this point master server should have no link with the remote slave server
# ps -lA | grep indiserver and get the last PID that should be the slave pid
kill -9
# Nothing weird should happend

```

Now, when trying to replace all the master-server-side action by an indiwebmanager instance (actually, [a fork ](https://github.com/knro/indiwebmanager/pull/56)I am still working, so sorry for the reproducibility.... )  I see the master server being stopped, whenever the slave server is stopped (processed is killed).

The corresponding logs from the master indiserver are the following one:

> cat /tmp/indiserver.log 
> 2023-08-23T20:23:02: startup: indiserver -p 7624 -m 1000 -v -f /tmp/indiFIFO -u /tmp/indiFIFO_sock
> 2023-08-23T20:23:02: listening to port 7624 on fd 5
> 2023-08-23T20:23:02: Local server: listening on local domain at: @/tmp/indiFIFO_sock
> 2023-08-23T20:23:02: FIFO: start indi_simulator_ccd -n "CCD Simulator"
> 2023-08-23T20:23:02: With name: CCD Simulator
> 2023-08-23T20:23:02: FIFO: Starting driver indi_simulator_ccd
> 2023-08-23T20:23:02: Driver indi_simulator_ccd: pid=4126 rfd=9 wfd=9 efd=10
> 2023-08-23T20:23:02: Driver indi_simulator_ccd: snooping on Telescope Simulator.EQUATORIAL_EOD_COORD
> 2023-08-23T20:23:02: Driver indi_simulator_ccd: snooping on Telescope Simulator.EQUATORIAL_COORD
> 2023-08-23T20:23:02: Driver indi_simulator_ccd: snooping on Telescope Simulator.TELESCOPE_INFO
> 2023-08-23T20:23:02: Driver indi_simulator_ccd: snooping on Telescope Simulator.GEOGRAPHIC_COORD
> 2023-08-23T20:23:02: Driver indi_simulator_ccd: snooping on Telescope Simulator.TELESCOPE_PIER_SIDE
> 2023-08-23T20:23:02: Driver indi_simulator_ccd: snooping on Rotator Simulator.ABS_ROTATOR_ANGLE
> 2023-08-23T20:23:02: Driver indi_simulator_ccd: snooping on Focuser Simulator.ABS_FOCUS_POSITION
> 2023-08-23T20:23:02: Driver indi_simulator_ccd: snooping on Focuser Simulator.FOCUS_TEMPERATURE
> 2023-08-23T20:23:02: Driver indi_simulator_ccd: snooping on CCD Simulator.FILTER_SLOT
> 2023-08-23T20:23:02: Driver indi_simulator_ccd: snooping on CCD Simulator.FILTER_NAME
> 2023-08-23T20:23:02: Driver indi_simulator_ccd: snooping on SQM.SKY_QUALITY
> 2023-08-23T20:23:02: Driver indi_simulator_ccd: snooping on Focuser Simulator.FWHM
> 2023-08-23T20:24:59: FIFO: start "ZWO CCD ASI290MM Mini"@localhost:7627 -n ""ZWO CCD ASI290MM Mini"@localhost:7627"
> 2023-08-23T20:24:59: FIFO: Starting driver ZWO CCD ASI290MM Mini@localhost:7627 -n ZWO CCD ASI290MM Mini@localhost:7627
> 2023-08-23T20:24:59: Driver ZWO CCD ASI290MM Mini@localhost:7627 -n ZWO CCD ASI290MM Mini@localhost:7627: socket=8
> 2023-08-23T20:25:15: FIFO: stop "ZWO CCD ASI290MM Mini"@localhost:7627
> 2023-08-23T20:26:41: Driver ZWO CCD ASI290MM Mini@localhost:7627 -n ZWO CCD ASI290MM Mini@localhost:7627: read EOF
> <delProperty device="ZWO CCD ASI290MM Mini"/>
> 2023-08-23T20:26:41: Driver ZWO CCD ASI290MM Mini@localhost:7627 -n ZWO CCD ASI290MM Mini@localhost:7627: restart #0
> 2023-08-23T20:26:41: Driver ZWO CCD ASI290MM Mini@localhost:7627 -n ZWO CCD ASI290MM Mini@localhost:7627: connect(localhost,7627): Connection refused
> 2023-08-23T20:26:41: good bye
> 

**Expected behavior**

This behaviour in the last 4 lines is absolutely unexpected, I have no idea why it happens. It looks just like even though the remote driver is stopped from the master server, there is somehow still a connection ...
Hence the fact that master server (its actual client part) fails with connection issue later on when the slave server is stopped

In comparison, the same log without using indiwebmanager look like this:

> 2023-08-23T20:43:23: startup: indiserver -vvv -p 7624 -m 1000 -v -f /tmp/indiFIFO -u /tmp/indiFIFO_sock
> 2023-08-23T20:43:23: listening to port 7624 on fd 5
> 2023-08-23T20:43:23: Local server: listening on local domain at: @/tmp/indiFIFO_sock
> 2023-08-23T20:43:49: FIFO: start "ZWO CCD ASI290MM Mini"@localhost:7627
> 2023-08-23T20:43:49: FIFO: Starting driver ZWO CCD ASI290MM Mini@localhost:7627
> 2023-08-23T20:43:49: Driver ZWO CCD ASI290MM Mini@localhost:7627: socket=8
> 2023-08-23T20:43:49: Driver ZWO CCD ASI290MM Mini@localhost:7627: sending msg nq 1:
> <getProperties device="ZWO CCD ASI290MM Mini" version="1.7"/>
> 
> 2023-08-23T20:43:49: Driver ZWO CCD ASI290MM Mini@localhost:7627: read defSwitchVector ZWO CCD ASI290MM Mini CONNECTION Idle rw
>     CONNECT='Off'
>  DISCONNECT='On'
> 2023-08-23T20:43:49: Driver ZWO CCD ASI290MM Mini@localhost:7627: read defSwitchVector ZWO CCD ASI290MM Mini CONNECTION Idle rw
>     CONNECT='Off'
>  DISCONNECT='On'
> 2023-08-23T20:43:49: Driver ZWO CCD ASI290MM Mini@localhost:7627: read defTextVector ZWO CCD ASI290MM Mini DRIVER_INFO Idle ro
>  DRIVER_NAME='ZWO CCD'
>  DRIVER_EXEC='indi_asi_ccd'
>  DRIVER_VERSION='2.3'
>  DRIVER_INTERFACE='6'
> 2023-08-23T20:43:49: Driver ZWO CCD ASI290MM Mini@localhost:7627: read defTextVector ZWO CCD ASI290MM Mini DRIVER_INFO Idle ro
>  DRIVER_NAME='ZWO CCD'
>  DRIVER_EXEC='indi_asi_ccd'
>  DRIVER_VERSION='2.3'
>  DRIVER_INTERFACE='6'
> 2023-08-23T20:43:49: Driver ZWO CCD ASI290MM Mini@localhost:7627: read defNumberVector ZWO CCD ASI290MM Mini POLLING_PERIOD Idle rw
>   PERIOD_MS='1000'
> 2023-08-23T20:43:49: Driver ZWO CCD ASI290MM Mini@localhost:7627: read defNumberVector ZWO CCD ASI290MM Mini POLLING_PERIOD Idle rw
>   PERIOD_MS='1000'
> 2023-08-23T20:43:49: Driver ZWO CCD ASI290MM Mini@localhost:7627: read defSwitchVector ZWO CCD ASI290MM Mini DEBUG Idle rw
>      ENABLE='Off'
>     DISABLE='On'
> 2023-08-23T20:43:49: Driver ZWO CCD ASI290MM Mini@localhost:7627: read defSwitchVector ZWO CCD ASI290MM Mini DEBUG Idle rw
>      ENABLE='Off'
>     DISABLE='On'
> 2023-08-23T20:43:49: Driver ZWO CCD ASI290MM Mini@localhost:7627: read defSwitchVector ZWO CCD ASI290MM Mini SIMULATION Idle rw
>      ENABLE='Off'
>     DISABLE='On'
> 2023-08-23T20:43:49: Driver ZWO CCD ASI290MM Mini@localhost:7627: read defSwitchVector ZWO CCD ASI290MM Mini SIMULATION Idle rw
>      ENABLE='Off'
>     DISABLE='On'
> 2023-08-23T20:43:49: Driver ZWO CCD ASI290MM Mini@localhost:7627: read defSwitchVector ZWO CCD ASI290MM Mini CONFIG_PROCESS Idle rw
>  CONFIG_LOAD='Off'
>  CONFIG_SAVE='Off'
>  CONFIG_DEFAULT='Off'
>  CONFIG_PURGE='Off'
> 2023-08-23T20:43:49: Driver ZWO CCD ASI290MM Mini@localhost:7627: read defSwitchVector ZWO CCD ASI290MM Mini CONFIG_PROCESS Idle rw
>  CONFIG_LOAD='Off'
>  CONFIG_SAVE='Off'
>  CONFIG_DEFAULT='Off'
>  CONFIG_PURGE='Off'
> 2023-08-23T20:43:49: Driver ZWO CCD ASI290MM Mini@localhost:7627: read defTextVector ZWO CCD ASI290MM Mini ACTIVE_DEVICES Idle rw
>  ACTIVE_TELESCOPE='Telescope Simulator'
>  ACTIVE_ROTATOR='Rotator Simulator'
>  ACTIVE_FOCUSER='Focuser Simulator'
>  ACTIVE_FILTER='CCD Simulator'
>  ACTIVE_SKYQUALITY='SQM'
> 2023-08-23T20:43:49: Driver ZWO CCD ASI290MM Mini@localhost:7627: read defTextVector ZWO CCD ASI290MM Mini ACTIVE_DEVICES Idle rw
>  ACTIVE_TELESCOPE='Telescope Simulator'
>  ACTIVE_ROTATOR='Rotator Simulator'
>  ACTIVE_FOCUSER='Focuser Simulator'
>  ACTIVE_FILTER='CCD Simulator'
>  ACTIVE_SKYQUALITY='SQM'
> 2023-08-23T20:43:49: Driver ZWO CCD ASI290MM Mini@localhost:7627: read defTextVector ZWO CCD ASI290MM Mini ACTIVE_DEVICES Idle rw
>  ACTIVE_TELESCOPE='Telescope Simulator'
>  ACTIVE_ROTATOR='Rotator Simulator'
>  ACTIVE_FOCUSER='Focuser Simulator'
>  ACTIVE_FILTER='CCD Simulator'
>  ACTIVE_SKYQUALITY='SQM'
> 2023-08-23T20:43:49: Driver ZWO CCD ASI290MM Mini@localhost:7627: read defTextVector ZWO CCD ASI290MM Mini ACTIVE_DEVICES Idle rw
>  ACTIVE_TELESCOPE='Telescope Simulator'
>  ACTIVE_ROTATOR='Rotator Simulator'
>  ACTIVE_FOCUSER='Focuser Simulator'
>  ACTIVE_FILTER='CCD Simulator'
>  ACTIVE_SKYQUALITY='SQM'
> 2023-08-23T20:44:08: FIFO: stop "ZWO CCD ASI290MM Mini"@localhost:7627
> 2023-08-23T20:44:08: FIFO: Shutting down driver: ZWO CCD ASI290MM Mini@localhost:7627
> <delProperty device="ZWO CCD ASI290MM Mini"/>
> 

**Desktop (please complete the following information):**
ubuntu 22.04 
indi 2.0.3
custom webmanager version but I don't think it is related

**Comment by gnthibault** [comment]
EDIT: it seems that the only difference is within the "-n" option passed into the FIFO.
Can someone point me to the why is this option playing a role in there ?
I might simply remove it from my version of indiwebmanage if that fixes the problem (will test tomorrow).

Thank you in advance for your help

Best regards

**Comment by gnthibault** [comment]
Ok I managed to confirm that the -n option in the FIFO command was the key to this issue, but I still do not understand the rationale behind this behaviour (haven't checked yet the source code).
For me this is definitely a bug, but I let someone else judge, maybe @knro  

The correct version to reproduce the bug is the following:
```
# start master server
indiserver -vvv -p 7624 -m 1000 -v -f /tmp/indiFIFO -u /tmp/indiFIFO_sock > /tmp/indiserver.log 2>&1
# start slave server
indiserver -vvv -p 7627 -m 1000 -v -f /tmp/indiFIFO_guiding_camera -u /tmp/indiFIFO_guiding_camera_sock > /tmp/indiserver2.log 2>&1
# start slave driver
echo "start indi_simulator_guide " > /tmp/indiFIFO_guiding_camera
# Start master link
echo "start \"Guide Simulator\"@localhost:7627 -n \"Guide Simulator\"@localhost:7627" > /tmp/indiFIFO
# Stop slave driver
echo "stop \"Guide Simulator\"@localhost:7627" > /tmp/indiFIFO

# ps -lA | grep indiserver and get the last PID that should be the slave pid
kill -9 SLAVE_PID
```

#Now you should see that both server are actually stopped

Instead if you replace the following line:
`echo "stop \"Guide Simulator\"@localhost:7627" > /tmp/indiFIFO
`By the "named" version:
`echo "stop \"Guide Simulator\"@localhost:7627 -n \"Guide Simulator\"@localhost:7627" > /tmp/indiFIFO`
You get back a proper and clean stop

**Comment by knro** [comment]
As per the [documentation](https://docs.indilib.org/indiserver/), the **-n** parameter is to set the label for the driver. So why is the @localhost:7627 appended to the driver label?

**Comment by gnthibault** [comment]
> As per the [documentation](https://docs.indilib.org/indiserver/), the **-n** parameter is to set the label for the driver. So why is the @localhost:7627 appended to the driver label?

From what I understand, label can be arbitrary string, and I used that specific example with @localhost:7627 simply because that was the default in indiwebmanager : https://github.com/knro/indiwebmanager/blob/ad69a0c83686fa812fd20375e6809c3399318748/indiweb/main.py#L105
I can test later-on today wether it makes a difference to use a label with a short/simpler string
