### ISSUE TITLE
Bypass saving to local when DSLR SD-Card is the target

### ISSUE THREAD

**Issue by FalCT60** [indilib/indi#1929]
When selecting DSLR SD-card as destination, the files are also loaded to the local media.
This is a waste of time. 

In such case, saving to local media ought to be disabled / bypassed, thus shortening the delays between takes.
Attached is a screenshot of the settings.
![3-NikonIndi3](https://github.com/indilib/indi/assets/49912948/22633f02-f703-405d-82f2-1837bac46569)

**Comment by knro** [comment]
IIRC, there is an "Ignore" setting in Image Settings.
