### ISSUE TITLE
Feature request: Aperture/focus length per profile

### ISSUE THREAD

**Issue by kecsap** [indilib/indi#193]
I use my Skywatcher Virtuoso mount with different configurations and I would like to have different profiles when:
1. I use standalone DSLR and guide scope with CCD
2. I use telescope with DSLR and guide scope with CCD.
3. I use telescope with CCD.

Currently, the entered aperture/focus length parameters are static per driver. If I set a certain aperture and focus length for a profile and I switch to an other profile, these parameters remain the same. These parameters are crucial for plate solving.

**Comment by knro** [comment]
While this is interesting, it doesn't belong to INDI, it's an Ekos issue. For any Ekos issues, please use bugs.kde.org

I will look into it.
