### ISSUE TITLE
Dome slaving doesn't work anymore using driver MaxDome II, indi_maxdomeii version 1.4

### ISSUE THREAD

**Issue by jcj2249** [indilib/indi#1974]
**Describe the bug**
I am using KStars to pilot my astro setup (including a dome Sirius)
Since KStars 3.6.7, the dome is not slaved anymore to the scope.
I reported this bug to the KStars forum, but I was told it was a INDI bug -  not a KStars bug.

**To Reproduce**
Exact steps to reproduce the behavior.
1. Connect the set up and move the scope to a target
2. Enable the slaving of the dome
3. The dome doesn't move

**Expected behavior**
The dome should rotate

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS 11.7.4

**Log Files**
Make sure to enable logging and include log files https://indilib.org/support/logs-submission.html

**Comment by knro** [comment]
Can you check in the dome if the telescope is set to your mount driver? I think this might be the cause.
