### ISSUE TITLE
Wrong filenaming when using %C placeholder

### ISSUE THREAD

**Issue by FalCT60** [indilib/indi#1979]
**Describe the bug**
%C placeholder leads to wrong filenames in distant mode

**To Reproduce**
Exact steps to reproduce the behavior.
1. set profile to Distant
2. set capture mode to remote
3. set /%C_%G_%D as placeholders

**Expected behavior**
Files ought to be named upon temperature, gain and date (+sequence), so in my case 20_120_2023-12-17T21-12-25.223_001.fits for a shot taken at 20°C, gain=120, aso.
Unfortunately, the actual file nam is -?\d+_120_2023-12-17T21-12-25.223_001.fits

**Screenshots**
![EkosTempWrong](https://github.com/indilib/indi/assets/49912948/0ba9face-8383-4d1d-9e07-8792ffb96cf5)

**Desktop (please complete the following information):**
 - OS: SMOS 1.8.0
 - RPi 5

**Comment by knro** [comment]
This is an Ekos issue, not INDI.
