### ISSUE TITLE
Pegasus PPBA/M missing auto dew aggressiveness setting

### ISSUE THREAD

**Issue by ijessen** [indilib/indi#1992]
**Describe the bug**
The PPBA/PPBM driver doesn't handle the auto dew "aggressiveness" setting.  It looks like support was added for this parameter in a later serial protocol update (Jan 2021), [see here](https://pegasusastro.com//wp-content/uploads/2022/05/Pocket_Powerbox_Advance_Serial_Command_Table.pdf).

**Comment by knro** [comment]
Thank you for the report. Do you think you can work on a PR for this?

**Comment by ijessen** [comment]
Yep - am planning to

**Comment by ijessen** [comment]
I started on this but my PPBM doesn't seem to respond to the aggressiveness commands like the documentation says it should.  I have a request in to Pegasus for info.

![image](https://github.com/indilib/indi/assets/2163199/c36201f1-b518-4275-9471-d4522bfad810)

**Comment by ijessen** [comment]
Pegasus support finally responded that they will update their documentation at some point, hopefully soon
