### ISSUE TITLE
Sesto Senso 2 Bug on TimerHit breaking AF Overscan in Ekos Focus

### ISSUE THREAD

**Issue by johneevans** [indilib/indi#1995]
**Describe the bug**
In investigating a problem with AF Overscan in Kstars Focus, the movement of the focuser is incorrect. See this forum thread for more details...
https://indilib.org/forum/focusers-filter-wheels/14322-re-kstars-3-6-9-af-overscan-not-working-correctly.html#99023

AF Overscan adds X ticks to an outward focuser movement. Waits for the focuser to complete its movement, then commands an inward movement of X ticks.

For example, if focuser is at 2000 and a request to move out by 88 ticks with Overscan=100 is received, the focuser will...
1. Move out to:  2000 + 88 + 100 = 2188.
2. When move completes move to: 2188 - 100 = 2088
What actually happens is the focuser moves to 1900.

I believe what is happening is that the initial outward movement is started correctly towards 2188. Then the TimerHit() function is called. It calls updatePosition and on line 334:
FocusAbsPosNP.s = IPS_OK;

Setting status to OK is, I believe, incorrect as this is I think reported to Ekos as IPS_OK which  implies the focuser movement has completed which isn't the case. Ekos then commands a move to the last known position - 100 = 1900 

If line 334 is set to
FocusAbsPosNP.s = IPS_BUSY;
then this should fix the problem and also supply intermediate position update to Ekos::Focus which don't appear to be happening currently.

**To Reproduce**
As described in the above example.

**Expected behavior**
As described in the above example.

**Screenshots**
See link to forum thread

**Desktop (please complete the following information):**
 - OS: all
 - Version [3.6.9 and previous I suspect]

**Log Files**
See link to forum thread.

**Comment by Ryther** [comment]
Hi, I'm trying to help @johneevans by doing the testing, since I own the focuser. If it's needed, I can eventually try the fixes made to the drivers.

My bits of info for this problem:
- Issuing movements too fast, even as separated commands, result in the same error
- There is no update on focuser position while in motion
