### ISSUE TITLE
Change french translation for "Pier Side"

### ISSUE THREAD

**Issue by FalCT60** [indilib/indi#2013]
Hello,
The french translation for _Pier Side_ may be subject of confusion for non-experienced users - and maybe not only them.
Of course, the first meaning of pier in french can be _jetée_ ou _ponton_, but this is there totally irrelevant and erroneous.
It happens that one other meaning of _pier_, in french, is _pilier_ (_nm._ same as english _pillar_), and that then takes more sense as it is what supports the mount: _un pilier de béton_ - _a concrete pillar/pier_.
Other possible translations could be _colonne_ (_nf._) or _pied_ (_nm._).
Hope to see it in next release.
Rgrds,

**Comment by knro** [comment]
There is no translation in INDI. You need to check with KDE's French translation team.
