### ISSUE TITLE
Telescope properties are missing on version 2.0.6

### ISSUE THREAD

**Issue by plop3** [indilib/indi#2033]
On telescope/options tab, the telescope properties are missing in version 2.0.6.
I don't know if the versions 2.0.4 and 2.0.5 are the same problem.
I cannot enter focal/aperture values (no fileds are presents)
I have compiled the version 2.0.3 and it's work fine. Telescope properties are present in Telescope/Options

    OS: Ubuntu 22.04
    Driver: EQModMount
    Indi version 2.0.6

**Comment by aaronwmorris** [comment]
Just copying my comments from the forum...

I believe this was intentional.

The aperture and focal length settings were removed from the Telescope/Mount properties in favor of the same settings under the Camera.
