### ISSUE TITLE
Usability Request - Scheduler

### ISSUE THREAD

**Issue by stevecoh1** [indilib/indi#2108]
**Is your feature request related to a problem? Please describe.**
I was using Ekos to schedule a job to run in the future.  I used the CCD module to create the sequence. Then I used the scheduler module to schedule a job.  Everything looked good and I wanted to save it.  For several minutes I could not get Ekos to accept the job into the queue.  I was pounding my head trying to figure what the problem was.  Was it another WiFi connectivity issue? No.  Was it something wrong with my inputs?  It all looked good.  Then it occurred to me: I had typed in my target as "M32". It should have been "M 32". Making that change, allowed the job to be added to queue and saved.

**Describe the solution you'd like**
An error message!  This is like an online form that won't let you continue unless you get all the inputs right.  Such forms ALWAYS show an error message like "Invalid Credit Card Expiration Date" or something.  In this case, it could be "Target unknown" or something of that sort.  Since it is not infrequent to have connectivity issues it would be nice to know that Ekos has received my request and found it wanting, rather than a connectivity issue.

**Describe alternatives you've considered**

**Additional context**
![Screenshot from 2024-09-07 11-45-36](https://github.com/user-attachments/assets/d567b9d0-0bc5-4dbd-9f38-735f2bff02e9)

**Comment by knro** [comment]
This is not an INDI issue.

Nevertheless, if you used the Find Dialog to select the tool, then the coordinates fields would be automatically filled. Your issue is not the name, it's that there are no J2000 RA/DE specified.

**Comment by stevecoh1** [comment]
Sorry, but I disagree.  Yes, I know it was my mistake not picking from the list.  But the interface does allow manual entry of the target, and if the user does so and enters it wrong, he deserves an error message, not a silent failure.  Silent failures are bad UI.

**Comment by knro** [comment]
You can enter manually, but then you'd also have to enter the RA/DE manually as well.

**Comment by stevecoh1** [comment]
OK, but you're missing my point: "Silent failures are bad UI".  If program lets the user do something and it's the wrong thing, he shouldn't need to scratch his head and say "WTF is wrong now?"  The higher you make learning curves, the more likely it is that users will give up or find a product that works better.
