### ISSUE TITLE
usePulseCommand out of sync in lx200ap_v2

### ISSUE THREAD

**Issue by munkacsymj** [indilib/indi#2110]
The member variable usePulseCommand (as used in lx200ap_v2.cpp) is initialized to false in lx200telescope.h. The property "Use Pulse Cmd" is initialized to "On" in lx200telescope.cpp. If a client does not change the value of the "Use Pulse Cmd" property, the client will see the property turned "On" but will have Pulse Guiding commands silently ignored by the lx200ap_v2 driver because usePulseCommand is false. 

As a workaround, the client can set the "Use Pulse Cmd" property to "On", _even though it is already on._ This causes the variable and the property to become synchronized in the driver and everything will work fine until the next time the driver starts.

Either the variable should be initialized to true and/or the variable and the property should be explicitly synchronized to each other when the property is defined and initialized by the driver.

**Comment by knro** [comment]
That's an excellent catch! It's odd it took this long to discover. We should be migrating this driver to the new INDI Property system soon which hopefully would avoid such issues. Great investigation!
