### ISSUE TITLE
Telescope Simulator custom track rate only updates when track mode is changed

### ISSUE THREAD

**Issue by PeterS-mBryonics** [indilib/indi#2128]
**Describe the bug**
Using the telescope simulator, updating the custom tracking rates only occurs when the track mode is changed (for example custom -> sidereal -> custom), rather than on set of new tracking rates. Edit: This doesn't occur when releases prior to and including 2.0.9 are used

**To Reproduce**
1. Run driver indi_simulator_telescope
2. Set track mode to "Custom"
3. Change track rates ra/dec to 5000, 5000
4. Set track rates
5. (No change in tracking rate)
6. Change Track Mode to "Sidereal" and then back to "Custom"
7. Observe motion of telescope

**Expected behavior**
When a custom track rate is set, the rate is immediately applied

**Desktop (please complete the following information):**
 - OS: WSL Ubuntu 22.04
 - Version: Release 2.1.0 and latest git

**Log Files**
(also can't add log files because the driver turns debug off after it's turned on)

Excuse all the edits, realised I wasn't clearing out the build folder properly so I wasn't checking the right version. I've tested 2.0.7 up to 2.1.0 and the latest git now.

**Comment by knro** [comment]
This is already fixed in master. Can you please check now?

**Comment by PeterS-mBryonics** [comment]
Thanks, cleaned out my copy and re-fetched the main branch, and recompiled etc. It has the same behaviour as before

**Comment by knro** [comment]
This was not enough.. during the migration to INDI new style properties a regression was introduced. Hopefully it's fixed now, please recompile from master and try

**Comment by PeterS-mBryonics** [comment]
Fab, that got it! Cheers.
