### ISSUE TITLE
Just purchased new ZWO AM5N Mount.  INDI won't connect to it.

### ISSUE THREAD

**Issue by stevecoh1** [indilib/indi#2148]
**Describe the bug**
I just purchased a brand new ZWO AM5N (2024 version) mount.  My Stellarmate Pro won't connect to it.

**To Reproduce**
Exact steps to reproduce the behavior.
1. Obtain mount and connect it to Stellarmate Pro using the USB port
2. Create a Profile using the AM5 USB driver 
3. Try to start it.  Connection fails. Log complains that /dev/ttyUSB0 does not exist, which is indeed the case.  Config file generated for me by INDI mentions /dev/ttyUSB0.  

**Expected behavior**
I expected a connection to be made

**Screenshots**
Screenshot showing config file and lsusb output

**Desktop (please complete the following information):**
 - OS: Stellarmate 1.8.5

 - Version 1.8.5

**Log Files**
Log was sent to Stellarmate, Issue see #1000

**Comment by knro** [comment]
Scan ports and it should be detected. Use the Port Selector tool. I literally connected to a new AMN5 yesterday with SM Pro without any issues.

**Comment by stevecoh1** [comment]
Thanks, Jasem.
I'm unfamiliar with that tool since I've only used Celestron AVX up until now.
I guess you mean [this](https://www.stellarmate.com/help/PortSelector.html).
I also see [this, making use of the Bluetooth capabilities of the mount](https://www.stellarmate.com/help/SerialPortAssistantBluetoothWiza.html), which sounds intriguing because of one less cable, maybe.  
Would one be better than the other?

**Comment by knro** [comment]
Yes, port selector. I think bluetooth is not working reliably, we're working on improving that.

**Comment by stevecoh1** [comment]
It worked.  That was easy enough. thanks.
