### ISSUE TITLE
indi-gpsd has improper DST offset

### ISSUE THREAD

**Issue by xsnrg** [indilib/indi#228]
Discussion: http://www.indilib.org/forum/general/2004-help-with-gpsd.html?start=12#16787

timedatectl returns the proper system settings and DST offset.  indi-gpsd performs a check against the current timezone and changes the offset when it does not need to.  This might be needed on other systems?  On Linux it is handled and the math should not be performed.

    // adjust offset for DST
    if (local->tm_isdst)
        offset -= 1;

credit to:jpaana

**Comment by knro** [comment]
@jochym What do you think?

**Comment by jochym** [comment]
He is right. We are correcting for DST twice. (!) 
I'll prepare PR in few moments.

**Comment by xsnrg** [comment]
Thank you @knro and @jochym

**Comment by xsnrg** [comment]
Confirmed fixed with #229
