### ISSUE TITLE
indi-tess does not compile

### ISSUE THREAD

**Issue by lupinix** [indilib/indi#26]
indi-tess does not compile since last changes (duconfig.h not found which was in indi-tess ealier), I get the following error message (Fedora 22, 23, 24):

> [  117s] + make -j8
> [  117s] /usr/bin/cmake -H/home/abuild/rpmbuild/BUILD/indi-tess-1.2.0.gite89c98ca -B/home/abuild/rpmbuild/BUILD/indi-tess-1.2.0.gite89c98ca --check-build-system CMakeFiles/Makefile.cmake 0
> [  117s] /usr/bin/cmake -E cmake_progress_start /home/abuild/rpmbuild/BUILD/indi-tess-1.2.0.gite89c98ca/CMakeFiles /home/abuild/rpmbuild/BUILD/indi-tess-1.2.0.gite89c98ca/CMakeFiles/progress.marks
> [  117s] make -f CMakeFiles/Makefile2 all
> [  117s] make[1]: Entering directory '/home/abuild/rpmbuild/BUILD/indi-tess-1.2.0.gite89c98ca'
> [  117s] make -f CMakeFiles/indi_tess.dir/build.make CMakeFiles/indi_tess.dir/depend
> [  117s] make[2]: Entering directory '/home/abuild/rpmbuild/BUILD/indi-tess-1.2.0.gite89c98ca'
> [  117s] cd /home/abuild/rpmbuild/BUILD/indi-tess-1.2.0.gite89c98ca && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/abuild/rpmbuild/BUILD/indi-tess-1.2.0.gite89c98ca /home/abuild/rpmbuild/BUILD/indi-tess-1.2.0.gite89c98ca /home/abuild/rpmbuild/BUILD/indi-tess-1.2.0.gite89c98ca /home/abuild/rpmbuild/BUILD/indi-tess-1.2.0.gite89c98ca /home/abuild/rpmbuild/BUILD/indi-tess-1.2.0.gite89c98ca/CMakeFiles/indi_tess.dir/DependInfo.cmake --color=
> [  117s] Scanning dependencies of target indi_tess
> [  117s] make[2]: Leaving directory '/home/abuild/rpmbuild/BUILD/indi-tess-1.2.0.gite89c98ca'
> [  117s] make -f CMakeFiles/indi_tess.dir/build.make CMakeFiles/indi_tess.dir/build
> [  117s] make[2]: Entering directory '/home/abuild/rpmbuild/BUILD/indi-tess-1.2.0.gite89c98ca'
> [  117s] [ 33%] Building CXX object CMakeFiles/indi_tess.dir/tess.o
> [  117s] /usr/bin/c++    -I/home/abuild/rpmbuild/BUILD/indi-tess-1.2.0.gite89c98ca -I/usr/include/libindi -I/usr/include/libnova  -std=c++0x -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic    -o CMakeFiles/indi_tess.dir/tess.o -c /home/abuild/rpmbuild/BUILD/indi-tess-1.2.0.gite89c98ca/tess.cpp
> [  117s] [ 66%] Building CXX object CMakeFiles/indi_tess.dir/tess_algebra.o
> [  117s] /usr/bin/c++    -I/home/abuild/rpmbuild/BUILD/indi-tess-1.2.0.gite89c98ca -I/usr/include/libindi -I/usr/include/libnova  -std=c++0x -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic    -o CMakeFiles/indi_tess.dir/tess_algebra.o -c /home/abuild/rpmbuild/BUILD/indi-tess-1.2.0.gite89c98ca/tess_algebra.cpp
> [  117s] /home/abuild/rpmbuild/BUILD/indi-tess-1.2.0.gite89c98ca/tess.cpp:37:22: fatal error: duconfig.h: No such file or directory
> [  117s]  #include <duconfig.h>
> [  117s]                       ^
> [  117s] compilation terminated.
> [  117s] CMakeFiles/indi_tess.dir/build.make:65: recipe for target 'CMakeFiles/indi_tess.dir/tess.o' failed
> [  117s] make[2]: *** [CMakeFiles/indi_tess.dir/tess.o] Error 1
> [  117s] make[2]: *** Waiting for unfinished jobs....
> [  117s] /home/abuild/rpmbuild/BUILD/indi-tess-1.2.0.gite89c98ca/tess_algebra.cpp: In function 'int get_heading(const vector*, const vector*, const vector*, vector*)':
> [  117s] /home/abuild/rpmbuild/BUILD/indi-tess-1.2.0.gite89c98ca/tess_algebra.cpp:84:16: warning: 'pitch' may be used uninitialized in this function [-Wmaybe-uninitialized]
> [  117s]    pitch = pitch*180/M_PI;
> [  117s]            ~~~~~^~~~
> [  117s] /home/abuild/rpmbuild/BUILD/indi-tess-1.2.0.gite89c98ca/tess_algebra.cpp:78:14: warning: 'roll' may be used uninitialized in this function [-Wmaybe-uninitialized]
> [  117s]    roll = roll*180/M_PI;
> [  117s]           ~~~~^~~~
> [  117s] make[2]: Leaving directory '/home/abuild/rpmbuild/BUILD/indi-tess-1.2.0.gite89c98ca'
> [  117s] CMakeFiles/Makefile2:70: recipe for target 'CMakeFiles/indi_tess.dir/all' failed
> [  117s] make[1]: *** [CMakeFiles/indi_tess.dir/all] Error 2
> [  117s] make[1]: Leaving directory '/home/abuild/rpmbuild/BUILD/indi-tess-1.2.0.gite89c98ca'
> [  117s] Makefile:130: recipe for target 'all' failed
> [  117s] make: *** [all] Error 2
> [  117s] error: Bad exit status from /var/tmp/rpm-tmp.3iHUBU (%build)

**Comment by knro** [comment]
Thanks for the report. Fixed.
