### ISSUE TITLE
Selection of Mount Control causes Kstars/Ekos to abort

### ISSUE THREAD

**Issue by phomer60** [indilib/indi#293]
Running Ubuntu Mate on Raspberry Pi 3 and mount is Losmandy Gemini.
When restarting Ekos the INDI servers are still running.
![screen sharing picture 08 july 2017 at 11 16 45 am aest](https://user-images.githubusercontent.com/20377751/27991507-93c376dc-64bc-11e7-81c1-7c3133aaa300.png)
![mountcontrolabort](https://user-images.githubusercontent.com/20377751/27991512-ad2b04dc-64bc-11e7-845e-9241cbb4e9b7.png)
![serverrunning](https://user-images.githubusercontent.com/20377751/27991517-d02be672-64bc-11e7-9802-a1c01df9c527.png)

**Comment by knro** [comment]
Please try PPA build from tomorrow and report if it works.

**Comment by phomer60** [comment]
Tried again today and no difference I can see, it is still aborting completely out of kstars / ekos.

**Comment by phomer60** [comment]
I have even tried this using the simulators and it fails, aborting back to the Unix shell.

**Comment by knro** [comment]
That's usually an indication of missing QML files. Try running kstars from the console and check the error when it exists. It will probably complain about a missing QML module not being installed properly.

**Comment by phomer60** [comment]
I always run kstars from a console via VNC as shown above. I tried running it with a keyboard and monitor and it works. The only error I see is libEGL warning: DRI2: failed to authenticate.

When running through VNC it is now showing as per the attached image.
![screen sharing picture 18 july 2017 at 9 29 13 pm aest](https://user-images.githubusercontent.com/20377751/28315229-e7242aec-6c00-11e7-9fda-997a65eda3a4.png)

**Comment by knro** [comment]
Closing since not INDI bug.
