### ISSUE TITLE
Image Transfer is disabled for this camera message.

### ISSUE THREAD

**Issue by phomer60** [indilib/indi#294]
This is happening each time Ekos is started and I try to use the camera.
Running Ubuntu Mate on Raspberry Pi 3 with QSI 583.
Workaround is to go into Image Info untick 'INDI DATA STREAM' tick box and then tick it again.
![imagetransfer](https://user-images.githubusercontent.com/20377751/27991533-5f1fb3a4-64bd-11e7-80f2-f4c3df6658fa.png)

**Comment by knro** [comment]
This is due to using exernal guide app. At any rate, it's fixed in the latest KStars GIT.
