### ISSUE TITLE
Mount dialogue box has inconsistent use of colons.

### ISSUE THREAD

**Issue by phomer60** [indilib/indi#295]
Aperture, RA, DEC, Az, Alt, HA, Min/Max Alt append a colon to the text.
Focal Length, and LST do not.
Personally, I prefer them without the colons but they should be consistent.
![mountcontrol](https://user-images.githubusercontent.com/20377751/27991573-630261f0-64be-11e7-8701-8d38fad541b7.png)

**Comment by knro** [comment]
This not not an INDI issue, please file KStars bugs at bugs.kde.org
