### ISSUE TITLE
Qsi CCD filter wheel adding name to filter.

### ISSUE THREAD

**Issue by joe090** [indilib/indi#320]
Qsi filter wheel was working on all levels before doing a  upgrade. After upgrade unable to add a name to individual filters. Qsi CCD device, device crashes after pressing set to add name. Iam running 16.04 also tested on 17.04 and Ubuntu mate for raspberry pi 3 does the same.

**Comment by knro** [comment]
Issue fixed, check PPA tomorrow.

**Comment by knro** [comment]
I'll close this, re-open if you have issue again.
