### ISSUE TITLE
Missing cmake modules in release 1.5.0

### ISSUE THREAD

**Issue by mattiaverga** [indilib/indi#380]
The provided libindi_1.5.0.tar.gz does not include cmake modules. Is this intended?

**Comment by knro** [comment]
no, I guess it got omitted. Are you a package maintainer?

**Comment by mattiaverga** [comment]
Not at the moment, but I tried to build an updated rpm locally and I found that directory missing. 
I would like to help maintaining indi package in Fedora.

**Comment by knro** [comment]
This shall be fixed in the next release in December/January.
