### ISSUE TITLE
Camera simulator has a filter named 'Luminosity'

### ISSUE THREAD

**Issue by phomer60** [indilib/indi#401]
Luminosity is a measure of brightness, I believe it was intended to name this filter 'Luminance'.
![screen sharing picture 24 october 2017 at 12 35 34 pm aedt](https://user-images.githubusercontent.com/20377751/31921037-3c5cb0d2-b8b0-11e7-9fb4-9105e9957991.png)

**Comment by knro** [comment]
Just fixed in master, thanks!
