### ISSUE TITLE
Install indi problem

### ISSUE THREAD

**Issue by Andreaweb80** [indilib/indi#443]
Hello, today i have a problem...
I've always installed all the indi lib and kstars with the following command:
sudo apt-add-repository ppa:mutlaqja/ppa
sudo apt-get install indi-full
sudo apt-get install indi-full kstars-bleeding

But today it response with an error:
I seguenti pacchetti hanno dipendenze non soddisfatte:
 indi-full : Dipende: libindi1 (>= 1.2) ma non sta per essere installato
             Dipende: libindi-dev (>= 1.2) ma non sta per essere installato
             Dipende: indi-bin (>= 1.2) ma non sta per essere installato
             Dipende: indi-eqmod ma non sta per essere installato
             Dipende: indi-sx ma non sta per essere installato
             Dipende: indi-sbig ma non sta per essere installato
             Dipende: indi-apogee ma non sta per essere installato
             Dipende: indi-gphoto ma non sta per essere installato
             Dipende: indi-qsi ma non sta per essere installato
             Dipende: indi-fishcamp ma non sta per essere installato
             Dipende: indi-maxdomeii ma non sta per essere installato
             Dipende: indi-asi ma non sta per essere installato
             Dipende: indi-aagcloudwatcher ma non sta per essere installato
             Dipende: indi-ffmv ma non sta per essere installato
             Dipende: indi-dsi ma non sta per essere installato
             Dipende: indi-qhy ma non sta per essere installato
             Dipende: indi-gpsd ma non sta per essere installato
             Dipende: indi-mi ma non sta per essere installato
             Dipende: indi-duino ma non sta per essere installato
             Dipende: indi-fli ma non sta per essere installato
             Dipende: indi-nexstarevo ma non sta per essere installato
             Dipende: indi-nexdome ma non sta per essere installato
             Dipende: indi-gpsnmea ma non sta per essere installato
E: Impossibile correggere i problemi, ci sono pacchetti danneggiati bloccati.

Seems a problem with the repo, but i don't know why...
Can someone help me?

**Comment by MPaskin** [comment]
I have the same problem, only in English!

**Comment by Andreaweb80** [comment]
So do you think it can be a repo problem?

**Comment by MPaskin** [comment]
It's always worked before, so I think something has changed.

**Comment by jochym** [comment]
Please, switch the report to english - this is the language the developers communicate.

**Comment by knro** [comment]
Launchpad, which is used to build the PPA, was having technical problems yesterday. It appears today it is back again.
