### ISSUE TITLE
Could not find a package configuration file provided by "INDI" in Archlinux

### ISSUE THREAD

**Issue by JiangXL** [indilib/indi#453]
Hi! 
When I try to build and install QHYCCD driver to  INDI,  below error occurred. 
``` bash 
$ cmake -L
Could not find a package configuration file provided by "INDI" with any of
  the following names:
    INDIConfig.cmake
    indi-config.cmake
  Add the installation prefix of "INDI" to CMAKE_PREFIX_PATH or set
  "INDI_DIR" to a directory containing one of the above files.  If "INDI"
  provides a separate development package or SDK, be sure it has been
  installed.
```
INDI is install from binary package from Archlinu https://www.archlinux.org/packages/community/x86_64/libindi/files/.

Do it mean that INDI need to build from source to get  **INDIConfig.cmake** and 
**indi-config.cmake**.

Any idea is welcome!

**Comment by knro** [comment]
You need to have cmake_modules directories somewhere. Try to clone the source and build libindi, libqhy, and then indi-qhy driver (in that order).

**Comment by JiangXL** [comment]
It work!!!
Thanks, you are so nice :+1:
