### ISSUE TITLE
Locking filter when focussing is not working

### ISSUE THREAD

**Issue by phomer60** [indilib/indi#462]
When I lock the Luminance filter for focussing and I am imaging using a Ha filter and it does a focus run between images it it not changing the filter for the focus run. It ends up not having a star to focus on and attempts to focus on noise before sometimes thinking it is successful and other times giving up. Either way the rest of the night is lost.
![screen sharing picture 16 december 2017 at 10 54 40 am aedt](https://user-images.githubusercontent.com/20377751/34064755-be3b5c16-e24f-11e7-9fe7-fdc9bc51a87c.png)

**Comment by knro** [comment]
This is not an INDI Bug, it's KStars/Ekos. Please file those bugs over at bugs.kde.org

Notwithstanding that, this is already fixed in KStars 2.8.9 which is due out later today.

**Comment by phomer60** [comment]
Jasem,

Unless I am missing something on the INDI web site, it would probably be useful to have somewhere in the support area which describes which types of things are INDI, Ekos or Kstars as it may reduce the number of misdirected queries.

Regards

Paul

**Comment by knro** [comment]
Sure. I'll try to conjure something. Basically, if the _driver_ is not working then it is INDI. For anything else it's the client fault (in this case KStars).

**Comment by phomer60** [comment]
Jasem,

I am wondering if this bug fix has has actually been released, as it still seems to be occurring.

The kstars 2.8.9 build is showing as 2017-12-16T11:27:07Z

Regards

Paul

**Comment by knro** [comment]
Please file a bug at bugs.kde.org
