### ISSUE TITLE
Sync fails for Celestron Nexstar driver

### ISSUE THREAD

**Issue by nesos** [indilib/indi#473]
Hi everyone,

when calling a sync command, the Celestron Nexstar driver will only transmit the first half of the sync command. 
For example:  If the telescope shall sync to the zero coordinates for RA and DEC it will only transmit

`s00000000,`

instead of

`s00000000,00000000`

The DEC coordinate is missing, causing a timeout on the hand controller.
I am using the latest version from the mutlaqja ppa.

Best regards, Ben

**Comment by nesos** [comment]
I think I found the problem and fixed it in the merge request #474

**Comment by knro** [comment]
Fix is merged.
