### ISSUE TITLE
indi_qhy_ccd crashed, Symbol not found - macOS Kstars

### ISSUE THREAD

**Issue by RelicsRage** [indilib/indi#490]
System: macOS HighSierra, version 10.13.2 MacPro Late 2013 - KStarts 2.8.9 *see attached log for details *

[log_09-37-45.txt](https://github.com/indilib/indi/files/1609039/log_09-37-45.txt)

System: VirtualBox, Kubuntu 17.04, Stars 2.8.9 - device mounted and works with no errors. Attached log file for CCD 

[log_09-58-25.txt](https://github.com/indilib/indi/files/1609040/log_09-58-25.txt)

**Comment by knro** [comment]
QHY CCD is updated and fixed. It should be available in the next KStars 2.9.0 release due in a few days.

**Comment by RelicsRage** [comment]
Thank you for the quick response.
