### ISSUE TITLE
libindi 1.6.1 release tarball misses cmake_modules

### ISSUE THREAD

**Issue by lupinix** [indilib/indi#493]
Hi,

the libindi_1.6.1.tar.gz is missing the cmake_modules directory, therefore cmake does not find the required libraries like cfitsio. In version 1.6.0 everything was fine with respect to cmake. Same for the 3rdparty tar file.

Greetings,
Christian

**Comment by knro** [comment]
You are right, in my rush to release this I forgot to include. Will make 1.6.2 now.
