### ISSUE TITLE
Installing INDI messes up package gvfs-backend

### ISSUE THREAD

**Issue by strongheart1** [indilib/indi#524]
On my system (Linux Mint 18.3 Cinnamon 64 bit ) I usually can connect my Canon EOS 50D and see it as storage device.  After installing INDI I could not see the camera anymore displayed as device.
Finally I found out that the 'gvfs-gphoto2-volume-monitor'  in /usr/lib/gvfs, which is a part of the package 'gvfs-backend', had been missing. 
Reinstallation of the package 'gvfs-backend' fixed the problem.

**Comment by knro** [comment]
This is done intentionally since it interferes with indi-gphoto operation.
