### ISSUE TITLE
indi_sx_ccd crash w/ PPA update 1.12~201802191336~ubuntu16.04.1

### ISSUE THREAD

**Issue by gschwim** [indilib/indi#526]
I updated from the PPA today and the subject matter crashes every time at the start of the server. Log attached. Rolling back to the branch fli_work and rebuilding indi-sx gets things working again.

[sx.txt](https://github.com/indilib/indi/files/1750402/sx.txt)

**Comment by knro** [comment]
PPA build problem, triggering a rebuild now.

**Comment by gschwim** [comment]
Confirmed the fix. Thx.
