### ISSUE TITLE
Main imaging camera listed as guide camera when using PHD

### ISSUE THREAD

**Issue by fmozza** [indilib/indi#534]
When PHD is chosen to provide guiding, the EKOS guider window shows the main imaging camera as the guiding camera.  Perhaps leave the value empty or indicate that PHD is providing the guiding services. 

Everthing works, but its confusing to see the imaging CCD listed as the guiding camera when isn't the guding camera.

**Comment by knro** [comment]
This is not an INDI issue, for KStars problems, report them to https://bugs.kde.org

Having said that, we are aware of the issue but did not want to introduce any changes at the moment as it might result in more unstability.

**Comment by fmozza** [comment]
thanks.  I'll report the bug there.

jmh
