### ISSUE TITLE
Possible problems on clang 6

### ISSUE THREAD

**Issue by jochym** [indilib/indi#542]
@knro:  I have noticed that the build fails on clang 6 (https://circleci.com/gh/jochym/indi/738) - the bionic default clang version changed recently. For now the build is forced to clang 5 on bionic (the docker image will be rebuild shortly) but I expect problems down the line on OSX. Maybe it would be better to fix it pro-actively? The problem seems to be in the indiccd.cpp file. Shell I prepare additional clang 6 build?

**Comment by knro** [comment]
I'll take a look at it thanks! I also asked Csaba to investigate this as he knows a lot more about this than I do.

**Comment by knro** [comment]
Ok virtual destructor added now.

**Comment by jochym** [comment]
What shell we do with the clang version? Default in bionic is 6 now. I have forced it to be still 5. Remind me why we are building with clang on linux? I know there was a rational reason but I cannot recall what was it.

**Comment by jochym** [comment]
@knro : do we need separate clang6 build ?

**Comment by knro** [comment]
I don't recall why we're building clang for Linux, maybe better warning/error reporting than the older GCC series? With gcc 8.x, it's on par with Clang now when it comes to warnings so there is no need for it IMO.

**Comment by jochym** [comment]
You mean all clang builds? That would speed up the CI considerably (by one cycle at least so 30%). Shell I drop all of them?

**Comment by knro** [comment]
Clang on Linux now required. I believe it is used for Mac, so there is that.

**Comment by jochym** [comment]
OK. Will do.
