### ISSUE TITLE
SynScan on macOS 10.13.4 not working

### ISSUE THREAD

**Issue by toxik** [indilib/indi#581]
Hello, 

I'm using KStars 2.9.4 and trying to connect to an SynScan EQ5 Pro via an USB to RS232 adapter (Prolific Technology, Inc.) connected to the handset.

I've tried both with and without PC Direct Mode but no luck, this is what I always get:
```
org.kde.kstars.indi: SynScan :  "[ERROR] Failed to connect to port (/dev/cu.usbserial). Error: Port failure Error: Resource busy. Check if device is connected to this port. "
```

The mount works nicely with EQMac v2.0.0 beta3 in PC Direct Mode with the same setup:
![image](https://user-images.githubusercontent.com/235319/39288770-0a7f0fa2-4932-11e8-8d9b-f5d73a99594c.png)

Any thoughts ?

**Comment by toxik** [comment]
I tried with the EQMod driver as well, I get the same "resource busy" error. Any way I could debug this further?

**Comment by knro** [comment]
Most likely then an issue with something holding the driver resources in Mac. Make sure everything is closed and nothing is using the serial port for anything.

**Comment by kecsap** [comment]
Is the device node the same in EQMac and KStars? /dev/cu.usbserial?

**Comment by toxik** [comment]
hmm not sure, this is what EQMac says:

![image](https://user-images.githubusercontent.com/235319/39322771-911336fe-4993-11e8-8058-fbedd098ba5b.png)

**Comment by toxik** [comment]
OK I just rebooted everything one more time, started all fresh and it worked with the SynScan driver.
Sorry for the wasted time !
