### ISSUE TITLE
Goto M101 is capturing and trying to solve as M102

### ISSUE THREAD

**Issue by Raddock** [indilib/indi#582]
Just use the mount control to go to M101. Then select capture and solve, and it trys to solve M102 and says the mount is way off.

<img width="989" alt="screen shot 2018-04-26 at 9 08 56 pm" src="https://user-images.githubusercontent.com/5283143/39340938-83e66f98-4996-11e8-8558-818d0bb111c5.png">

**Comment by knro** [comment]
This is a KStars issue, not INDI. Please file a bug report at https://bugs.kde.org
