### ISSUE TITLE
Update FLI driver version

### ISSUE THREAD

**Issue by lluiscanals** [indilib/indi#592]
We have recently tested version 1.3 of FLI driver for kernel version 4.13.X. It is unclear whether the CCD takes images or not (as the exposures seem to be taken and pixels are read), but the images were never saved. To solve this issue we had to download and use version 1.3.2 of FLI driver.

**Comment by knro** [comment]
The driver does not save the images, the client does. Which client were you using with the driver?

**Comment by knro** [comment]
FYI. The INDI driver does NOT use FLI kernel module any more.
