### ISSUE TITLE
Trivial Bug

### ISSUE THREAD

**Issue by Lagroxane** [indilib/indi#632]
But if no-one tells you, it won't get fixed.

I'm running os x 10.11.6

I started the download of the gsc and got a progress bar that was moving well.

The next time I looked the progress bar was gone but the dialogue still says "downloading GSC..."

I have a 100 Mb connection, so I'm pretty sure it's finished :)
[Wizard.tiff.pdf](https://github.com/indilib/indi/files/2150914/Wizard.tiff.pdf)

**Comment by knro** [comment]
For KStars issues, please file them at bugs.kde.org
