### ISSUE TITLE
indi-sbig driver limits binning by 3

### ISSUE THREAD

**Issue by ashindin** [indilib/indi#67]
I have SBIG STF-8300M ccd and I can set binning 9 under windows (I make airglow measurements) but indi-sbig driver limits it only to 3.

**Comment by knro** [comment]
Thanks for report, will look into it.

**Comment by ashindin** [comment]
Actually I solve this problem by changing a few lines in sbig_ccd.cpp

**Comment by knro** [comment]
What did you change? Please send a pull request
