### ISSUE TITLE
Bad variable definition in INDI driver (int instead of longint) prevents focuser connexion.

### ISSUE THREAD

**Issue by jcj2249** [indilib/indi#672]
Intermittently I had problem connecting my Microtouch focuser to KStars : the resource was busy.
I posted the issue "Microtouch focuser refuses to connect : Resource busy" in the thread http://indilib.org/forum/focusers-filter-wheels/3692-microtouch-focuser-refuses-to-connect-resource-busy.html.
Eric (TallFurryMan) found the reason : when the focuser step counter flew over 32767 ticks, the driver didn't respond correctly anymore.
I'm using KStars 2.9.7 on macOS.
Would it be possible to correct this problem in the next release ?

**Comment by knro** [comment]
THanks for the report. Looks like the driver was transformed from this: https://github.com/AzGilrock/Starizona/blob/master/MicroTouch/UsbPort.vb

However, get position is 16bit unsigned, up to 65536 ticks while the driver limits it to half of this range. Will work on a fix soon.

**Comment by jcj2249** [comment]
Thanks Jasem !

Have a nice evening.
__________
Jean-Claude
