### ISSUE TITLE
Document tolerance for null pointers in specific function parameters

### ISSUE THREAD

**Issue by elfring** [indilib/indi#676]
[The function “delXMLEle”](https://github.com/indilib/indi/blob/666a5f06644d11a26aaeefce0c957d5a6c20df16/libindi/libs/lilxml.c#L163 "Implementation of delXMLEle()") was implemented in the way that it checks if a null pointer was passed as an input parameter. It returns then immediately.

Can such a detail become an official property in the affected application programming interface?
How would you like to represent information about existing input parameter validation in [the corresponding API documentation](https://github.com/indilib/indi/blob/666a5f06644d11a26aaeefce0c957d5a6c20df16/libindi/libs/lilxml.h#L94 "Update candidate")?

**Comment by knro** [comment]
What's your suggestion exactly regarding this? Can you submit a PR to improve the API docs?

**Comment by elfring** [comment]
* I am looking for an acknowledgement from the main developers of this software for the mentioned technical detail before.
* Other designers expressed similar details in different ways for API documentations already. Which wording will get the desired consensus?

**Comment by knro** [comment]
Sorry I'm still not following, in the function documentation you want us to say that it's safe to pass nullptr?

**Comment by elfring** [comment]
Yes. (The function implementation contains the comment “benign if NULL” before the relevant condition check.)

**Comment by elfring** [comment]
* Have you got any wording preferences here?
* Will any tags become useful for such a function parameter property?

**Comment by knro** [comment]
The actual documentation for this function is in [lilxml.h](https://github.com/indilib/indi/blob/666a5f06644d11a26aaeefce0c957d5a6c20df16/libindi/libs/lilxml.h#L94) which not correct now since it says it returns a value when it is declared as void.

**Comment by elfring** [comment]
Why have you closed this issue?

**Comment by elfring** [comment]
Will it make sense to add null pointer tolerance also for the parameter “lp” of [the function “delLilXML”](https://github.com/indilib/indi/blob/eb29df827eb9ef00bace77229d5a406c6359bc7d/libindi/libs/lilxml.h#L89 "Checking function properties")?
