### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [indilib/indi#680]
I would like to point out that an identifier like “[`_LilXML`](https://github.com/indilib/indi/blob/eb29df827eb9ef00bace77229d5a406c6359bc7d/libindi/libs/lilxml.h#L72 "Update candidate")” [does eventually not fit](https://www.securecoding.cert.org/confluence/display/c/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier "Do not use identifiers which are reserved for the compiler implementation.") to the expected naming convention of the C language standard.
Would you like to adjust your selection for unique names?

**Comment by knro** [comment]
What? who else uses _LilXML in the standard C language?

**Comment by elfring** [comment]
How do you think about to avoid that this software [depends on undefined behaviour](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106 "Avoiding undefined behaviour?")?

**Comment by knro** [comment]
Ok thanks. I didn't know that _ followed by capital letter makes a reserved identified. Btw, is this audit part of some ongoing project?

**Comment by elfring** [comment]
Thanks for [your small source code improvement](https://github.com/indilib/indi/commit/fa60f910229494c5eb8e5552ad98eb858c1992f6 "Renaming of three data structure identifiers").
