### ISSUE TITLE
Plate solving with remote server

### ISSUE THREAD

**Issue by fmozza** [indilib/indi#732]
There are two issues:

1.The first problem is that building the latest version(s) of astronomy.net causes a problem where it will not execute if referenced using a symbolic link.  I think this is because at build time, the executables are linked to relative paths for the libraries, not absolute paths.  Thus, using  /usr/bin/solve-field and /usr/bin/wcsinfo fails - one has to use absolute paths.  I can't say if this is the case for the astronomy.net package that is installed from the core OS repositories. 

This is not strictly an EKOS problem (although it is impacted by this ...).  A reasonable work-around is to use the script below to execute the absolute paths:

`#! /usr/bin/env /bin/bash
prog=`basename "$0"`
/usr/local/astrometry/bin/$prog $@
exit`

I copy this to both /usr/bin/solve-field and /usr/bin/wcsinfo and everything works as it should.

2. The second problem is within the Alignment page on EKOS:  with the Remote solver selected, EKOS still checks that the executables are available on the local system, and if they are not, it fails, regardless of what exists on the remote server.

This should be addressed by checking the existence of the executables on the remote system and not on the local system.

**Comment by knro** [comment]
Thanks for the report, I'll check it out. However, This is not an INDI (driver) issue, so issues with Ekos should be filed in bugs.kde.org
