### ISSUE TITLE
weatherwatcher left sockets open

### ISSUE THREAD

**Issue by mmastria** [indilib/indi#744]
There's a small bug that left sockets open (WAIT_CLOSE) after read data from HTTP source.

weatherwatcher.cpp

279c279
old:             return true;
new:             rc = true;

I'll pull request on this.

**Comment by mmastria** [comment]
pulll request:
https://github.com/indilib/indi/pull/745

**Comment by knro** [comment]
Thanks for the fix! It's merged.
