### ISSUE TITLE
AstroPhysics Experimental tracking indicator initial synchronization

### ISSUE THREAD

**Issue by wotalota** [indilib/indi#748]
On my system when Ekos connects to the AstroPhysicExperimental mount, the telescope panel comes up unparked and with the tracking button indicating off (the off button is highlighted red). However the mount is tracking. 
Clicking the Tracking off button puts up a 'are you sure' message box which when confirmed does not turn tracking off. 
Selecting tracking on, then tracking off does stop tracking.

**Comment by knro** [comment]
@mikefulb Any ideas? Does the driver set SCOPE_TRACKING on startup if the mount was actually tracking initially?

**Comment by wotalota** [comment]
The key to reproduce appears to be dropping power on the mount.
1. disconnect & shutdown ekos  
2. turn off and reapply power to the mount
3. restart ekos & connect
4. mount (in my case) is unparked. no indication that it is moving tracking off & alt az values at park 
   values.
Without the initial application of power starting/stopping park/unpark etc does not appear to reproduce.

Went through the above today to check a camera setting and forgot about it, remembered after 3 hours
and found it as in the screenshot.
![track](https://user-images.githubusercontent.com/44623193/47827526-c7919b80-dd54-11e8-8e26-8f0218fe10c2.png)
