### ISSUE TITLE
Flat collection calibration setting impacting Light collection

### ISSUE THREAD

**Issue by wotalota** [indilib/indi#749]
System: Mach1, ASI071 oag:ASI120-s, when collecting Flats, calibrate is set to "The Wall" AZ: 280 00 00, ALT: 01 00 00. After flat collection is done with, including across KStars restarts, then attempt to collect lights.
Use mount control goto, use of solver, guiding started, then in CCD when starting to collect lights at the solved position the mount slews back to the wall position for flats which confuses the guider.
Selecting flats and setting the calibration from wall to manual allows lights to be captured but it does
not persist. The next time KStars is started calibration reverts to the wall again and collection of lights
fails. This is the case even though flats were not revisited and calibrate is greyed out.

**Comment by knro** [comment]
This is an Ekos bug, not INDI. Please file Ekos bugs at KDE https://bugs.kde.org

Furthermore, please attach the complete Ekos log when you submit it there.
