### ISSUE TITLE
synscan driver incorrect  coordinates

### ISSUE THREAD

**Issue by didierd089** [indilib/indi#762]
with the driver indi_syncan_telescope and indiserver v1.7.5 the mount returns incorrect coordinates in
ccd skychart sky and indi panel
the coordinates are correct in synscan pro
neq6 mount
worked correctly in v1.7.4

**Comment by knro** [comment]
Can you give an example?

**Comment by cstachon** [comment]
I have the same problem but it also means that the telescope icon on Kstars/CDC does not move from the RA/Dec values shown above plus the target starts off ok while slewing but as soon as racking starts the target reverts back to NGC7788 . Posted this on Indi Forum with some logs
