### ISSUE TITLE
IMAGE INFO

### ISSUE THREAD

**Issue by macicco** [indilib/indi#773]

**Comment by macicco** [comment]
While setting up DSLR NIKON 40 DX, I am supposed to configure pixel pirch, image resolution on INDI - Image Info tab. But , any attempt to press set button after size inputs figures

**Comment by macicco** [comment]
I tried manually set the size figures into file.xml, but even that did not work.

![screenshot from 2018-11-30 20-56-12](https://user-images.githubusercontent.com/5925289/49319141-8a026880-f4e2-11e8-8481-b93ec2a4d50d.png)

**Comment by macicco** [comment]
It seems my issue is analog  to issue  #365

**Comment by macicco** [comment]
> If you happen to use Ekos, then Ekos sets these values upon connection. You need to clear the DSLR values in order to re-enter them again.

Could you detail how clean values ? You mean, only "image info Tab" ?

**Comment by knro** [comment]
Just press the "trash bin" icon next to the CCD name in capture module then restart.
