### ISSUE TITLE
libusb error: indi_qhy_ccd did not claim interface 0

### ISSUE THREAD

**Issue by CCCMC825** [indilib/indi#774]
Operating System: Ubuntu 18.04 Bionic Beaver LTS
INDI Version: 1.7.5 (Stable)
KStars Version: 2.9.8 (Stable)
Cameras: QHY165C (Main) and QHY5L-II-C (Guide)
Symptoms: Ekos is frequently stuck when attempting to capture an exposure and eventually the system runs out of disk-space and becomes unaccessible. An inspection of disk usage using LiveCD Recovery revealed that a libusb error was logged into /var/log/syslog and /var/log/kern.log at a rate of SEVERAL HUNDREDS THOUSANDS TIMES A SECOND PER FILE. The exact error message is as follows:

`kernel: [3314.xxxxxx] usb 4-4: usbfs: process 3751 (indi_qhy_ccd) did not claim interface 0 before use`

`grep -c indi_qhy_ccd` reported 211,661,935 matches in /var/log/syslog.

**Comment by glowmouse** [comment]
It sounds like a connection to the camera was established,  lost,  and some part of the code didn't error handle gracefully.  I have a QHY camera; I'll see if I can reproduce the bug and add something helpful.
