### ISSUE TITLE
Year in GPSD and INDI client differ

### ISSUE THREAD

**Issue by elbarbudo** [indilib/indi#787]
I installed indi on a Raspberrry PI 2.
When I connect my old Garmin ETREX gps, I get repeated errors about "Date is negative" !
Running xgps show 1963 as the year.
But in INDI client connected to GPSD, I have the correct 2018 year.

On different forums about the Garmin GPS I found that the year was often wrong, but that does not explain why xgps and the indi-gpsd plugin gieve different answer.

Out of topic, but how can I tell GPSD to ignore the year send by the gps and use the system year  which is correct

**Comment by elbarbudo** [comment]
![xgps](https://user-images.githubusercontent.com/2513291/50282051-cfff7c00-0451-11e9-88fe-0fc924155a52.png)
![indi-client](https://user-images.githubusercontent.com/2513291/50282053-d0981280-0451-11e9-9c02-80d7ff46f345.png)
Screen captures showing the issue

**Comment by elbarbudo** [comment]
I found that my Garmin Etrex NEVER give the date to gpsd

**Comment by jochym** [comment]
The time is _always_ sourced from system time. See: https://github.com/indilib/indi/issues/823
