### ISSUE TITLE
Orion SSAG using indi_ssag_ccd driver messes up aborting exposure.

### ISSUE THREAD

**Issue by IvanBenak** [indilib/indi#794]
When aborting an exposure on with the Orion SSAG driver (indi_ssag_ccd), the exposure continues on in the background and causes erratic behavior (software restart required).  Upon reviewing the code, I noticed that the SSAGCCD::AbortExposure function does nothing other than return a true.  Looking at the other ccd driver examples, it would appear that they at minimum set the InExposure boolean variable to false so that when the TimerHit function happens, the image is ignored.  I've made that change in the attached code.  I have also added code to keep track of the handle when SetTimer has been called and terminate the handle with the RemoveTimer function.  I also added the option of "CCD_HAS_SHUTTER" to the capabilities as the technical specs for the actual ccd used says that it is supported.

[ssagccd.cpp.txt](https://github.com/indilib/indi/files/2719757/ssagccd.cpp.txt)

**Comment by knro** [comment]
Thanks! Please submit a PR with the changes.

**Comment by IvanBenak** [comment]
Okay, I believe I have done that successfully now. #796 is in the queue.
