### ISSUE TITLE
pmc8 needs method to change mount types

### ISSUE THREAD

**Issue by tolson2000** [indilib/indi#800]

**Comment by knro** [comment]
is this just a matter of alias or are there control protocol differences?

**Comment by tolson2000** [comment]
Looks like it is gear ratios, microstep differences, steps per revolution type things.

**Comment by tolson2000** [comment]
I don't much about INDI coding standards and the like. I found a table in their documentation which shows the different scales for the axis. So do you think all we need to change is the AXIS SCALEs...
#define PMC8_AXIS0_SCALE 4608000.0
#define PMC8_AXIS1_SCALE 4608000.0
to
#define PMC8_AXIS0_SCALE 4147200.0
#define PMC8_AXIS1_SCALE 4147200.0


![pmc8_motor_parameters](https://user-images.githubusercontent.com/9102687/50722507-8b005a00-108d-11e9-8562-e3c08a74cbc9.jpg)



I found this information in ES programmers reference...

**Comment by knro** [comment]
@mikefulb Hello Mike! What do you think? Maybe a property to select the mount type and then set these accordingly?

**Comment by mikefulb** [comment]
That looks reasonable.  I was going to make some changes but really 
wanted to get a mount from Jerry so I could test them but seems like 
you've got it covered thanks.

Michael Fulbright

**Comment by tolson2000** [comment]
I watched video on doing pull request. Did it. But I only see 3 of the 4 of my changed files in the commit request. The pmc8.h file did not show up. But there are some addtitions to it not in the indi master.
