### ISSUE TITLE
add arm64 in asi_zwo sdk

### ISSUE THREAD

**Issue by dragonlost** [indilib/indi#815]
Hello

Would it be possible to add the sdk arm64 for the camera/wheel asi in indi?

thanks

**Comment by knro** [comment]
It already supports arm64, what's the problem?

**Comment by dragonlost** [comment]
I have installed indi-full and kstars-bleeding but I do not have the zwo_asi driver available ( and sbig)

When I go to see the driver: https://github.com/indilib/indi/tree/master/3rdparty/indi-asi
I realized that there is no arm64 file unlike the sdk provided by zwo (unlike the altair driver for example)

**Comment by dragonlost** [comment]
Well I had not seen but there is the driver zwo. I search at ASI. Sorry for the inconvenience.
