### ISSUE TITLE
indi_lx200stargo: Option to disable keypad

### ISSUE THREAD

**Issue by NicDoebelin** [indilib/indi#821]
When the StarGo keypad is disconnected, the mount randomly aborts slews.

How to reproduce:
1. connect the keypad
2. unpark and perform some slews with the keypad
3. disconnect the keypad
4. perform several long slews in EKOS, check if the target object is reached

The mount randomly aborts the slews. This also happens on Windows when the keypad is not connected but not explicitly disabled in the StarGo ASCOM driver. To fix it I have to boot Windows and disable the keypad in the ASCOM driver.

Note that parking is not affected, only long slews.

**Comment by sterne-jaeger** [comment]
Nic, I haven't forgotten it, it's on my list as one of the next features.

**Comment by sterne-jaeger** [comment]
There is an update on my own indilib fork available: https://github.com/sterne-jaeger/indi/tree/stargo-1.5

I will test it a couple of days and will create a pull request.

**Comment by sterne-jaeger** [comment]
Closed with PR#945.
