### ISSUE TITLE
indi_sbig_ccd can't be installed

### ISSUE THREAD

**Issue by xcxjack** [indilib/indi#829]
My system is arm64 based Ubuntu 18.04, I tried two ways but both don't work:

1     From ppa.

pi@NanoPC-T4:~$ sudo apt-get install indi-sbig
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 indi-sbig:armhf : Depends: libindi1:armhf but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

2    Build and install

[  8%] Built target indi_eqmod_telescope
[ 11%] Built target indi_starbook_telescope
[ 13%] Built target indi_sx_wheel
[ 15%] Built target indi_sx_ccd
[ 16%] Built target indi_sx_ao
[ 18%] Built target sx_ccd_test
[ 20%] Built target indi_maxdomeii
[ 21%] Built target indi_nexdome
[ 22%] Built target indi_spectracyber
[ 24%] Built target indi_aagcloudwatcher
[ 25%] Built target aagcloudwatcher_test
[ 27%] Built target indi_nexstarevo_telescope
[ 31%] Built target indi_gphoto_ccd
Scanning dependencies of target indi_qsi_ccd
[ 31%] Building CXX object indi-qsi/CMakeFiles/indi_qsi_ccd.dir/qsi_ccd.cpp.o
[ 32%] Linking CXX executable indi_qsi_ccd
[ 32%] Built target indi_qsi_ccd
Scanning dependencies of target indi_sbig_ccd
[ 32%] Building CXX object indi-sbig/CMakeFiles/indi_sbig_ccd.dir/sbig_ccd.cpp.o
[ 33%] Linking CXX executable indi_sbig_ccd
/usr/bin/ld: skipping incompatible /usr/lib/gcc/aarch64-linux-gnu/7/../../../aarch64-linux-gnu/libsbig.so when searching for -lsbig
/usr/bin/ld: skipping incompatible /usr/lib/aarch64-linux-gnu/libsbig.so when searching for -lsbig
/usr/bin/ld: skipping incompatible //usr/lib/aarch64-linux-gnu/libsbig.so when searching for -lsbig
/usr/bin/ld: cannot find -lsbig
collect2: error: ld returned 1 exit status
indi-sbig/CMakeFiles/indi_sbig_ccd.dir/build.make:100: recipe for target 'indi-sbig/indi_sbig_ccd' failed
make[2]: *** [indi-sbig/indi_sbig_ccd] Error 1
CMakeFiles/Makefile2:791: recipe for target 'indi-sbig/CMakeFiles/indi_sbig_ccd.dir/all' failed
make[1]: *** [indi-sbig/CMakeFiles/indi_sbig_ccd.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by knro** [comment]
SBIG blob does not support arm64. Please contact SBIG to see if they can provide an arm64 build. We tried before and could not get any where.

**Comment by cgobat** [comment]
In that case, perhaps it would be wise to not build/publish `indi-sbig` for arm64? Or is [this, for example](https://launchpad.net/~mutlaqja/+archive/ubuntu/ppa/+build/32763008) something different?
