### ISSUE TITLE
KStars crash when Astrometry module is accessed in EKOS, with only astrometry driver active in INDI

### ISSUE THREAD

**Issue by GiGa-astro** [indilib/indi#831]
A few days ago, on a cloudy day :-(, I just wanted to download a few astrometry index files, so I started KStars (3.1), EKOS and INDI; and connected to the astrometry driver in INDI, as the only driver being connected. When I tried to open the astrometry module in EKOS, and KStars crashed immediately, leaving only the indilib server active. From this I assume that the astrometry module doesn't like being accessed if there is no camera and/or mount driver being connected to, for operations other than plate solving or polar alignment.

Even though I realize that the astrometry module is not intended to be used by itself as for only downloading index files, I would assume that normal behavior would be for KStars or EKOS to warn the user that drivers required for the normal operation of the astrometry module are not (yet) connected instead of crashing KStars. Not being sure if this is a KStars or EKOS issue, I posted here first.

Thanks for all your effort and help.

**Comment by knro** [comment]
Thanks for the report, but this is not an INDI issue, it's a KStars issue. Anyway, you cannot use Ekos without a CCD. So at least specify CCD simulator.
