### ISSUE TITLE
Missing x86 libatik 

### ISSUE THREAD

**Issue by pchev** [indilib/indi#845]
Last change for Atik SDK v2.2.0 remove the 32bit library  3rdparty/libatik/x86/libatikcameras.bin

Is it possible to have this file back?
My Atom netbook I use at the telescope is 32bit only.

**Comment by knro** [comment]
Ok, I will ask Atik to send me x86 build of the new SDK... I think we are close to removing support for x86-32 since everyone is dropping support for this architecture.

**Comment by pchev** [comment]
I use Ubuntu 18.04 that is supported until 2023 ... 
If necessary I can keep the Atik driver at the current level because it work fine, but I prefer if it can be included at least in the next stable version.
