### ISSUE TITLE
Indi::FocuserInterface Absolute Position should be signed 

### ISSUE THREAD

**Issue by james-lan** [indilib/indi#866]
The cause: 
So, what brought this up was that empirically, it works, with the whole chain when some extra checks I made were removed. When I submitted that up the chain, it got a INDI values shouldn't be negative, and that it breaks the interface. ( https://github.com/indilib/indi/pull/859 ) 

The reason why this is a problem is that OnStep currently supports :FZ (Zero) and :FH (Half) with defaults of +/- 25 (microns), By default it will initialize to 0 and 0. It does not support sync to other locations. While there are workarounds that can be done, I do not think it should be neccessary, as when my unncessary checks are removed (that pull request) and the values treated as ints, it works fine.

Thoughts: 
I looked around, and in fact in the actual INDI spec, it has one reference to an focuser with a negative position. (And not starting at 0, so I don't think that's a relative focuser.):

<defNumberVector device="OTA" name="Focus" state="Idle" perm="rw" timeout="50"
label="Focus position, μM"
<defNumber name="Focus" label="" format="%4.0f" min="-100" max="100" step="10">50</defNumber>
</defNumberVector>

So thinking this is something that's an arbitrary artifact from a few using full-in as zero and then having this convention be (IMO wrongly) included as a this must be it, I have gone through and looked at everything which has a MoveAbsFocuser call in both libindi/drivers and 3rdparty 

To summarize: 
There is one driver that treats it like an unsigned in an error message, none use an unsigned in for mount communication. (%d being the most common, which will throw it to a signed integer, and as far as gcc is concerned is a signed integer) 
Most drivers set .min to 0, which means that it being signed/unsigned is not an issue. 
With two exceptions, NO driver uses anything that's more than 20-bits. So we've got 12 unused bits as is, changing it to signed would mean only 11 unused bits. The two are OnStep and OnFocus. (Which internally use a 4 or 8 byte dependin on processor float and signed 32-bit int respectively.) 
Again, to emphasize it: Almost all drivers do treat it internally as an int, and not an unsigned int. 
Changing this (providied no errors in coding) will break nothing, and provide more flexibility, eliminating any need to use offsets. 

Again, it works perfectly if that uint is treated as an int. Which is is almost universally in drivers, many simply passing the uint32_to to an int (which can result in negative numbers), which even happens within the focuserinterface. 

This also allows for accurate matching with focusers which do use negative values, so that if there are bug reports, the values that INDI reports are the values that the software would see. 

Changes: 
Essentially all this amounts to would be removing a few lines of documentation (those stating the focuser can't be negative), and aside from the uint32_t no changes major changes would be required. 

As far as practical things. For example, if one step on an absolute focuser is moved per millisecond, that would take for 30-bits, 12 days or more. 20-bits is 17 minutes. Which aside from one driver (Amusingly OnStep's cousin OnFocus) is the max used. So there's basically no risk of an overflow for the 32 to 31 positive bytes. 

Here's a list of going through everything which uses it, and I know I saw a focuser that uses a negative value, but perhaps it was changed, I'll do the work to change it and a pull request. However, I wanted to raise this as an issue, because it's something that seemed to get a rather strong reaction from @knro . 

However, after looking through this, I believe the 0 point requirement has no point, and to properly deal with it as an uint32_t would require a bunch more work than treating it as an int, which would actually be more consistent with how it's used internally. For almost all of the drivers I looked at the only changes would need to be uint32_t > int32_t, possibly the addition of a .min = 0 and possibly an addition of a data type. (Moonlite, for example, assignes a variable within the function which is just set equal to the other.)

As noted the only thing which treats it as unsigned aside from a few like that, is one that uses it in a printf, informational message, that's it. 

Apologies if this is a bit long, but it's something that's arbitrary, doesn't match how things are used within the interface (and changing it to match the documentation would break things.) and requires minimal effort to make more useful. Possibly simplfies things for some drivers as well, as I noticed a few references to offsets, but I was already going through enough information, and I don't propose to change those right now. 

I'll be making a branch and submitting a pull request if there's no good arguement for keeping it the way it is in a few days. 

Going forward the following would be the case: 

All drivers must set: 
FocusAbsPosN[0].min (Even if = 0, which would be the same behavior, as currently exists, with unsigned)
FocusAbsPosN[0].max (which would also be a signed 32-bit int) 
Absolute Position is a 32-bit signed integer (int32_t) 

Relative motion would be kept as uint32_t as it exists. With specified direction/sign. 

*******
in libindi/drivers

focuser/steeldrive.cpp:IPState SteelDrive::MoveAbsFocuser(uint32_t targetTicks)

Sets FocusAbsPosN[0].min = 0
Output format to device :F9%07d#
Max:
double focusMaxPos  = floor(fSettings[i].maxTrip / fSettings[i].gearRatio) * 100;
FocusAbsPosN[0].max = focusMaxPos;
 

focuser/moonlite.cpp:IPState MoonLite::MoveAbsFocuser(uint32_t targetTicks)

Output format to device :SN%04X#  (Hex)
16-bit Output, unsigned

focuser/onfocus.cpp:IPState OnFocus::MoveAbsFocuser(uint32_t targetTicks)

    FocusAbsPosN[0].min = 0.;
    FocusAbsPosN[0].max = 10000000.;

So at most 24 bit

    snprintf(cmd, 24, ":MA%d#", position);

Theoretically, it can be a 32-bit signed integer, and is internally. 

focuser/robofocus.cpp:IPState RoboFocus::MoveAbsFocuser(uint32_t targetTicks)
focuser/robofocus.cpp:    return MoveAbsFocuser(FocusAbsPosN[0].value + (ticks * (dir == FOCUS_INWARD ? -1 : 1)));

Sets FocusAbsPosN[0].min as 0
Output ungh (lots of if chains)

FO%06d Max is 99999

focuser/smartfocus.cpp:IPState SmartFocus::MoveAbsFocuser(uint32_t targetPosition)
focuser/smartfocus.cpp:        LOGF_DEBUG("MoveAbsFocuser: destination= %d", destination);
focuser/smartfocus.cpp:        if (send(command, sizeof(command), "MoveAbsFocuser"))
focuser/smartfocus.cpp:            if (recv(&respons, sizeof(respons), "MoveAbsFocuser"))
focuser/smartfocus.cpp:                LOGF_DEBUG("MoveAbsFocuser received echo: %c", respons);
focuser/smartfocus.cpp:                    LOGF_ERROR("MoveAbsFocuser received unexpected respons: %c (0x02x)", respons,
focuser/smartfocus.cpp:    return MoveAbsFocuser(position + (dir == FOCUS_INWARD ? -ticks : ticks));

FocusAbsPosN[0].min   = 0.;
Output 16 bit. 
        command[1] = ((destination >> 8) & 0xFF);
        command[2] = (destination & 0xFF);

focuser/sestosenso.cpp:IPState SestoSenso::MoveAbsFocuser(uint32_t targetTicks)
focuser/sestosenso.cpp:    rc = MoveAbsFocuser(newPosition);

snprintf(cmd, 16, "#GT%d!", targetTicks);
    FocusAbsPosN[0].min   = 0.;

focuser/moonlite_dro.cpp:IPState MoonLiteDRO::MoveAbsFocuser(uint32_t targetTicks)

FocusAbsPosN[0].min   = 0.;
Same as Moonlite 

(Might need explicit cast to unsigned int) 
Change:     targetPos = targetTicks; to uint32_t targetPos = targetTicks;

focuser/lakeside.cpp:    return MoveAbsFocuser(dir == FOCUS_INWARD ? FocusAbsPosN[0].value - ticks : FocusAbsPosN[0].value + ticks);
focuser/lakeside.cpp:IPState Lakeside::MoveAbsFocuser(uint32_t targetTicks)

sprintf(cmd, "CO%d#", abs(calc_steps));
FocusAbsPosN[0].min = 0.;
Max read at startup per comment

focuser/nstep.cpp:IPState NSTEP::MoveAbsFocuser(uint32_t targetTicks)

    FocusAbsPosN[0].min  = 0;
    FocusAbsPosN[0].max  = 999999;
    
Sends in 0-999 and uses a running tally system. 
snprintf(cmd, NSTEP_LEN, ":F%d%d%03d#", direction, mode, nextMotion);
    

focuser/focus_simulator.cpp:IPState FocusSim::MoveAbsFocuser(uint32_t targetTicks)
focuser/focus_simulator.cpp:        return MoveAbsFocuser(targetTicks);

Never sets min. 

focuser/focuslynxbase.cpp:        return (MoveAbsFocuser(FocusAbsPosN[0].max / 2) != IPS_ALERT);
focuser/focuslynxbase.cpp:IPState FocusLynxBase::MoveAbsFocuser(uint32_t targetTicks)
focuser/focuslynxbase.cpp:    return MoveAbsFocuser(newPosition);

<%sMA%06d>
        FocusAbsPosN[0].min = SyncN[0].min = 0;

focuser/dmfc.cpp:IPState DMFC::MoveAbsFocuser(uint32_t targetTicks)

snprintf(cmd, 16, "M:%d", newPosition);
    FocusAbsPosN[0].min   = 0.;
    FocusAbsPosN[0].max   = 100000.;

focuser/usbfocusv3.cpp:IPState USBFocusV3::MoveAbsFocuser(uint32_t targetTicks)
focuser/usbfocusv3.cpp:            MoveAbsFocuser(targetPos);

    FocusAbsPosN[0].min   = 0.;
    FocusAbsPosN[0].max   = float(maxpos);
    maxpos    = 65535;

Also checks if move will be less than 0. 

focuser/tcfs.cpp:                    MoveAbsFocuser(startPos);
focuser/tcfs.cpp:                    MoveAbsFocuser(startPos);
focuser/tcfs.cpp:IPState TCFS::MoveAbsFocuser(uint32_t targetTicks)

FocusAbsPosN[0].max  = 9999; or 7000 depending
Does use a rather complicated setup, with relative movments. 
%04d is used, but 

(Change to add .min explicitly) 

focuser/microtouch.cpp:IPState Microtouch::MoveAbsFocuser(uint32_t targetTicks)

    FocusAbsPosN[0].min   = 0.;
    FocusAbsPosN[0].max   = 60000.;

    write_buffer[0] = cmd;
    write_buffer[1] = val % 10;
    write_buffer[2] = (val / 10) % 10;
    write_buffer[3] = (val / 100) % 10;
    write_buffer[4] = (val / 1000);

Comment: Gotta love odd methods of communication. 
Changes: Only needs unsigned removed and uint changed 

focuser/perfectstar.cpp:IPState PerfectStar::MoveAbsFocuser(uint32_t targetTicks)
focuser/perfectstar.cpp:    return MoveAbsFocuser(finalTicks);

    // 20 bit resolution position. 4 high bits + 16 lower bits

Changes: Only unsigned changed

telescope/lx200_OnStep.cpp:virtual IPState      MoveAbsFocuser (uint32_t targetTicks)
telescope/lx200_OnStep.cpp:IPState LX200_OnStep::MoveAbsFocuser (uint32_t targetTicks) {
telescope/lx200_OnStep.cpp:             LOGF_DEBUG("MoveAbsFocuser called with targetTicks == %s, :FS%06d#, which may be negative, i gives %i, u gives %u ", read_buffer, targetTicks, targetTicks, targetTicks);

Command accepts doubles, min and max determined by firmware, default is +/- 25

rotator/gemini.cpp:IPState Gemini::MoveAbsFocuser(uint32_t targetTicks)
rotator/gemini.cpp:    return MoveAbsFocuser(newPosition);

uint32_t maxPos = 0;
    rc = sscanf(response, "%16[^=]=%d", key, &maxPos);
    if (rc == 2)
    {
        FocusAbsPosN[0].max = maxPos;
        FocusAbsPosN[0].step = maxPos / 50.0;
        FocusAbsPosN[0].min = 0;

    snprintf(cmd, 32, "<F100MOVABS%06d>", targetTicks);

Note:First one which uses uint32_t for maxPos, but that value can't be altered. Per actualygoing and looking at the Gemini manual, it doesn't explicitly say, but the default is 115200, and it can't be set using more than 6 decimal digits. 

Change: (See note) uint32 > int32

rotator/integra.cpp:IPState Integra::MoveAbsFocuser(uint32_t targetTicks)

Uses ints internally, manually checks for < 0 (Extra) 

FocusAbsPosN[0].min   = 0;
FocusAbsPosN[0].max   = MaxPositionN[0].value;

Change: only uint > int

rotator/nightcrawler.cpp:IPState NightCrawler::MoveAbsFocuser(uint32_t targetTicks)

Uses int32 internally, 

    FocusAbsPosN[0].min = 0.;
    FocusAbsPosN[0].max = 100000.;
    
Change: Only uint > int

auxiliary/pegasus_upb.cpp:IPState PegasusUPB::MoveAbsFocuser(uint32_t targetTicks)
auxiliary/pegasus_upb.cpp:    return MoveAbsFocuser(dir == FOCUS_INWARD ? FocusAbsPosN[0].value - ticks : FocusAbsPosN[0].value + ticks);

    snprintf(cmd, PEGASUS_LEN, "SM:%d", targetTicks);
    snprintf(expected, PEGASUS_LEN, "M:%d", targetTicks);

**** 3rdparty **** 

indi-armadillo-platypus/arm_plat_focuser_common.h:    virtual IPState MoveAbsFocuser(uint32_t targetTicks) override;
indi-armadillo-platypus/arm_plat_focuser_common.cpp:IPState ArmPlat::MoveAbsFocuser(uint32_t targetTicks)

    sprintf(cmd, "!step goto %d %i %i#", port, targetTicks, backlash );
    FocusAbsPosN[0].min   = 0.;
    FocusAbsPosN[0].max   = 100000.;

indi-fli/fli_pdf.cpp:IPState FLIPDF::MoveAbsFocuser(uint32_t targetTicks)
indi-fli/fli_pdf.cpp:        LOGF_ERROR("FLIPDF::MoveAbsFocuser: FLIGetStepperPosition() failed. %s.", strerror((int)-err));
indi-fli/fli_pdf.cpp:    return MoveAbsFocuser(new_rpos);
indi-fli/fli_pdf.h:    virtual IPState MoveAbsFocuser(uint32_t ticks) override;
indi-avalon/lx200stargofocuser.cpp:        FocusAbsPosNP.s = MoveAbsFocuser(absolutePosition);

Appears to use timer based. 
    FocusAbsPosN[0].min   = 1;
    FocusAbsPosN[0].max   = FLIFocus.max_pos;

    if (targetTicks < FocusAbsPosN[0].min || targetTicks > FocusAbsPosN[0].max)

Per the website: 
Number of Steps: 105,000 

So that should be settable as an upper bound on it.

indi-avalon/lx200stargofocuser.cpp:IPState LX200StarGoFocuser::MoveAbsFocuser(uint32_t absolutePosition) {
indi-avalon/lx200stargofocuser.cpp:    return MoveAbsFocuser(absolutePosition);
indi-avalon/lx200stargofocuser.h:    IPState MoveAbsFocuser(uint32_t absolutePosition) override;

sprintf(command, ":X16%06d#", AVALON_FOCUSER_POSITION_OFFSET + targetFocuserPosition);

Note, while using FocusAbsPosN min and max, does not set them as far as I can tell

This has a position offset, so I'm not sure if that's to allow it to be negative or not, this seems to be reverse engineered as opposed to having a protocol document. (Gotta love that. :( )

**Comment by knro** [comment]
The zero being the minimum is there by definition of INDI Library API (not INDI Wire API it's not related to this). It's just there to make things easier for everyone to agree upon. Zero means fully retracted, there is no ambiguity there, it's a nice number that everyone can agree upon. it's the same for inward vs outward, but definition inward is negative and outward is positive.

Most of the focuser protocols we dealt with don't deal with signed absolute positions. Maybe a few do, but the majority do not, and for a good reason, it's just easier to deal with. The SYNC feature is there so that if by going to a negative offset, you are creeping into the negative absolute position, you can SYNC to any arbitrary position and then go back, and then SYNC again.
