### ISSUE TITLE
QHYCFW2 can't set number of filters

### ISSUE THREAD

**Issue by RCompassi** [indilib/indi#897]
Can't set the number of filters on standalone QHYCFW2. Using the number of filters slider on the main control tab to set and save it to 7 does nothing, upon connecting the FW it returns to the default 5 slots.

Running on ubuntu mate and raspberry pi3b+ (astroberry)
KSTARS 3.2.0 build 2019-03-28T18:34:49Z

**Comment by knro** [comment]
What's the driver version for QHYCFW2?

**Comment by RCompassi** [comment]
In the drive Info, it says 1.0.

**Comment by RCompassi** [comment]
Ok, managed to update the qhy driver for 1.2.

Ok, here's what I've done:
Pulled the indilib from github
compiled the library
compiled the 3rd party driver indi-qhy mannualy and installed
THEN it updated to driver version 1.2, and now i can set the number of filter slots correctly.
For some reason, the nightly does not update the driver?

**Comment by knro** [comment]
Nightly can get delayed due to launchpad issues sometimes. Issue is resolved, thanks!
