### ISSUE TITLE
[indi_starbook_telescope] Parser & formatter of HMS is incorrect.

### ISSUE THREAD

**Issue by lkcheng89** [indilib/indi#908]
Format of RA in the response to GETSTATUS should be HH+MM.m rather than HH+MM.SS (i.e "m" is one tenth of a minute which is ranged from 0-9) This is tested with my Starbook S and not sure that another models like 1 & TEN behave similarly.

**Comment by not7cd** [comment]
Not only 2 lines, but also parser in constructor. It should be 
refactored to `operator>>` and without regex. As seen in newer novalib 
wrappers.
