### ISSUE TITLE
Ekos Alignment module fails to recognise index files

### ISSUE THREAD

**Issue by zacn** [indilib/indi#911]
Recently tried KStars/INDI/Ekos for first time. I was running indiserver on a RPi3B+ connected to an HEQ5 Pro and a ZWO ASI185. The camera was on a Celestron C8 with an f6.3 focal reducer giving a field of view 19.6' by 12.4'. I was controlling the set up using a KStars/INDI/Ekos client (Kstars version 3.1.1) running on a 64bit laptop using Linux Mint Mate 19 Tara.

Telescope control using INDI and the KStars star map worked fine with the telescope slewing to the target (Arcturus) and tracking.

I ran into problems when trying to use the Ekos Alignment module. The "Capture & Solve" function failed to solve repeatedly. Ekos produced a warning that the Astrometry index files 4200 to 4205 were missing. The laptop had a complete set of the Astrometry files from 4200_00 to 4219 (as did the RPi) and these could be accessed via the alignment module options/Index Files buttons. The camera was taking images (via the camera module) and these showed several stars. I slewed the telescope to Vega to try a different patch of sky but got exactly the same results.

The following night I tried again with the same set up. By mistake I set up the field of view in the alignment module to a lower value (13' by 9.8') and the error message this time reported that files 4200 to 4204 were missing (not the 4200 to 4205 when the field of view was set to 19.6' by 12.4). Otherwise the results were as before with the astrometry solver invoked by "Capture & Solve" never solving.

Later I tested the laptop and its software alone using Astrometry accessed via the "solve-field" command. The program solved location using images of M31 and the Pleiades.

I then tested the laptop with KStars/INDI/Ekos using the "simulators" profile. With the alignment module field of view set to 128' by 96' invoking "Load & Solve" produced an error message that index files 4205 to 4211 were missing. The solver completed satisfactorily, however, and the simulated telescope slewed to the correct target (M31). The automatic "Capture & Solve" follow on, when the module took a simulated image of the sky, repeatedly failed to solve. Attempting to "Capture & Solve" using the simulated camera always resulted in a failure to solve.

The Ekos warning about missing index files seems to be a bug. Whether the failure to "Capture & Solve" results from the same problem is not clear.

**Comment by knro** [comment]
This issue tracker is for INDI server + driver issues. For KStars/Ekos bugs, they need to be filed at bugs.kde.org
