### ISSUE TITLE
SkySafari 6 Pro will not connect with Synscan mount

### ISSUE THREAD

**Issue by KjetilLe** [indilib/indi#943]
I can connect with SkySafari 6 Pro when I select Telescop Simulator as Mount in Indi.
However, when I scange the mount to Synscan (connected through USB to serial cable), SkySafari is unable to connect. I get the message "SkySafari Pro can't make a wireless connection to the scope. If you're using a bluetoth serial adapter, make sure that it's turned on and paired with the Android device. If you're using wifi, make sure you've joined the scope's Wi-Fi, and entered its IP address correctly."

In Indi control panel I get the message "SkySafari Server is running. Connect the App now to this machine using SkySafari LX200 driver. 
(In SkySafari I have selected Meade LX200 GPS/ACF, LX600 driver.) 
(I have also tried the others Meade mounts in SkySafari with no luck.) 

K-stars is working fine, the problem is only to Connect SkySafari.

**Comment by KjetilLe** [comment]
I use Stellarmate version 1.3.5 and the software updater says I am up to date.

**Comment by KjetilLe** [comment]
Thank you again for Your fast reply, but how do I incorporate this in the system?

Best regards
Kjetil
________________________________

**Comment by TallFurryMan** [comment]
Shift your stellarmate to pick updates from nightly builds with "sudo add-apt-repository ppa:mutlaqja/indinightly", update once the mentioned commit is built by Jasem's ppa.

**Comment by knro** [comment]
It's not yet available, I'm still working on the client part (KStars) since it needs to be updated. This is not really a "fix" it is just convenience. The issue is that the Snoop Telescope property in Options in the SkySafari driver is not set to your mount, so now I'm updating the client (KStars) to do this automatically. But you can do it yourself once and just change the field from Telescope Simulator to Synscan or whatever mount you're using and it should be set.

**Comment by KjetilLe** [comment]
Hi

I tried again this morning, but it is still not working. I enclose the log.
 In SkySafari I get message: "SkySafari Pro can make a wireless connection to the scope, but the scope is not responding. Make sure the scope is powered on and connected correctly. Also make sure that you select the correct scope type."

In K-star: "[Error] Internal client is not connected! Please make sure the mount name is set in the Options tab. Disconnect and reconnect to try again."

I hope this helps to solve the problem.

Best regards
Kjetil

________________________________

**Comment by knro** [comment]
Did you check SkySafari INDI driver ---> Options --> Snoop Telescope

That should be set the the mount name you're using. Then click "Save" after that. Then disconnect/reconnect.

**Comment by KjetilLe** [comment]
Hi

My first attempt was With synscan, but changing to Snoop telescope does not help.

Shall I make a New log file?

Best regards
Kjetil
________________________________

**Comment by knro** [comment]
Please attach a screenshot of the SkySafari driver Options tab.

**Comment by KjetilLe** [comment]
Here it is.

Best regards
Kjetil
________________________________

**Comment by KjetilLe** [comment]
![SkySafari](https://user-images.githubusercontent.com/50326921/57980865-f7726900-7a30-11e9-91b5-74d9d9d782af.jpg)
![Bluetooth](https://user-images.githubusercontent.com/50326921/57980871-048f5800-7a31-11e9-9d01-491d581b2cbb.jpg)

**Comment by KjetilLe** [comment]
Above is the screenshot you requested some days ago.
Regarding the Bluetooth Connection: I connect the Bluetooth dongle from the Bluetooth menue on the main screen shown on the photo and I get a connection. Then I Guess the baud rate is agreed upon (I am no expert here). However I do not get a flashing yellow ligt in the dongle (as I get when I onnect to the mount via Bluetooth directly (without Stellarmate) from SkySafari 6 Pro to the mount (chosing SkyWatcher SynScan in the SkySafari menue). When I do this I have a steady green light and a flashing yellow light at the Bluetooth dongle.
The dongle is connected when I open and start Kstars, but the Bluetooth Connection will not Connect.
Before investigating further I would like to know that this is the correct procedure. In Ekos I can not select the Serial port Assistant and that confuses me.

**Comment by KjetilLe** [comment]
I have tried all the Baud rates, but I get the Warning that the port/dev/rfcomm0 is already used by another driver or process no matter which Baud rate I use.

**Comment by KjetilLe** [comment]
SkySafari connects now with Stellarmate 1.4.2 using EQMod mode.
