### ISSUE TITLE
Bluetooth will not connect

### ISSUE THREAD

**Issue by KjetilLe** [indilib/indi#944]
I can connect to my Synscan using an USB to serial cable, but I can not connect using a Bluetooth dongle (Firefly). The Bluetooth device connects and I get up- and downloads.

When scanning ports I get 3: /dev/rfcomm0, /dev/ttyACM0 and /dev/ttyUSB0.
None of the ports will connect.
When using /dev/rfcomm0, which I believe is the correct one, I get the following error message: [Warning] Port /dev/rfcomm0 is already used by another driver or process. I get the same message using /dev/ttyACM0. For dev/ttyUSB0 I get the message [Error] Serial read error: Timeout error.

I use Stellarmate version 1.3.5 and the software updater says I am up to date.

**Comment by knro** [comment]
/dev/rfcomm0 is indeed the correct one. Can you disconnect all other devices and just keep the bluetooth to see if that works?

**Comment by KjetilLe** [comment]
Thank you for the quick reply.
I have tried as you proposed and here is the logfile. (I had to add a CCD to be able to run.)
________________________________

**Comment by knro** [comment]
Did you try different baud rates?

**Comment by KjetilLe** [comment]
Above is the screenshot you requested some days ago.
Regarding the Bluetooth Connection: I connect the Bluetooth dongle from the Bluetooth menue on the main screen shown on the photo and I get a connection. Then I Guess the baud rate is agreed upon (I am no expert here). However I do not get a flashing yellow ligt in the dongle (as I get when I onnect to the mount via Bluetooth directly (without Stellarmate) from SkySafari 6 Pro to the mount (chosing SkyWatcher SynScan in the SkySafari menue). When I do this I have a steady green light and a flashing yellow light at the Bluetooth dongle.
The dongle is connected when I open and start Kstars, but the Bluetooth Connection will not Connect.
Before investigating further I would like to know that this is the correct procedure. In Ekos I can not select the Serial port Assistant and that confuses me.

**Comment by KjetilLe** [comment]
I have tried all the Baud rates, but I get the Warning that the port/dev/rfcomm0 is already used by another driver or process no matter which Baud rate I use.

**Comment by knro** [comment]
Can you please try to see if this is an issue as in the latest SM OS v1.4.0?

**Comment by KjetilLe** [comment]
Same result With v1.4.0. I can Connect via Serial cable but not via Bluetooth. 
I seems that the Bluetooth dongle Connects (to Serial port 6), but I get the Message that 6 is already in use.
![serial](https://user-images.githubusercontent.com/50326921/58642667-1957cf80-82fe-11e9-97f8-4bea68a8bbf5.jpg)
![serial](https://user-images.githubusercontent.com/50326921/58642688-21177400-82fe-11e9-85be-1cd53f1ee5ff.jpg)
![Bluetooth](https://user-images.githubusercontent.com/50326921/58642697-25439180-82fe-11e9-9385-141b5e3963ba.jpg)

**Comment by KjetilLe** [comment]
![Warning](https://user-images.githubusercontent.com/50326921/58642838-6471e280-82fe-11e9-8d7d-88da2eed9fa1.jpg)

**Comment by knro** [comment]
Ok can you build libindi from source? If yes, I can suggest one patch that we can check if it works out for you. Or if you have TeamViewer setup on SM OS and ready, open a support ticket at StellarMate and we can arrange time for the TV setup.

**Comment by KjetilLe** [comment]
Hi Jasem

I am not a libindi Builder, but TeamViewer can be arranged. However I will be away from home the Next 2-3 weeks doing a Hydro Power Station commissioning. I will contact you when I am back home.

best regards
Kjetil
________________________________

**Comment by knro** [comment]
v1.8.1 should have the fix. Can you see if it works with latest stable INDI?

**Comment by KjetilLe** [comment]
Hi Jasem
I can confirm that is working with this update.
Than you.

Best regards
Kjetil
________________________________
