### ISSUE TITLE
Pentax DSLR does not fire

### ISSUE THREAD

**Issue by KjetilLe** [indilib/indi#946]
I have tried to connect via USB Stellarmate to the camera USB (one at the time):
Pentax K-5, Pentax K-3, Pentax K-1ii.

The cameraes are recognized and the driver info Gphoto CCD, version 2.6, interface 10 exec indi_pentax_CCD.

I get the warning: Didn't find any exposure widget. Are you sure the camera is set to Bulb mode?
(Which it is.)

Not sure what this means:
1) Do I need a separate, special cable to the shutter control Jack on the camera, which for Pentax just are (relay) conacts closing one for focus and another for shutter. 
2) Program bugs?  

On different forums I can find pieces of information regarding this, but not the Whole story.

**Comment by KjetilLe** [comment]
Working now With Stellarmate 1.4.2

**Comment by Ucarre** [comment]
Hi! Ihave the same problem on Stellarmate and icant fix it. Can you help me? 
I have put /dev/ttyUSB0 in the shutter port and said that the bulb mode is enabled but the camera didnt shot... i dont know what to do- Thanks!!
