### ISSUE TITLE
LX200GPS and ACK issue

### ISSUE THREAD

**Issue by Biscuit47** [indilib/indi#979]
[LX200_issue_log.txt](https://github.com/indilib/indi/files/3352969/LX200_issue_log.txt)

Every attempt to connect to the mount (Driver: indi_lx200gps, Version 2.0, Interface 5) fails. Serial port is enabled at 9600 baud (and I tested at every baud rate).   It always returns "LX200 GPS : "[DEBUG] Failure. Telescope is not responding to ACK!".  

The mount is an LX200 GPS using the latest firmware from Meade.  

The port on the mount is fine; I can connect and run the mount through ASCOM drivers.  It will not work with EKOS/Indi drivers.  I even purchased and tried a second connecting cable.

**Comment by knro** [comment]
Thanks for the log. After you plugin your cable, can you open "Mate Terminal" in StellarMate and type in:

`dmesg`

and copy the output here?
