### ISSUE TITLE
mutex in StreamManager::asyncStream

### ISSUE THREAD

**Issue by nadvornik** [indilib/indi#980]
**Describe the bug**

With my limited knowledge of C++ I'd say that the lock at https://github.com/indilib/indi/blob/master/libindi/libs/stream/streammanager.cpp#L270 does not work as intended. It is released immediately.

**Comment by knro** [comment]
Absolutely! This bug was introduced by the DETECTOR_INTERFACE patch and my bad I didn't catch that. Working on a fix now!
